### ISSUE TITLE
Unlinking a topo in edit mode (via ajax api) doesn't remove route line from topo

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#711] opened 2012-08-06 03:58 UTC

**Comment by Mdemaillard** [comment] 2020-03-11 18:04
Until topo is saved and refreshed. Still the case.

**Comment by Mdemaillard** [comment] 2020-03-13 06:12
Duplicate of #24 
Closing this one to clean up, ill put the name in #24 since its the only info here.

**Closed by Mdemaillard** 2020-03-13 06:12 UTC
Labels: 2: Bug fix, Feature: Phototopo
