### ISSUE TITLE
Corrupt stream layout

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3555] opened 2019-11-12 08:05 UTC
**What happened?**
Just loaded my dashboard and got a weird lyout of the stream:

![grafik](https://user-images.githubusercontent.com/1528540/68653733-a4372a00-052c-11ea-8bf5-c597ef13c2a4.png)

**Comment by brendanheywood** [comment] 2019-11-12 13:16
I've found the root cause of this and got a patch on the way

**Comment by lordyavin** [comment] 2019-11-20 11:45
So it's not yet hotfixed, right?

Happened again:

![grafik](https://user-images.githubusercontent.com/1528540/69236373-a5530180-0b93-11ea-96f2-7f8a32992815.png)

**Comment by brendanheywood** [comment] 2019-11-20 13:08
@lordyavin if we hot fix something we will update and close the github issue. This will be in the next release

**Comment by scd** [comment] 2019-12-17 02:08
I am closing this because it should have been fixed for last release.

**Closed by scd** 2019-12-17 02:08 UTC
Labels: 2: Bug fix, Area: Streams / feeds
