### ISSUE TITLE
user logbook, weird return page after editing 1 ascent

### ISSUE THREAD

**Issue by Mdemaillard** [theCrag/website#3598] opened 2020-03-08 09:31 UTC
**What happened?**
On desktop, chrome
From my logbook (https://www.thecrag.com/ascents/by/mdemaillard) , listing all my ascents:
after editing one ascent via the drop-down menu on the right, then saving.
the logbook gets displayed again, but with "no ascent found". There is no filter visibly selected, despite what the URL suggest. (probably filtered on the ascent previously edited ?)
Refreshing the result by using "Apply Filter" brings the World ascent logbook instead of mine

Example url(s) to reproduce the problem:
https://www.thecrag.com/ascents/by/mdemaillard%2525253Fpage%2525253D2

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/60388146/76160015-f67d0600-612e-11ea-8838-70516c50587d.png)

**What you expected:**
* [ ] after saving, come back to MY logbook 
* [ ] nice to have: come back on the exact page state as before selecting the ascent to edit

**Comment by scd** [comment] 2020-03-08 10:01
Can I ask if this was on the second page. 

It looks like you should be returning to

https://www.thecrag.com/ascents/by/mdemaillard?page=2

but the ? and = have been endoded and then re-encoded.

**Comment by Mdemaillard** [comment] 2020-03-08 10:22
Correct, the ascent edited was on the second page of my logbook

**Comment by rouletout** [comment] 2021-01-09 14:53
I can'T reproduce that - i tried first page, second page and last page. i always land on page 1 with the full list, closing

**Closed by rouletout** 2021-01-09 14:53 UTC
Labels: 2: Bug fix, Area: Navigation
