### ISSUE TITLE
Lat/long edits not working when made from "Bulk Edit" or "Edit this sector" page

### ISSUE THREAD

**Issue by oliverstory** [theCrag/website#1469] opened 2014-05-26 12:56 UTC
Hi guys

I recently tried to update the descriptions and lat/long coordinates for three out of the five routes in this sector:
http://www.thecrag.com/climbing/australia/orroral-ridge/legoland/area/419280090

I re-visited to upload topo photos the next day, and while the description edits had taken effect the GPS coordinates were still showing the 'approximate location' of the sector as a whole. Tried again to edit the lat/long details via the 'Bulk edit' button (just below the 'Description' section) and confirmed that the changes were not saved.

I then viewed the route 'Goose Step', clicked the 'Edit route' button and added the GPS coordinates on that page. The coordinates were saved.

As a third test I returned to the sector page, clicked the 'Edit this sector' button and added GPS coordinates for two more routes. The GPS coordinates weren't saved.

So it appears GPS coordinate editing isn't working for either the 'edit sector' or 'bulk edit' buttons, but is when you edit a single route.

Cheers
Oliver

**Comment by oliverstory** [comment] 2015-08-23 05:16
Update: I now can't add lat/long coordinates through the single-route edit page either.

Just tried with 'Faded Youth' and 'Live Injection' at this crag: http://www.thecrag.com/climbing/australia/orroral-ridge/honeysuckle-crag/area/418352766

The coordinates I entered aren't saved.

Cheers
Oliver

**Comment by Mdemaillard** [comment] 2020-03-17 13:37
duplicate of #1046. Closing here.

**Closed by Mdemaillard** 2020-03-17 13:37 UTC
Labels: 2: Bug fix, Area: Maps, Content editing
