### ISSUE TITLE
Locating something shows unrelated area name

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2530] opened 2017-01-15 06:24 UTC
Guessing it's just pulling the name of the previous crag in the list instead of the current one
![image](https://cloud.githubusercontent.com/assets/22091505/21960691/75bcc890-db47-11e6-93b3-f5145c635b1d.png)

**Comment by brendanheywood** [comment] 2017-01-15 11:15
thanks @DaneEvans this is a duplicate of #1903 so I will close this one, I've pinged you on the other so that you'll get notified on it as we work on it

**Closed by brendanheywood** 2017-01-15 11:15 UTC
