### ISSUE TITLE
Slash-grade parsing error

### ISSUE THREAD

**Issue by Basti-muc** [theCrag/website#3174] opened 2018-05-13 20:16 UTC
**What happened?**

9+/10- is entered, non-existent 9+/11- is displayed 
See here: https://www.thecrag.com/climbing/germany/frankenjura/megalumania/route/1798646523

**What you expected:**
9+/10- is displayed

**Comment by scd** [comment] 2018-05-14 03:29
The root cause has been fixed, but it looks like the displayed grade is cached in the route record and has to be updated.

Fixed in this instance but will still be broken in other instances.

**Closed by scd** 2018-05-14 03:29 UTC
