### ISSUE TITLE
Translations: can't find key

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2391] opened 2016-09-18 14:35 UTC
I can't find this key for the red button anmyore, displays the text twice

<img width="806" alt="screen shot 2016-09-18 at 23 34 10" src="https://cloud.githubusercontent.com/assets/19162952/18616527/83f271b4-7df8-11e6-9cd6-c570cab4ad56.png">

**Comment by nclementel** [comment] 2016-10-04 14:08
_template.account-settings.restore_ 

The issue is not in the translation: it is repeated also in English.

**Comment by scd** [comment] 2016-11-08 06:44
fixed on simon's dev

**Closed by scd** 2016-11-08 06:44 UTC
Labels: Feature: Translations
