### ISSUE TITLE
"#" href link for discussion

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2917] opened 2017-09-19 11:08 UTC
**What happened?**

Not sure if it was always there and never noticed or if it is something new.

![screen shot 2017-09-19 at 13 01 51](https://user-images.githubusercontent.com/19304867/30589445-c215470c-9d3a-11e7-8b5f-19179205a399.png)

**What you expected:**

Can't figure out what it is for and where it is supposed to point.

**Comment by brendanheywood** [comment] 2017-09-19 11:30
I'm going to close this as essentially a duplicate of https://github.com/theCrag/website/issues/2905

This enables you to deep link directly to any comment

**Closed by brendanheywood** 2017-09-19 11:30 UTC
