### ISSUE TITLE
questionable Grade scale alignment french - UIAA

### ISSUE THREAD

**Issue by Mdemaillard** [theCrag/website#3686] opened 2020-05-25 15:32 UTC
**What happened?**
from user feedback as per discussion:
https://www.thecrag.com/discussion/3320848095/personal-grade-for-ascent-differs-from-route-grading#m3321251055

the conversion french - UIAA is put under question
https://www.thecrag.com/en/article/grades

**What you expected:**

* [x] provide source(s) to look into (Yannick / niklast)
* [x] check if graph under https://www.thecrag.com/en/article/grades is up-to-date as per system values (i think it is dynamically generated, but to double check)
* [ ] concensus on grade system conversion (as far as possible)

lets roll from there

**Comment by Mdemaillard** [comment] 2020-05-25 15:44
as a first observation, thecrag chart is fully in line with the wikipedia english for the 2 system in question
https://en.wikipedia.org/wiki/Grade_(climbing)

**Comment by Mdemaillard** [comment] 2020-05-25 17:47
From Ulf
Yannick Froese thanks for your comments. I'm afraid guidebooks or grade converters are often simplifying the conversion problem. theCrag is using a fine graded internal grading system with over 500 grades to ensure the conversions are in line with the many grading systems out there. Distribution curves ensure that overlaps are handled correctly and all the subtelities of grading conversion like non-linear grades, changes in the width of grades within the same grading system, etc. are covered. While we don't provide any further detail to this to the public other than in our grde pages a good reference is this article by the IRCRA: https://www.ircra.rocks/single-post/2016/09/12/Reporting-Grades-in-Climbing-Research

If you see anything not in line with this, just let us know

**Comment by lordyavin** [comment] 2020-05-27 07:10
Duplicate of #3320

**Comment by rouletout** [comment] 2021-01-15 09:47
This is in line with accepted conversion, closing

**Closed by rouletout** 2021-01-15 09:47 UTC
Labels: 7: Idea for discussion, Feature: Grades
