### ISSUE TITLE
Getting notifications for areas I haven't climbed at?

### ISSUE THREAD

**Issue by goshenw** [theCrag/website#3187] opened 2018-05-28 00:16 UTC
Seems that something has just changed that pushes notifications about discussions in areas that I have never been to or climbed at.

I'm sure it's on your to-do list (and not directly related to this bug); but it would be great to have control over which areas to receive discussion notifications about.  Just a simple checkbox to either a whole region (eg Blue Mountains) or perhaps I'd like to get notifications about a particular area I'm fond of (eg Pierces Pass).   It could default to being 'on' to areas you've climbed at like it is currently; but a way to turn it off would be greatly appreciated I'm sure!   :-)

**Comment by brendanheywood** [comment] 2018-05-28 00:44
hi @goshenw I'll close this as a dup of this https://github.com/theCrag/website/issues/1449

Yes this is something we just didn't get right and we will work to not only make it obvious why you are subscribed to something but also make it easy to change it on the spot, and also change the settings for what thing you are auto subscribed to.

**Closed** 2018-05-28 00:46 UTC

**Comment by lordyavin** [comment] 2018-05-28 06:30
Duplicate of #1449
