### ISSUE TITLE
target routes in activity

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3649] opened 2020-04-19 00:24 UTC
**What happened?**

When you tick a route as a target, activity indicates "logged an ascent from the past".
<img width="608" alt="Capture d’écran 2020-04-19 à 07 50 33" src="https://user-images.githubusercontent.com/34114303/79674553-c8531180-8216-11ea-963d-836f96f52800.png">

**What you expected:**

- activity indicates "targets an ascent". 

- target routes doesn't count in routes ascents.

**Comment by scd** [comment] 2020-04-19 00:35
We are not going to fix this directly. Rather we are going to remove target ascents and replace them with  personal route lists so you can set you multiple aspirational goals.

**Comment by Mdemaillard** [comment] 2020-04-19 08:12
Duplicate of #2836

**Comment by rouletout** [comment] 2021-01-15 09:33
Closing thgis as this will be replaced by "wishlist" rather sooner than later

**Closed by rouletout** 2021-01-15 09:33 UTC
Labels: 5: Polishing, 9: Won't Fix, Area: Logbooks Ticking & tick lists
