### ISSUE TITLE
In-between grades for the Norwegian grading system

### ISSUE THREAD

**Issue by scd** [theCrag/website#1056] opened 2013-04-09 01:15 UTC
There are 4 official in-between grades 7+/8-, 8/8+, 9-/9 and 9/9+ which are locally recognized as grades in their own right.

See the grade pulldown list in the following club website: https://www.bergen-klatreklubb.no/forere/cragdatabase/grad.php

This might be a little difficult to implement, as I have to look into grade parsing with the '/'.

**Comment by birgander2** [comment] 2015-01-13 14:53
Also in the UIAA system quite often slash grades are used, and normally they denote a grade in between and not a range.

**Comment by lordyavin** [comment] 2018-12-05 11:49
To be closed?  Is connected to  #1951?

**Comment by Mdemaillard** [comment] 2020-05-27 19:58
The route input is possible (as for UIAA) using the free text that recognizes slashgrades. (#1951, closed)
I believe the remaining point is allowing to tick as such (#3320 open)
Can we close this one as dupe of #3320 or do we want to keep the possible Norway specific official in-between grades ?

**Closed** 2020-06-04 17:07 UTC
Labels: 5: Enhancement, Feature: Grades
