### ISSUE TITLE
Displayed width of topos too small

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3574] opened 2020-01-05 13:19 UTC
The display of topos which are not in the perfect aspect ration is imho not ideal / not wide enough. Many cameras take images in 3:2 or even 4:3 aspect (and not 16:9 or whatever theCrag expects to use the whole horizontal space). One of many examples can be found [here](https://www.thecrag.com/climbing/portugal/reguengo-do-fetal/area/2661644619). The topo would appear much better/bigger if scaled to use all of the available horizontal space. For portrait mode topos this might not be the way to go, but for everything up to quadratic it would really be an improvement to stretch everything in the way discribed.

**Comment by Mdemaillard** [comment] 2020-03-29 20:50
duplicate of #3415. Closing this and merging the info

**Closed by Mdemaillard** 2020-03-29 20:50 UTC
Labels: 5: Enhancement, Area: Display/Layout, Feature: Phototopo
