### ISSUE TITLE
Grade oppinion on ascent logging

### ISSUE THREAD

**Issue by kk56k** [theCrag/website#3420] opened 2019-05-05 19:10 UTC
The feature of adding personal grading to routes is relatively rarely used, which is not surprising as it requires the rights and the will to edit a route. 
I would propose to add personal grading query to the logging screen similar to the quality rating scale.
This could for example be a choice box with 
- sandbagged (route is too hard for the grade, upgrade proposed)
- hard for the grade (route is hard but not too hard for the grade)
- okay for the grade (grade matches route)
- easy for the grade (route is easy but not too easy for the grade)
- overrated (route is too easy for the grade, downgrade proposed)
or something like that. 

The result of these selections could then be displayed similar to the quality rating. This way, a nice overview of the communities grade opinion could be generated for each route, which then in a next step could be takes as reference to up- or downgrade routes.

[proposed Labels] 
["5: Enhancement", "7: Idea for discussion", "Feature: Grades", "Area: Logbooks Ticking & tick lists" ]

**Comment by lordyavin** [comment] 2019-05-05 20:29
Hey @kk56k, thanks for the idea. Are you aware of the possibility to log an ascent with a user defined grade? I think that feature may match some points of your proposal.

**Comment by kk56k** [comment] 2019-05-05 21:01
Hey @lordyavin,
as far as I know, the user defined grade only affects your log, but does not provide any information for other climbers (if they don't scroll through the ascent history of the route and do their own statistics). 
What you can do, is using the comments box for keywords, but this feature neither is regularly used to provide information about the grade nor is there some established standard code.

**Comment by lordyavin** [comment] 2019-05-06 08:59
Did you read issue #689 and the linked discussions? I have the impression your issue could be a duplicate of it. Please check it out.

**Comment by kk56k** [comment] 2019-05-06 10:14
I just read the first comments and even though the suggestions go much further than mine, it appears to be pretty similar. Shame on me I did not find it when I searched for similar issues. I guess, this issue can be closed/deleted then.

**Comment by lordyavin** [comment] 2019-05-06 10:18
Duplicate of #689

**Closed by lordyavin** 2019-05-06 10:18 UTC
Labels: Area: Logbooks Ticking & tick lists

**Comment by lordyavin** [comment] 2019-05-06 10:29
please add a comment to #689
