### ISSUE TITLE
Images too small in forum discussions

### ISSUE THREAD

**Issue by scd** [theCrag/website#3007] opened 2018-01-15 08:16 UTC
**What happened?**

Images too small in forum discussions 

![screenshot from 2018-01-15 19-14-59](https://user-images.githubusercontent.com/373058/34932794-7c2549e0-fa28-11e7-9bde-6b437b33923b.png)

**What you expected:**

100% width.

**Comment by brendanheywood** [comment] 2018-01-15 10:39
I think this is effectively mostly a duplicate of https://github.com/theCrag/website/issues/2872

We should probably hand this in 2 ways:

* [ ] different markdown contexts should be able to pass in extra params that affect the cards, eg in route context we want images max 160 wide, in beta double that in forums larger again
* [ ] regardless of the max size above, we fill out the image srcset which the whole suite of sizes so you only get what you need on each device #2872

**Comment by scd** [comment] 2018-01-16 06:04
I have partially done this. I am passing a context variable into the Markdown function which gives us the flexibility of triggering different sizes. So far it is default (160 width) and forum width of 400.

I have defined a responsiveWidths variable in the linkPhoto function which will build a srcset, however it does not work in the markdown functions because we of another issue with markdown which will convert urls in srcset into html links. We know the fix for this issue, but it needs a bit of a refactor so I will not implement srcset just yet.

Anyway the forum post now looks a lot better with larger images:

https://www.thecrag.com/discussion/1636723359/release-58

**Closed** 2018-01-22 00:07 UTC
