### ISSUE TITLE
PDF-Topos: Wrong route grade / no info shown for multi-pitch routes

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3330] opened 2019-01-02 15:21 UTC
**What happened?**

For example in this area: https://www.thecrag.com/climbing/mexico/el-salto/area/1667175816 this route (https://www.thecrag.com/climbing/mexico/el-salto/route/581524854) is registered as a 4-pitch route. See screenshot:
<img width="815" alt="screen shot 2019-01-02 at 09 19 02" src="https://user-images.githubusercontent.com/19162952/50598154-7e061f80-0e6f-11e9-8f90-319a3938f266.png">

The PDF Topo does not show the number of pitches and their respective grades. This is making you believe that the first pitch is actually harder than it is and not providing the right info. See screenshot:

<img width="895" alt="screen shot 2019-01-02 at 09 20 52" src="https://user-images.githubusercontent.com/19162952/50598229-c0c7f780-0e6f-11e9-8f4e-e5066c9c4ffd.png">

**What you expected:**

Correct display of number of pitches and their respective grades on the PDF Topo

**Comment by brendanheywood** [comment] 2019-01-03 01:21
Closing as duplicate of https://github.com/theCrag/website/issues/2995

**Closed by brendanheywood** 2019-01-03 01:21 UTC
Labels: 2: Bug fix
