### ISSUE TITLE
Index Tree UI discussion

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2544] opened 2017-01-22 14:37 UTC
Does anyone else feel that the dropdowns on the Index Tree are in the wrong places? 
I feel that the one to the right of a region should have the daughters of that region, and the left the siblings. 

As it is the right doesn't exist at the current level, the left is the daughters, and you have to go another one to the left to get to siblings. 

It seems more intuitive for me at least to restructure them.

**Comment by brendanheywood** [comment] 2017-01-23 03:13
Maybe, there are plenty of examples in the wild both ways. The issue with doing using the arrow on the right side is that if you are the last / current node, then there is no arrow. Maybe the way around that is that the whole node item when hovers shows it's children rather than just the arrow. It's not high on my list thought but I'll leave open for other to vote on

**Comment by Mdemaillard** [comment] 2020-03-11 19:06
Is that the navigation menu / tree on the left ? if thats the case, ready for closure
![image](https://user-images.githubusercontent.com/60388146/76453784-24d33d80-63dc-11ea-8f71-1dd676541175.png)

**Comment by DaneEvans** [comment] 2020-03-16 00:24
No, the one at the top. 

![image](https://user-images.githubusercontent.com/22091505/76713988-9b739080-6778-11ea-81f8-6ca8136fa086.png)

**Comment by Mdemaillard** [comment] 2020-03-16 05:32
Ahh the breadcrumb. I see. +1 from me.

From desktop perspective only: a hover on a node should show its daughter on dropdown, consistent everywhere, because nodes are easier to target than arrows.

BUT for mobile hover is bad (and precise targeting as well, doh).

So i would say: 1 click on a node opens the drop down, a second click targets the node itself. Forget the arrows.

**Comment by Mdemaillard** [comment] 2020-03-16 13:30
Duplicate of #2965, which has more valueadd. Merging into it and closing here.

**Closed by Mdemaillard** 2020-03-16 13:30 UTC
Labels: 5: Polishing, Area: Navigation
