### ISSUE TITLE
Filter world-map

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#2598] opened 2017-02-13 19:47 UTC
Hey guys,

I just browsed the overview map where you have round markers at the location where crags are with the amount of routes.

I thought it would be great if it would be possible to filter different route types, for example only boulders, only sport climbs or only alpine stuff. Would be also great to be able to combine the filters.

For example if someone is only interested in bouldering, he would be a lot faster it he could hide everything else and have a nice overview of the stuff he really wants to know.

**Comment by Drazhar** [comment] 2017-02-13 19:54
Or as another option or in addition, the circles could be colored like a pie-chart to show the percentage of boulders/sport/trad. The same as the bar at the top of each sector/crag/... which already show how much of what type is present.

**Comment by DaneEvans** [comment] 2017-02-14 00:33
I'd like to see this too, 

The pie chart might hide things with say a fair sport crag (20 routes) in a large bouldering area (200+), it might be hard to spot that there are any routes there. 

Maybe have a separate round marker for each style, or the filters.

**Comment by brendanheywood** [comment] 2017-02-14 01:16
Thanks guys I'm going to close this, it's a duplicate of #985 (and sorta also #1610) can you please read those and comment there instead (and please try and search for duplicates first, but don't stress too much I will cross link or close as needed)

**Closed by brendanheywood** 2017-02-14 01:16 UTC
