### ISSUE TITLE
Convert grades on mouseover as tooltip

### ISSUE THREAD

**Issue by Basti-muc** [theCrag/website#2775] opened 2017-05-31 12:35 UTC
I think it makes sense to show the original grade of a route (and not automatically convert it to the preferred grading system).
But, as the system can automatically convert grades to a different system, it would be cool to have a tooltip showing the corresponding grade in the preferred grading system when hovering over a foreign grade.

E.g. I'm not familiar with the australian grading system, so I'd love to see a tooltip showing the equivalent grade in FR or UIAA system (even though the color code is cool and gives a rough idea).

**Comment by birgander2** [comment] 2017-05-31 14:02
And it would be good to show the current grading system used. It is not always so obvious: Many people, for example, change correct FB grades (in FR context) to FB context, because they think that something is wrong. A tooltip showing the grading system in both index listing and route details would help here. Currently something like "set using the FR context" is shown - that's ok for theCrag pros, but not understandable for the average user.

**Comment by Basti-muc** [comment] 2017-05-31 14:11
@birgander2 I think you requested that in #2245? ;-)

**Comment by brendanheywood** [comment] 2017-11-01 23:59
Yeah closing this as a duplicate of https://github.com/theCrag/website/issues/2245

**Closed by brendanheywood** 2017-11-01 23:59 UTC
