### ISSUE TITLE
Free solo onsight tick type

### ISSUE THREAD

**Issue by jaka4eva** [theCrag/website#2882] opened 2017-08-12 23:54 UTC
**What happened?**
Could you by any chance add a new tick type for 'free solo onsight'?

(please also provide urls and screen shots)

**What you expected:**

**Comment by brendanheywood** [comment] 2017-08-13 01:33
thanks @jaka4eva I am closing this as a duplicate of https://github.com/theCrag/website/issues/2835 and have added your vote to that issue

**Closed by brendanheywood** 2017-08-13 01:33 UTC
