### ISSUE TITLE
Selections in name input fields hard/impossible to remove on mobile

### ISSUE THREAD

**Issue by dnnr** [theCrag/website#3128] opened 2018-03-23 15:33 UTC
On mobile, when inputting or selecting accounts for name input fields (e.g., "Who with"), existing entries cannot always be removed by pressing the <kbd>x</kbd>.

It seems to depend on the context: It works in the search mask but doesn't work in _Log ascent_. The button is hard to hit in any case, but when it doesn't work, even zooming in all the way doesn't help.

I tried this on Android, using Chrome Beta 66.0.3359.30. It's been like this for years, so it's probably not related to any recent change.

Even though this seems like a tiny issue, it basically makes logging on mobile impossible for me, since I can't fix a single mistake. The name input field is especially unforgiving, because once focused, it _will_ add an entry to the list (the first one or the selected one) when unfocusing it, even if you don't want it to. This might be a bug in itself, not sure. 

For reference, it looks like this for me:
![goooyjkhv-iqprvi](https://user-images.githubusercontent.com/2630359/37837981-014df76c-2eb7-11e8-9ff2-3d1f3694b0d0.png)

**Comment by scd** [comment] 2018-03-24 01:32
I have just tested my two browsers (Chrome 64.0.3282.137 being one of them) on my Andriod and it works fine.

Can anyone else who reads this test their mobile and report the result in this issue.

**Comment by brendanheywood** [comment] 2018-03-24 09:50
There is two distinct issues, the second one about focusing is everywhere, desktop / mobile, and yes I consider that a bug and it has caught me in the past too. At least fixing that should reduce the incidence of the other bug.

Fixing it is going to be hard unless I can reproduce it. If you are zooming right in and it still doesn't work then it's not just a target size issue (although I can and will also make it larger too)

**Comment by DaneEvans** [comment] 2018-03-24 10:40
It’s hard to hit on Safari (iPhone se)
But I’ve not seen it become impossible. 

Also not a fan of the fact that it insist on adding someone

**Comment by brendanheywood** [comment] 2018-03-26 06:10
Ok so I traced the introduction of the second bug to this:

https://github.com/theCrag/website/issues/1799#issuecomment-68955646

This is subtle, where someone has just typed in a name which doesn't match anything we want it to select on blur, but where you have typed in something that does match, and hovered or moved the selection we don't want selectonblur, we want an explicit choice. Hard to explain with words but I think I've found the best combination to solve both at the same time.

Also as a bonus I've tweaked the close button so it's large and vector:
![image](https://user-images.githubusercontent.com/187449/37889373-b7612eae-3117-11e8-9d8d-5dc8a26942ab.png)

@dnnr can you please test this on my test server here (all data here will be removed, login is the same)

https://brendan.thecrag.com/climbing/australia/ebor-gorge/area/12094657

If it still fails there, can you see if typing 'backspace' on the keyboard remove the previous entry as a workaround?

**Comment by dnnr** [comment] 2018-03-26 14:48
> @dnnr can you please test this on my test server here

So, I have mixed results. First of all, it looks like this (the vertical bar seems unintended):
![frrb4sdvynjqwl1z](https://user-images.githubusercontent.com/2630359/37912324-96acb958-3112-11e8-8d42-7bd7747f9dae.png)
When adding a real user, it looks exactly like in your screenshot.

The issue with adding names on blur seems solved to me. :thumbsup:

Tapping the <kbd>x</kbd> works sometimes, but it is still very hard to hit. Occasionally, it seems to not work at all anymore until I refresh the page. Zooming in never seems to help at all; it's always a matter of tapping dozens of times to eventually hit the right spot.

In about half of my attempts, focusing the field didn't work correctly anymore after adding some names. The dropdown might still appear, but the cursor and on-screen keyboard doesn't.

Pressing backspace as a workaround doesn't work (nothing happens) in either mobile Chrome or Firefox for Android. It does work on desktop Firefox, though (two backspace presses are needed)!

For what it's worth, apart from the backspaces and the strange vertical bar, none of the issues described above occur in Firefox for Android.

**Comment by brendanheywood** [comment] 2018-03-27 00:05
the vertical bar is intended, I've fixed this so it's good for both 'free text' and @ items:

![image](https://user-images.githubusercontent.com/187449/37938584-5dd8b4e0-31aa-11e8-96a7-cef1f6c921ee.png)

Before only the 'x' was clickable but now the whole square to the left of the grey line is. But I suspect that the issue isn't the size of the clickable region at all, I think something else is going on like some JS failing elsewhere and so all js is busted (ie the need to refresh the page). Are you able to open a js console and see if there are any errors?

**Comment by dnnr** [comment] 2018-04-02 11:37
> Are you able to open a js console and see if there are any errors?

Okay, so I managed to do this now. There are no messages showing up in the JS console, apart from a failed GET request to GA (it's blocked).

Interestingly, when "tapping" the <kbd>x</kbd> using the remote control on desktop, it works just fine. I'm beginning to suspect some device-specific issue here. Maybe we should first have somebody else confirm my observations on their device.

**Comment by brendanheywood** [comment] 2018-04-03 01:45
@dnnr we are starting a release today which will include the couple of partial fixes for this. I'm tempted to close this issue with the couple of changes I've made. Simon couldn't reproduce it either on his android + chrome. If you can shed any more light on it then please make a new issue with the details

**Closed by brendanheywood** 2018-04-03 01:45 UTC
Labels: 2: Bug fix, 3: Mostly done
