### ISSUE TITLE
Feature: offer to log ascent you've been tagged in

### ISSUE THREAD

**Issue by davich** [theCrag/website#3581] opened 2020-01-15 07:24 UTC
Feature request:

When my partner logs me in an ascent,
the site should offer to add it to my profile.

It seems that even though I've been tagged in a climb by my partner, I have to log the ascent separately. It should offer to do this for me.

**Comment by lordyavin** [comment] 2020-01-15 08:31
I don't like the idea that the platform automatically adds ascents to my logbook. Actually you already have the option to log the ascent from the stream event context menu.

**Comment by rouletout** [comment] 2022-01-18 14:11
+1 From supporter: Let me bulk log ascents other climbers have logged. For example, if my climbing partner has logged their climbs, let me log all of them at once too instead of logging each one individually.

**Comment by scd** [comment] 2022-09-18 23:12
You can do this from streams events.

<img width="726" alt="Screen Shot 2022-09-19 at 9 04 49 am" src="https://user-images.githubusercontent.com/373058/190932031-33ba1970-974b-486a-9e87-440479e98b45.png">

Move over we have added a feature for stream a stream ticking event where if you have logged who with then the stream events of the person you climbed with is shown below your stream event (See 'Related') in the screen shot above. Here is the link for the above screen shot.

https://www.thecrag.com/event/6579341517

If you share your stream event with people you climbed with then they can easily cross tick. I want to improve this so there is a virtual tick list you can easily tick from.

I believe this means that the issue is resolved, but there may be further work for improving the stream event UI for bulk ticking, but this would be a different issue if it is wanted.

**Comment by rouletout** [comment] 2022-09-19 17:12
Closing

**Closed by rouletout** 2022-09-19 17:12 UTC
Labels: 7: Idea for discussion, Area: Logbooks Ticking & tick lists
