### ISSUE TITLE
404 on URL from stream

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3254] opened 2018-08-29 15:26 UTC
**What happened?**

I clicked on a [link](https://www.thecrag.com/climbing/italy/finale-ligure/dancing-dalle/area/1965467109) in a stream event and got a 404 error.

![grafik](https://user-images.githubusercontent.com/1528540/44797882-893efb00-abb0-11e8-9dc7-07354c016843.png)

**What you expected:**

Working URLs :wink:

**Comment by Mdemaillard** [comment] 2020-03-17 07:18
link above is working.
assumed duplicate of #3204

**Closed by Mdemaillard** 2020-03-17 07:18 UTC
Labels: 2: Bug fix, Area: Streams / feeds
