### ISSUE TITLE
Enable a crag coordinator to choose a web cover image

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2716] opened 2017-04-20 14:18 UTC
This is a more focused actionable list of things to get the final UI complete for cover images split off from #974

* [ ] we want a crag coordinator to be able to choose a cover image for a crag. They would go to any picture inside that crag (doesn't need to be their photo), they would see a new button, similar to facebook, which says 'Make this the crag cover image'.
There is two additional bits of info we need
  * [ ] we need the focus point of the image. Right now thumbor can only handle left / middle / right, vs top / middle / bottom so we would just give them a matrix of the 9 focus choices. Internally store this as a pair of percentages, 0% 50% 100%, later when we upgrade thumbor we can set a focal point anywhere but the data model should not need to change.
  * [ ] we may also need to know which crag the web cover should be attached to. I'm thinking that we should probably not do any filtering or validation of the node area type so you can upload a web cover to a boulder or field or gym or whatever. So just present a list of all nodes from the node the photo is attached to up to the TLC level.
* [ ] the template current has some data for a webcover, it's all just old junk just rip it out completely and replace with it only with the explicit cover above, we don't want any automatic web covers or avatars at all
* [ ] the fake static data I am currently using has only the bare minimum to show the photo. When you add this to the template data use the proper atoms so we get the full photo metadata including the photographer object etc
* [ ] create a stream event for setting a cover. Not too fussed on the karma level, it doesn't need to be lots of karma, maybe 20? You should only ever get it once even if you replace it

In the admin page for a crag there are 2 fields:

![image](https://cloud.githubusercontent.com/assets/187449/25234735/578ebc14-2626-11e7-89c9-aa141d961bb7.png)

* [ ] We can probably reuse the existing data model, I'm not sure, but remove the fields from the gui completely and any validation that's done here (it's never been usable)
* [ ] we need to be able to remove a web cover

**Comment by brendanheywood** [comment] 2017-04-20 14:20
@rouletout are you happy with this workflow?

**Comment by rouletout** [comment] 2017-04-20 14:25
Sounds good to me - we assume coordinators will make sure the quality is good enough which is fine

**Comment by brendanheywood** [comment] 2017-04-20 14:28
Yes, but even if they choose a real crappy image thumbor will still scale it as needed so it will all still work regardless.

**Comment by scd** [comment] 2017-04-20 22:50
I will get something functional on the photo page without worrying to much how the UI looks. I don't think it is heaps of work.

**Comment by brendanheywood** [comment] 2017-04-20 23:02
If this is all api and just a chunk of js on the photo page then thats probably the best. Something like

/api/node/id/12345/cover

``
{
  photoid: 234567,
  focusx: .1,
  focusy: .5,
}
```

If you call the same endpoint with null photoid then it removes it

**Comment by scd** [comment] 2017-04-20 23:05
Just doing it api is good idea. I will use our standard crag update api so that it minimises the coding.

**Comment by scd** [comment] 2017-04-20 23:45
@brendanheywood are you currently using the focus point. The focus point fields will need to be added to the database.

**Comment by brendanheywood** [comment] 2017-04-21 00:12
Yes I am using the focus point, if you look at the hard coded cover paths many of them have /top/ or /bottom/ in the thumbor url. At the moment our version of thumbor can only use keywords but the latest can use a x,y focal point and I really wish I had it now for some of the images I've setup for @rouletout. 

eg Datca

https://www.thecrag.com/climbing/turkey/datca

https://www.thecrag.com/photo/1034342205

https://static.thecrag.com/img/1200x400/bottom/a1/8c/a18c00a7e993cd2877c1fbc375fa28b607923afd

But even this cropping isn't perfect I actually want to crop it slightly higher so there is just a touch of greenery and more of the cave visible, so like y = 75% instead of 100%. The filter I want is focal() and was introduced in 5 Feb 2016:

http://thumbor.readthedocs.io/en/latest/focal.html

The moment this filter is available when we upgrade thumbor I want to take advantage of it so I want the data model sorted now. I can see two versions of this:

1) we go live shortly with the ability to choose a x/y as a percentage, but we round these out to 0% 50% and 100% as we construct the thumbor url, this means when we upgrade thumbor we just remove the rounding and we get better images right away for all the existing covers.

2) we go live and do the rounding in the UI in the photo page so we only ever store 0, .5 or 1 in the db, but after we upgrade thumbor we can then go back and re-focus any images we want.

I'm not fussed either way, 1) is probably a less confusing UI in the interim, but either way we need the data model in place.

**Comment by scd** [comment] 2017-04-21 00:34
I will put the data model in based on there being a number input between 0-1 or NULL. The data model itself will not care about the UI implementation in this case,

Just getting my head around the thumbor settings. A focal point of 1 or 0 would be on the edge, which means the image is aligned to that edge. Is this the correct interpretation?

**Comment by brendanheywood** [comment] 2017-04-21 01:05
Yes at the moment because we only have the 3x3 = 9 focal points, then it's probably more useful to think of '/left/bottom/' and being equivalent to focalx = .1666 and focaly = .83333 rather than x = 0 and y = 1. Even if the focal point is hard up against an edge the bounding box for the resulting crop will get pushed out towards the center so that it will always include that focal point but still retain the correct aspect ratio. At least for the web covers which are 3x1 aspect ratio the x focus point in most cases will be ignored unless you have a super wide panoramic shot, but I want to use this for lots of other things not just the 3x1 covers (eg facebook og:images are different)

Lets say we have this image and the focal point in on Monique, which is probably around x = 80% and y = 45%

![image](https://cloud.githubusercontent.com/assets/187449/25258191/07013b40-2681-11e7-8061-1bc20b9dd42d.png)

Then I can pick an aspect ratio and get a good crop which will include her, eg:
* 8x1 pano in red
* 1x1 square in purple
* 1x4 vertical pano in green

So essentially find the largest cropping which is the desired aspect ratio and includes the focal point and doesn't go over any edges.

![image](https://cloud.githubusercontent.com/assets/187449/25258257/661c089e-2681-11e7-8a87-1195114d8f01.png)

**Comment by brendanheywood** [comment] 2017-04-21 01:12
And what they would each look like:

![image](https://cloud.githubusercontent.com/assets/187449/25258461/f365c2c0-2682-11e7-9bce-b9a3fa6b1603.png)

![image](https://cloud.githubusercontent.com/assets/187449/25258477/03127222-2683-11e7-9fef-968e0b1ef521.png)  ``` . . . . . . . .  ```    ![image](https://cloud.githubusercontent.com/assets/187449/25258491/22f18254-2683-11e7-8f8a-f194e4859e1d.png)

**Comment by brendanheywood** [comment] 2017-04-21 13:53
Actually I'm pretty excited to discover that with a little maths we can use the existing version of thumbor and get everything. It just means we have to do the calc ourselves in the template instead of thumbor doing it for us, as long we have access to the original image dimensions. So I'm absolutely full stream ahead with doing this properly now.

Eg in that photo above the original dimensions are 2000x1300, if we want to crop centered at 80% and 45% and with an aspect ratio of 3x1, then we end up with a crop box of 2000x666 centered at x = 2000 * .8 = 1600, y = 1300 * .45 = 585, which ends up with x = 0-2000 and y = 252-918 after we push back from the edges:

https://static.thecrag.com/img/0x252:2000x918/fit-in/600x200/7e/90/7e902dd8845e9452aa0fb2e0cb4e8e70765a932d
![image](https://cloud.githubusercontent.com/assets/187449/25279897/595c282c-26eb-11e7-8daf-99e8a5e767a2.png)

Same logic applied to a square:
https://static.thecrag.com/img/700x0:2000x1300/fit-in/300x300/7e/90/7e902dd8845e9452aa0fb2e0cb4e8e70765a932d
![image](https://cloud.githubusercontent.com/assets/187449/25279976/a8248cec-26eb-11e7-8b32-0cc62e7a99a9.png)

**Comment by scd** [comment] 2017-04-24 07:51
I think we want the focus fields to be associated with the photo, not the node. We should be able to assign the focus point of any photo.

**Comment by scd** [comment] 2017-04-24 08:28
I have still coming to grips with this algorithm. I get the feeling that we should be assigning a bounded box (ie top left and bottom right) as the focus area rather then a single focal point. 

The reason is that if we want a whole person in the image then we want to make sure the bounded box does not go outside the edges.

A bounded box for the focal area would also put bounds on the aspect ratio that could be displayed. In your example above a 16:1 aspect ration would cut the climber in half. Having a bounded box will tell the system that this has happened. Turning this around, we will know which images are suitable for a 8:1 panorama.

The reason why I want to bring this up now is because I am going to add extra fields to the photo. If we are doing all this maths then I propose we create the following fields 

 * FocusTop: the y value for the top left point
 * Focus Left: the x value for the top left point
 * FocusBottom: the y value for the bottom right point
 * FocusRight: the x value for the bottom right point

We just store them as absolute points based on the full image dimensions.

@brendanheywood, does this make sense or have I got something wrong?

**Comment by brendanheywood** [comment] 2017-04-24 10:00
I had that same though and ummed and ahed about commenting. I agree it would be good for any photo to be able to have a focus point, but I can also imagine a single pano photo of a large cliff also being used for two different cover photos with different focus points, but an edge case I'm happy to ignore. I'm not too fussed which way we go

Re using a rect instead of a point, I'm totally cool with that and I prefer it. It also gives us the additional flexibility to ask for the smallest image with a certain aspect ratio that contains the focus area rather than the largest, which is desirable in some situations eg very small res pics. This gets us pretty well to the utopia of dynamic "art direction" with our images. 

Thinking more broadly, we have other issues sitting in the backlog like being able to tag people in photos (https://github.com/theCrag/website/issues/854). If you are concerned about getting the data model right now, should we consider the idea of a photo having many 'focal area's, and each focal area has a bounding box, a chunk of markdown and 'type'. Then when we are linking a webcover, we are not linking directly to a 'photo' but instead to a focal area with type 'webcover'. This solves the edge case above of having two web covers with the same photo, and also means we can tag multiple people using an @ mention in the markdown chunk with type 'person'. This is all internal data model, we may not expose it directly in the gui like this. I'm trying to think of any other use cases for the same data model, we could also link to areas and routes the same way.

And it could be used for general marking up of a photo like highlighting a broken hold in a forum post but it doesn't warrant being a topo. Pretty similar to flickrs comment on photo feature, see an example here, hover over the image

https://www.flickr.com/photos/brendan_heywood/8035453787/in/dateposted-public/

**Comment by scd** [comment] 2017-04-24 11:28
+1 

I am creating a PhotoFocus table

**Comment by scd** [comment] 2017-04-25 08:09
@brendan, if you want to start playing with the admin UI I have got something very simple working. Note that there is some legacy logic in how our system deals with web covers and probably some bugs, so I have not got the webcover properly working on the area page json.

At this stage I just wanted to focus on the admin UI, and give you a go at making it nice. Go to a photo page and you should see something like.

![tc-webcover-admin](https://cloud.githubusercontent.com/assets/373058/25374754/f780846e-29e1-11e7-87ae-1ca05569a038.png)

We need to replace the top,bottom,left & right fields with mouse clicks in a photo. Note that the top, bottom, left and right fields should be input relative to the width and height fields. So if you want them as a percentage you make width and height both 100. The width and height defaults to the original width and hieght in this case, but I imagine it will be a lot easier doing the mouse clicks on a smaller image.

**Comment by brendanheywood** [comment] 2017-04-26 12:17
I have since also softened a bit towards fall back images. It does make sense that until an image has been chosen then we still do as best we can in the mean time. Otherwise pages like the favorites list will look quite odd (see https://github.com/theCrag/website/issues/2736)

Have you already backed that out? Either way I think it's logic needed to be reassessed as it always seemed to show up weird images

**Comment by scd** [comment] 2017-04-26 12:33
> Have you already backed that out?

No. Will wait until you give the UI on the photo page then this will give us both a chance to discuss and work out the best business rules.

**Comment by brendanheywood** [comment] 2017-04-26 12:48
Another thing to throw into the mix, would we want to allow multiple web covers?

eg this page has 3 web covers that rotate every 5 seconds:

https://www.lonelyplanet.com/new-zealand

We would still have a primary one which is used for the static things like pdf + facebook

**Comment by brendanheywood** [comment] 2017-04-26 13:06
* [ ] because an image could have many focal areas / webcovers, the data in the photo page needs to be something like:

```
focusPoints: [
  {
    id: 1234,
    type: 'webcover',
    top:
    left:
    right:
    bottom:
    node: {
      345677,
      ...
    }
],
```

Also what is "canAssignAsWebCover": 1,  - how is this derived?

**Comment by scd** [comment] 2017-05-01 06:10
> Another thing to throw into the mix, would we want to allow multiple web covers?

Sure, why not. This would also mean that I can dump the field associating a photo with the web cover on the node index, which is better because it is at odds with the new structure.

> We would still have a primary one which is used for the static things like pdf + facebook

So the primary would be called 'webcover' and the secondary ones 'webcover-secondary'. We need a way to distinguish primary versus secondary so we may as well use the focus label.

Do we want to make a webcover image available as the web cover for muliple nodes. Note that this is the reverse of having multiple webcovers for one node. If yes then an image can have many webcover focus's

 > focusPoints:

Will do. But this means there is a bit of work in the UI so you can dynamically add a focus. 

> canAssignAsWebCover

The image must be associated with a TLC or descendant of a TLC. This was something you mentioned and makes it easier to choose nodes that an image can be assigned to. I have kept it as a server flag rather then getting the template to make the test.

The business rules currently mean we cannot assign web covers higher than TLC. Is this OK?

Are you waiting on me for this?

**Comment by brendanheywood** [comment] 2017-05-01 07:04
> So the primary would be called 'webcover' and the secondary ones 'webcover-secondary'. We need a way to distinguish primary versus secondary so we may as well use the focus label.

Hmm, I'd say they would all have the same type = 'webcover' and as you said we'd stick something in the label like a priority to determine which is the first we show. For simplicity lets make the api not know or care, so it will just store whatever it gets in the label and dump all the focal points as is. For the first release the templates can just grab the first and use it. 

> Do we want to make a webcover image available as the web cover for muliple nodes. Note that this is the reverse of having multiple webcovers for one node. If yes then an image can have many webcover focus's

Yes, but I'd assumed this was already agreed upon back in comment: https://github.com/theCrag/website/issues/2716#issuecomment-296602311 

Maybe you mean the distinction of using the same 'webcover' focus point as the same thing for multiple nodes, vs using the same photo with perhaps the same or different focal points? If so then no I don't think there is much value in it, I'd go with the simpler version of if people want to reuse the same photo for two webcovers at different crags then they have to draw two focal points. I think it's a fairly safe assumption that they will be focusing on different points anyway, and even if that assumption is false then the work to do it twice is trivial.

So to summarize I see the end result as

* a photo can have 0-many focal points
* each focal point has exactly 1 type + rect bounds + label
* each focal point has 0 or 1 node links
* each node has 0-many links to a specific focal point

Medium term I see the types as being 'webcover', 'comment', 'account'. The data stored in the label is only meaningful in the context of the type. so for a webcover it could just be a number we use at the priority if there are many, for a 'comment' it would be some markdown, and for an account it would be a userid.

> The image must be associated with a TLC or descendant of a TLC.

Requiring the photo to be linked to a node is purely so we can make the selection process simpler. It should not be a hard restriction at the api level. I think as long as the photo has *any* node linked at any level that is the only thing that should matter. When adding a focal point you will only be able to link it to a node that is an ancestor of the photos node, so if it's a region level photo and you want to link it as a country web cover that is a valid use case.

> The business rules currently mean we cannot assign web covers higher than TLC

I definitely want to add web covers to regions and countries. Think of the lonely planet page for NZ (https://www.lonelyplanet.com/new-zealand). As long as the photo is linked to a node inside that region I think that's all that matters (and that the person has the coordinator role at the area / region / country node level).

> Are you waiting on me for this?

The main thing I need is for the api to save and for the data to come out in the area template json. Ideally if it also came out in the photo page json data too so we can get round trip editing in the photo page. The current data in the photo page isn't in the right shape:

```
"webCover": {
  "left": "33",
  "asciiName": "Gara Gorge",
  "name": "Gara Gorge",
  "bottom": "222",
  "right": "333",
  "urlStub": "australia/gara-gorge",
  "top": "22",
  "subType": "Crag",
  "isTLC": 1,
  "id": "11772109",
  "type": "area"
},
```

I would expect an array of them, and for the node to be a nested object maybe like:

```
"focalAreas": [
 {
  "type": "webcover",
  "label": "",
  "left": "33",
  "bottom": "222",
  "right": "333",
  "top": "22",
  "node": {
    "id": "11772109",
    "type": "area"
    "subType": "Crag",
    "isTLC": 1,
    "urlStub": "australia/gara-gorge",
    "asciiName": "Gara Gorge",
    "name": "Gara Gorge",
  }
 }
 ]
,
```

**Comment by scd** [comment] 2017-05-01 07:33
> Maybe you mean the distinction of using the same 'webcover' focus point as the same thing for multiple nodes, vs using the same photo with perhaps the same or different focal points? 

From a data model point of view the simplest thing is to have same photo with different focus points for each node. This means we can have the node stored in the focus table rather then create another table. For example if you have one photo used as a web cover for both Arapiles and Victoria then you will have to define two focus points.

**Comment by brendanheywood** [comment] 2017-05-01 10:35
> From a data model point of view the simplest thing is to have same photo with different focus points for each node.

Yup perfect we are on the same page

**Comment by scd** [comment] 2017-05-06 03:42
I have got the api working for the photo page. The template has a foci variable, which is a list of focus items. Each focus item can be any focus type.

```
"foci": [
    {
        "top": "1",
        "id": "587110108",
        "bottom": "2",
        "node": {
            "id": "11738035",
            "asciiName": "Victoria",
            "subType": "Region",
            "name": "Victoria",
            "type": "area",
            "urlStub": "australia/victoria"
        },
        "type": "webcover",
        "right": "7",
        "left": "4"
    }
],
```

The UI is really rudimentary to show that create/update/delete works. All of these are a single endpoint. If you include a focus id in the data then it updates, if you also don't have values for any of the left, right, top and bottom parameters then it deletes.

This means you can get started, but I still have to update the index side of things. Hopefully that will be done in the next day or two.

**Comment by scd** [comment] 2017-05-08 00:04
I have also got the webcovers being returned in area template

```
"webcovers": [
    {
        "origHeight": "1824",
        "dateUploaded": "2013-08-27T18:36:16Z",
        "id": "341516439",
        "hashID": "1e9353077007f80ddf71b7ba77813f5367bd59cc",
        "origWidth": "1368",
        "node": {    # the node for which the image was uploaded - do we need this here?
        },
        "activeFocus": {
            "bottom": "2",
            "right": "4",
            "id": "341516439",
            "left": "3",
            "top": "1",
            "type": "webcover"
        }
    }
],
```

Note it is a list of webcovers. We probably need to discuss the policy for the primary webcover which will be managed via the label. NOTE TO SELF - FORGOT TO PASS THE LABEL THOUGH.

In summary the template data on the photo page returns a `foci` parameter which is a list of focus items associated with that photo and the area page returns a `webcovers` parameter which is a list of webcover focus items associated with that page.

I have made a policy decision to only include webcover images that have been explicitly set up. This means that the focus area will be set by a human for all webcovers.

**Comment by brendanheywood** [comment] 2017-05-08 00:10
Awesome - can you also pass through the atom data for the photo please, ie if there is a title, photographer etc. I won't use all of it but at minimum I want to be able to click on the photo and go to the photo page, but I think I also want to show the photographer / copyright on the crag page. I don't think I'll use the full photo title / account / route as I think it will add clutter, you are only a click away from it if you want it.

**Comment by rouletout** [comment] 2017-05-08 00:24
Will the definition of a photo as webcover run through the photo review process?

**Comment by scd** [comment] 2017-05-08 00:36
> can you also pass through the atom data for the photo please

@brendanheywood I think that is all ok as the photo template data is generated via our standard function. In this particular example there is no title, copyright or climber. There is actually two modes when calling the photo template data function - standard and full details. We are using standard for the webcovers. Full details also includes description, submittor, photographer and trip.

> Will the definition of a photo as webcover run through the photo review process?

@rouletout no it will not. What did you have in mind? The photo review process will be retired so I don't want to put too much effort into it. The main thing is that you should be able to go to the photo page from the review process in a single click. From the photo page you can do all the web cover processing you want.

**Comment by scd** [comment] 2017-05-08 00:47
In regards to the thumbor calculation should we just be hooking into the `thumborDynamicImageUrl` webhelper?

If I understand the algorithm requirements correctly we need to pass in a desired aspect ratio (eg 3x1) and the focus constraints and the webhelper should do the rest. 

@brendanheywood I will implement the algorithm for this, but just wanted you to agree with my assumptions above.

I think this is going to be really useful for a few aspects of the site.

**Comment by rouletout** [comment] 2017-05-08 00:47
I had nothing specific in mind - i assume you can only make a photo a web-cover once it ran through the process, correct?

Want to avoid we get a dildo as web-cover but would also like to see when a web-cover was set for an area, is this possible?

**Comment by brendanheywood** [comment] 2017-05-08 01:12
> In regards to the thumbor calculation should we just be hooking into the thumborDynamicImageUrl webhelper?
>
> If I understand the algorithm requirements correctly we need to pass in a desired aspect ratio (eg 3x1) and the focus constraints and the webhelper should do the rest.

I'd want a new webhelper which internally calls thumborDynamicImageUrl, it needs to accept absolute final dimensions like 1200x400 and the focal area and I was thinking it should also accept a 'method' string which determines which algorithm it uses to produce the final cropping. The algorithm I described above could be called something like "biggest-includes-focus" and is perfect for the webcover, ie find the largest cropping at the desired aspect ratio which includes the focal area (as best it can), and then resize it to the final dimensions. But I can also imagine lots of other subtle variations like "smallest-centered-focus" which I would use for very small images which need a tight cropping (eg a long list of crags each with an icon), or "largest-focus-right" or "largest-focus-left" where I want a large image and want the focus to be pushed to one side or the other so I can safely overlay text over it and apply a gradient or blur to one side etc. I was expecting to be writing all this, so don't worry about all the others but if you do implement this for me just get the first algorithm in place.

Finally it should also accept another optional argument which is a set of preformed thumbor filters to be inserted into the url in the right place so we can do any blurring or gradients etc on the thumbor side if we need.

> but would also like to see when a web-cover was set for an area, is this possible?

No but we should be able to easily get this by adding a 'type' filter to the activity facet, I've split that into:

https://github.com/theCrag/website/issues/2755

**Comment by scd** [comment] 2017-05-08 04:49
@brendanheywood I have implemented the wrapper similar to you suggested. Actually I re purposed `dynamicImageUrl` webhelper which was pretty much empty now that we have removed the precanned image processing.

I have called the method `biggest-includes-focus-center` because I don't thing we want it to fail if the focus constraints conflict (for example if the focus height was higher then possible display height when the demanded ratio is taken into account).

I have also integrated this with the area template page because this was the easiest way to test. The hard coded assignments will still work if there is not a webcover assigned from the database.

I have only done limited testing. In particular I have not done any testing if the function was asking for a vertically oriented cover. There are some particular edge cases we have to make sure work that I have not tested yet:
 - [ ] image smaller than 1200 pixels wide
 - [ ] image rotated 

Finally could you please check the wrapper function is in-line with your expectations. 

Also something came up when commenting out some of the old code. A while ago we created the concept of an area avatar. It is pretty much the same workflow as a webcover but the end result is a single avatar. The avatar process would be similar to an account avatar. I am wondering if there is anything we need to consider now with regards to area and account avatars, or just worry about it later.


@rouletout creating web covers will require at least coordinator permissions. Coordinators are one level up from editors so I imagine no dildo's will be installed. 

I think we should soft release this (ie not promote) because the primary reason for doing this now is to make it easier for you to install webcovers. There are a whole lot of management functions which we should implement if this feature starts getting wider use.

**Comment by brendanheywood** [comment] 2017-05-08 08:11
I've just given this a test here:

https://dev.thecrag.com/climbing/australia/gara-gorge

using this image:

https://dev.thecrag.com/photo/1015671939

It produced this url which is broken:

https://static.thecrag.com/img/0x23.6666666666667:1000x357/fit-in/1000x333/c7/d2/c7d238f191b8bf5dcc34a877fd6ea438578af983

If I simplify the numbers back to an integer then it kinda at least serves an image but isn't really doing what it's supposed to:

https://static.thecrag.com/img/0x23:1000x357/fit-in/1000x333/c7/d2/c7d238f191b8bf5dcc34a877fd6ea438578af983

* [ ] We need to round to integers so the final dimensions are pixel perfect and we don't get browser stretching / blurring 
* [ ] the og:image isn't using this code yet (this is currently pretty hacky and needs cleanup)

**Comment by scd** [comment] 2017-05-08 11:00
Rounding should be this.

https://static.thecrag.com/img/0x24:1000x357/fit-in/1000x333/c7/d2/c7d238f191b8bf5dcc34a877fd6ea438578af983

What specifically else is wrong? 

Is it that the original image is less than 1200 wide. I alluded to this being a edge case we had to look into.

Do you want to update the code to deal with the rounding correctly or do you want me too do this tomorrow.

**Comment by brendanheywood** [comment] 2017-05-08 12:49
I'm won't get to this for a bit, so yes please. I'd expect the pic to always be exactly 1200x400 but at least for the web that's not an issue and it will just get stretched so let's just ignore that for now.

**Comment by scd** [comment] 2017-05-09 01:40
I have been thinking about this picture perfect issue and it is more complex then one may first think and may lead to no solutions if the image size being requested is bigger than the original width. This is an extreme example, but if we requested an image size of 1000x1001 and the original image was 900x900 there is no pixel perfect solution.  Note that there is a pixel perfect solution if the original image was 1100x1100 because it is bigger and you can cut a perfect 1000x1001 square out of it.

Luckily we control what we select. So if we are requesting 300x1200 then there is a pixel perfect solution for a 900x900 original.

As far as I can see the algorithm to determine if there is a pixel perfect solution is to find the highest common factor of the requested width and height and if that is a greater than the original width and height then it can be done.

So what do we do if there is no pixel perfect solution? return empty string? return the original url?

We are choosing 1200 x 400 as our requested dimensions. Highest common factor is 400 so as long as the image is bigger than 3x1 it is fine. This implies to me we don't have to worry about the null solution set too much, but I think the algorithm should be robust.

**Comment by scd** [comment] 2017-05-09 02:37
Now we get something like:

https://static.thecrag.com/img/0x12:999x345/fit-in/999x333/c7/d2/c7d238f191b8bf5dcc34a877fd6ea438578af983

Pushed but only limited debugging.

**Comment by scd** [comment] 2017-05-09 03:27
Tested arapiles node on my dev and got this:

https://static.thecrag.com/img/1x187:1999x853/fit-in/1200x400/7e/90/7e902dd8845e9452aa0fb2e0cb4e8e70765a932d

Seems ok to me :)

**Comment by brendanheywood** [comment] 2017-05-09 07:50
For the web at least, every version will be responsive anyway and stretch to fit the space we tell it to, so if the aspect or the size is slightly off it is fine. I remember Adam had an issue with images not loading correctly because of an assumed size in the old app, but let's ignore that as it may be irrelevant in the new app.

**Comment by brendanheywood** [comment] 2017-05-18 13:05
JS library: https://fengyuanchen.github.io/cropperjs/

**Comment by brendanheywood** [comment] 2017-05-18 14:15
So @scd what I had in mind for the first basic UI is you have:

* [ ]  an 'Action' dropdown menu in the head like everywhere else, and in the menu it has the 5 or so links for every ancestor up the chain if you have permissions to set it.
* [ ] If one is set already then it will have a tick or something in the menu item.
* [ ] when you select any of them it loads up the cropper lib over the top of the image, selects a square by default and then positions it into the center of the photo. It size should be around 20-25% of the minimum of the width / height, something like this:

![image](https://cloud.githubusercontent.com/assets/187449/26205991/dc6d3c74-3c26-11e7-9803-8a8841608ae2.png)

* [ ] Under the image is a save button, similar to the save in the maps edit page, it's grayed out if there is nothing to save, then turns green if you have unsaved edits.
* [ ] because it is already drawn you can just drag it around. Most people will just drag it over the focus area and then press save. If the center is ok already then you just press save. You can resize the focal area if desired but I suspect most people won't need to.
* [ ] after you press save it does it's thing, then unloads the js lib and you are back to the raw photo page

Bonus points:
* [ ] you drag the bounding box around the screen it would also give you a preview of the bounding box used in the webcover. So this requires a js port of the various resize algorithms. If and when we show different pics in different places we could show all the various crop outlines overlaid so you can make sure they all make sense

![image](https://cloud.githubusercontent.com/assets/187449/26206370/fd910d4e-3c27-11e7-9506-83e5416e1bd0.png)

**Comment by scd** [comment] 2017-05-22 06:16
MVP for Ulf:
 - [ ] Webcover selection of node (similar to Action button, but just below the image)
 - [ ] Select area/ancester for webcover initialises a cropper crop box, either with pre-stored dimensions or a new box in the center of the image
 - [ ] You can see which ancestors have a webcover via a tickbox
 - [ ] Label is a priority number which determines which webcover takes precidence.
 - [ ] All foci of a photo is listed in the image details. We need to be able to see other foci, other than webcover and we need to see webcovers if the photo has been relinked to a different area.
 - [ ] Removing focus link via the listed foci
 - [ ] Permissions for each ancestor

**Comment by brendanheywood** [comment] 2017-05-22 08:00
I've done a quick test and it's working, example here:
https://dev.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/the-fortress

I think there is a minor kink with the cropping algorithm, ie I focused directly on this helmet:

![image](https://cloud.githubusercontent.com/assets/187449/26297917/6be0eca4-3f18-11e7-934e-3183e7aefe5d.png)

but the resulting pic isn't veritcally centered on the helmet:

![image](https://cloud.githubusercontent.com/assets/187449/26297929/7b3c0364-3f18-11e7-80fa-c12eb285d143.png)

**Comment by scd** [comment] 2017-05-23 03:34
Hmmm, @brendanheywood I am glad you picked this up. This was a bug in the front end which took a while to find and would have been a pain later. During the debugging process I found another potential bug in the backend.

This was a natural width versus width problem. The front end looked like it was working because coincidently I made the same error in saving and loading. In otherwords I picked up the image width from javascript when loading and canvas width when saving. I did not read deep enough in the specs, my bad.

Please reload and redo your test. Note, that you will have to reset the crop area as it is not saved correctly.

**Comment by brendanheywood** [comment] 2017-05-23 03:41
Looks perfect now :)

**Comment by brendanheywood** [comment] 2017-05-23 03:41
* [ ] One minor bug is that the photos are always linking to prod and not back to the current box

**Comment by scd** [comment] 2017-05-23 04:48
Fixed the image link.

**Comment by scd** [comment] 2017-05-23 04:52
I am going to close this because the issue is substatially completed. We may want to make a new todo list after we have been using it for a while.

FYI, I don't think we should do the algorithm in javascript. If we do want to have a webcover view on the photo page itself then we should get the dimensions from the server via the API.

**Closed by scd** 2017-05-23 04:52 UTC
Labels: 6: New Feature
