### ISSUE TITLE
Date taken: Use EXIF data as a preset

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2885] opened 2017-08-17 05:22 UTC
**What happened?**
I uploaded lots of pictures and every time I'm annoyed that the import process isn't capable of reading the EXIF data to preset the "Date Taken" field.

**What you expected:**
The import process reads the EXIF data and preset the "Date Taken" field. Additionally the process should read other EXIF data that may be interesting for the platform. E.g. the geolocation data.

**Comment by brendanheywood** [comment] 2017-08-17 05:41
thanks @lordyavin - I'm going to close this as a duplicate of https://github.com/theCrag/website/issues/606

**Closed by brendanheywood** 2017-08-17 05:41 UTC
Labels: 5: Enhancement, Area: Photos (videos)
