### ISSUE TITLE
Duplicate search results

### ISSUE THREAD

**Issue by dnnr** [theCrag/website#2780] opened 2017-06-04 20:54 UTC
**What happened?**

When searching for a route, the same node shows up twice in the results:

Example:
https://www.thecrag.com/nodes/fuzzy-search/stecklessriss?S=stecklesriss
![image](https://cloud.githubusercontent.com/assets/2630359/26765240/f75cb27c-4977-11e7-9ad3-67a23583b491.png)

Both results have the exact same link, so it's not a duplicate in the tree:
https://www.thecrag.com/climbing/germany/frankenjura/right-tower/route/19712419

Note that I mistyped the route name in my search query, but that doesn't seem to matter.
When typed correctly, other matches appear in the result (not duplicated), but the Steckelsriss still appears twice at the top.

**What you expected:**
I expected any matching node to only appear once in the results.

**Comment by brendanheywood** [comment] 2018-08-17 07:37
Closing as duplicate of https://github.com/theCrag/website/issues/540

**Closed by brendanheywood** 2018-08-17 07:37 UTC
