### ISSUE TITLE
Image "topo" structuring within pages.

### ISSUE THREAD

**Issue by NickFoulds** [theCrag/website#3746] opened 2020-08-26 23:37 UTC
I have been updating several topos and pages over the last few months and I always seem to come into an issue with trying to order topos so they sit where seems to make most logical sense for them. In particular trying to get an image of the boulder field or crag from a distance as a header image to make the page flow nicely and help people orient themselves well at the outset of approaching crag/field.

for example see yuri's pace page here: https://www.thecrag.com/climbing/australia/queensland/passchendaele/area/963175656

The first photo to come up on the pages feed is a boulder with routes 1-3 on it. The second image is one I took of the boulders from a further distance (easier to recognise on your way in and help you orient where you are compared to which boulders etc). However no matter how I play around with the route order on my image and the one before (excepting eliminating route 1 from the first block which doesn't make sense to do) I cannot get my image to sit at the top where it is most logically helpful.

I also find that you cannot centralise images in the feed or have an option to left align, right align or centre them depending on your choice. I would say probably all the images would look best centralised rather than a mixture of good and poor images (from various people all contributing on different devices) being erratically left aligned with different sizes etc. 
Can you add something to the code to automatically centralise images in the feed? and can you implement something that people like me updating areas can utilise to re-order images or perhaps simply add a box at the top that can have a "cover shot" image for the sub node in question with option to add topo lines as well?

Thank you for your time with this and I hope this can help to stimulate a change for the crag’s editing process to make it easier for users and developers as well as allowing for clearer topos and instruction for the topo user.
 
All the best and keep up the hard work!

**Comment by georg-d** [comment] 2020-08-27 10:21
Is this issue - except for the center alignment of topos - the same issue as https://github.com/theCrag/website/issues/3674 ?
> I like to make overviewing topos combined with smaller sections of topos to easier to find the route. But the way the topos are sorted makes this workflow just more confusing and messy.

If yes, please let's discuss "overview on top" in #3674 so we do not have _one more_ place to keep an eye on :) and let this issue only take care about center alignment of topos (it would IMHO make things easier, e.g. centering can be implemented quickly and the issue could be tagged as resolved).

Concerning center alignment: +1

**Comment by NickFoulds** [comment] 2020-09-01 08:11
Yep this is defo the same issue. 
Apart from the Centre alignment (but that is pure aesthetics and defo a second string to issue #3674 which was my major complaint. sorry to create a nearly duplicate thread was just following instruction from one of the crag team from on site advice. 

But happy to have this thread be just about the centring of the images. 

An perhaps creating a space for a central approach topo at the top rather than ordering within the feed which I think is more what issue #3674 is about.

Would that be better for 2 strings of workflow as you suggest?

**Comment by georg-d** [comment] 2020-09-02 12:42
> sorry to create a nearly duplicate thread 

No worries 😄 Even verterans create dupes because they may recall the topic was somewhere around but simply do not find the existing issue  due to "unlucky" search terms. Later on, some user will find this and can inter-link related issues, respectively, can close pure dupes.

> But happy to have this thread be just about the centring of the images.
> 
> An perhaps creating a space for a central approach topo at the top rather than ordering within the feed which I think is more what issue #3674 is about.
> 
> Would that be better for 2 strings of workflow as you suggest?

I'm not sure I understood you correctly; my understanding is: #3746 will only care about center alignment (would be great if you edited the title and added a short note at top of 1st post, so others do not need to read all the comments to understand the refinded scope of the issue) and #3674 + #3027 + #1190 will care about ordering of topos (approach topos on top, below overview topos, below these the detailed topos).

**Comment by rouletout** [comment] 2020-09-03 20:02
Closing as dupe of https://github.com/theCrag/website/issues/3674

**Closed by rouletout** 2020-09-03 20:02 UTC
