### ISSUE TITLE
idea: filter on the map results

### ISSUE THREAD

**Issue by juanliria** [theCrag/website#4194] opened 2023-05-01 15:23 UTC
It would be very helpful to be able to filter the results in the map area (not only in the routes area), i.e. I want to visualize in the map all routes from grade 5a to grade 6c. or filter it by type of climbing e.g. all routes tagged with "boulder"

**Comment by rouletout** [comment] 2023-05-09 12:55
Duplicate of https://github.com/theCrag/website/issues/3677 - closing

**Closed as completed by rouletout** 2023-05-09 12:55 UTC
