### ISSUE TITLE
Specific colours for gym routes

### ISSUE THREAD

**Issue by gui84** [theCrag/website#4061] opened 2022-05-14 18:38 UTC
Different colours for gyms routes, to differentiate them from outdoor ones on the map.

- For instance dark red instead of red for bouldering problems
- For instance dark blue instead of blue for sport routes

**Comment by scd** [comment] 2022-05-16 07:06
This is already in the system.

Here is an example I am in the process of setting up:

https://www.thecrag.com/en/climbing/australia/queensland/brisbane/wall-walkers-bouldering

The process requires setting up a route template which is assigned to each route and can determine colors and hidden grade range and other things. 

Because it is fairly technical only superusers can set this up for a gym. It will be quite a lot of work to make this user friendly for normal user permissions. 

FYI a route template details looks like this

<img width="404" alt="Screen Shot 2022-05-16 at 5 02 21 pm" src="https://user-images.githubusercontent.com/373058/168537210-e1da3c89-5da7-48c9-a3df-b4598eb6077a.png">

Because it involves us in setup it is really a service we want to offer for paying gyms, but let's see.

@gui84 pease send us email for the gym you want to setup.

**Comment by rouletout** [comment] 2022-05-16 12:28
I think this is a misunderstanding, @gui84 please confirm but I think you meant the gear style color, correct? As it is already used on your ascent map on your profile?

**Comment by gui84** [comment] 2022-05-16 14:36
@rouletout I mean on both general map and profile map :
- hide artificial routes (gyms, artificial walls)
- change colours in order to differentiate them from "natural routes"

**Comment by rouletout** [comment] 2022-05-18 13:40
So this is actually a duplicate of https://github.com/theCrag/website/issues/3867 - closing here and linking

**Closed as completed by rouletout** 2022-05-18 13:40 UTC
Labels: 5: Enhancement, Area: Maps
