### ISSUE TITLE
profile picture not changing / avatar redirect is being cached after the type of avatar has changed

### ISSUE THREAD

**Issue by jedparkes** [theCrag/website#2532] opened 2017-01-16 03:54 UTC
Just tried to change my profile picture on thecrag from the B/W one to one on Tannin
If i go to Account / Settings i see the Tannin one but on the dashboard page i see the old one still

Dashboard showing wring pic
![image](https://cloud.githubusercontent.com/assets/17869239/21970576/a4a85642-dbfb-11e6-84f4-63b19b21003e.png)

Account / Settings showing the right pic
![image](https://cloud.githubusercontent.com/assets/17869239/21970585/bc579280-dbfb-11e6-9d39-634f94df37a1.png)

**Comment by scd** [comment] 2017-01-16 04:53
This may be some sort of browser cache issue. Can you have a look on a different browser. This is what it looks like for me on your dashboard:

![screenshot from 2017-01-16 15-52-21](https://cloud.githubusercontent.com/assets/373058/21971332/d648fc4e-dc03-11e6-844c-3bda00f5a2de.png)

**Comment by brendanheywood** [comment] 2017-01-16 07:12
The root cause here is the /avatar/123 endpoint which then redirects to the facebook / gravatar / internal url is caching the redirect. Now that we have thumbor I think we deprecate that endpoint and just provide the templates with the data / urls they need to render the image link without the intermediate redirect.

As a short term fallback we can just remove either the expires header on avatar redirect.

**Comment by jedparkes** [comment] 2017-01-16 19:31
My profile pic is ok this morning but yeah my last one was a facebook one and this new one was one i uploaded to thecrag

**Comment by scd** [comment] 2021-01-11 00:02
Closing as there as I don't prepose fix this bug until we revamp how avatars are served.

**Closed by scd** 2021-01-11 00:02 UTC
Labels: 2: Bug fix, Area: Climbers / Profile, Area: Photos (videos), Performance
