### ISSUE TITLE
Annotations: Edit Button missing

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3491] opened 2019-07-05 22:04 UTC
**What happened?**

I added 3 annotations here: https://www.thecrag.com/climbing/switzerland/alpen/zentralschweiz/area/557684958 and wanted to edit the text afterwards but the Edit button is not available (on the right). It is there for the routes though.

<img width="937" alt="Screenshot 2019-07-05 at 15 43 18" src="https://user-images.githubusercontent.com/19162952/60746840-dfa26600-9f46-11e9-8705-11a3ea8474fb.png">

<img width="952" alt="Screenshot 2019-07-05 at 15 43 24" src="https://user-images.githubusercontent.com/19162952/60746844-e7620a80-9f46-11e9-9079-618e22d50ea1.png">

If you edit the whole area you may edit the annotation.

Ideally also provide screenshots:

**What you expected:**

Edit button as for the routes.

**Comment by scd** [comment] 2019-07-27 02:10
@brendanheywood can you please triage this

**Comment by brendanheywood** [comment] 2019-07-27 07:18
This looks like a regression from when I added the annotation hover events a release or two ago as part of the annotations in topos. It should be reasonably easy to fix... looking

**Comment by brendanheywood** [comment] 2019-07-27 07:46
Fixed in dev

**Closed by brendanheywood** 2019-07-27 07:46 UTC
Labels: 2: Bug fix, Content editing
