### ISSUE TITLE
Route Location Issue

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2209] opened 2016-05-24 06:26 UTC
When entering multiple routes through the Add Routes command latitude and longitude information is not stored for the route (if entered previously, it can't be edited). When entering a single route lat/long can be entered (at least occasionally).
Also, a hint if W or E is the negative value would help.

**Comment by brendanheywood** [comment] 2019-01-14 04:20
closing as duplicate of https://github.com/theCrag/website/issues/1046

**Closed by brendanheywood** 2019-01-14 04:20 UTC
Labels: 2: Bug fix, Area: Maps, Content editing
