### ISSUE TITLE
Link to own ascents in crag overview doesn't always show

### ISSUE THREAD

**Issue by dnnr** [theCrag/website#3833] opened 2021-01-16 10:46 UTC
This is related to #3398.
At some crags, the link to one's own ascents on a crag does not show even though it should.

For example, I have climbed at [Happurger Wand](https://www.thecrag.com/en/climbing/germany/frankenjura/happurger-wand), but that page looks like this: 
![image](https://user-images.githubusercontent.com/2630359/104809693-5a606880-57ef-11eb-870b-14f770b4252c.png)

As a good-case example, I've also climbed at [Holzgauer Wand](https://www.thecrag.com/en/climbing/germany/frankenjura/holzgauer-wand), and it looks like this: 
![image](https://user-images.githubusercontent.com/2630359/104809720-82e86280-57ef-11eb-803f-7df1a59d455c.png)

The notable difference between those two crags is that Happurger Wand is the bottom-most node, which directly contains the routes. In contrast, Holzgauer Wand contains two other sub-crags (which should probably be sectors, but that doesn't matter here) but no routes directly.

I've checked a couple more places and this behavior is consistent. Wherever I've looked, the "# by you" link is always missing at the bottom-most node. This also holds if the bottom-most node is of type sector, not crag.

**Comment by rouletout** [comment] 2021-01-16 11:37
@dnnr thanks for the detailed analysis - this is a duplicate of https://github.com/theCrag/website/issues/3801 - I'll refer from there and close here

**Closed by rouletout** 2021-01-16 11:37 UTC

**Comment by dnnr** [comment] 2021-01-16 15:17
Oh, my bad. I'm not used to my weird tiny bugs already having been noticed by other people, so I forgot checking first. Thanks for handling it!
