### ISSUE TITLE
History of events incorrect, shows current name and grade instead of version at that point in time

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3350] opened 2019-01-25 14:14 UTC
**What happened?**

I added a new route with a dummy name and no grade. Later on another user updated name and grade. Now the event of my edit displays the data of the more recent edit.

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/kletterwerk/route/2202218979

My add:
![screenshot_2019-01-25-14-41-06](https://user-images.githubusercontent.com/1528540/51750729-3e6bd580-20b3-11e9-9925-4a25cc44b935.jpg)

The others update:
![screenshot_2019-01-25-14-41-34](https://user-images.githubusercontent.com/1528540/51750744-49266a80-20b3-11e9-9b6b-527bd43b812c.jpg)

**What you expected:**

* [ ] don't reflect updates/changes to events in the past. Grade should be as I added it. The same for name. IMHO the current implementation is misleading and irritating.

**Comment by Mdemaillard** [comment] 2020-03-10 12:03
Duplicate of #1470

**Comment by rouletout** [comment] 2021-07-19 19:02
Closing in favor of #1470

**Closed by rouletout** 2021-07-19 19:02 UTC
Labels: 2: Bug fix, Area: Streams / feeds
