### ISSUE TITLE
If I delete or merge a route, there is a phantom line left on the topos it was attached to

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#24] opened 2011-03-05 01:03 UTC
Should merge the topo data to the other route

**Comment by Mdemaillard** [comment] 2020-03-13 06:13
reference to #677 as well might be interesting

**Comment by rouletout** [comment] 2020-12-27 10:46
Can't reproduce that - added 2 routes to a topo, merged them, no issue. Unlinked it, no issue. Delete not possible as it is on teh topo. Closing.

**Closed by rouletout** 2020-12-27 10:46 UTC
Labels: 2: Bug fix, Area: Reparent/Merge, Feature: Phototopo
