### ISSUE TITLE
Software error when trying to add route (to gym)

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2977] opened 2017-12-09 08:40 UTC
**What happened?**

Today, I repeatedly get the following error when trying to add a route to a gym. Probably only something temporary, but I thought you should know:

```
Software error:

DBD::mysql::st execute failed: Deadlock found when trying to get lock; try restarting transaction at /opt/CIDS/perllib/BSIS/Db.pm line 1228.
For help, please send mail to the webmaster (scd@thecrag.com), giving this error message and the time and date of the error.
```

(please also provide urls and screen shots)

**What you expected:**
No error, route added.

**Comment by birgander2** [comment] 2017-12-09 09:50
Seems to work again!

**Comment by lordyavin** [comment] 2017-12-11 08:39
Duplicate of #2950

**Comment by lordyavin** [comment] 2017-12-21 07:14
Closing because of duplication.

**Closed by lordyavin** 2017-12-21 07:14 UTC
Labels: 2: Bug fix
