### ISSUE TITLE
Expose existing guidebook facilities better

### ISSUE THREAD

**Issue by scd** [theCrag/website#1562] opened 2014-07-26 23:05 UTC
- [ ] editor's access to adding guidebooks
- [ ] better integration of publications

**Comment by brendanheywood** [comment] 2017-09-07 13:02
Closing this as a duplicate of https://github.com/theCrag/website/issues/396

**Comment by rouletout** [comment] 2022-09-04 16:28
This is done via the Plan your trip feature starting with release 101

**Closed by rouletout** 2022-09-04 16:28 UTC
Labels: 5: Enhancement, Area: Publisher/Copyright/Publication
