### ISSUE TITLE
Area for ascent listed as "unknown"

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#2655] opened 2017-03-20 10:05 UTC
For some crags in the region [Arco - Trento Area](https://www.thecrag.com/climbing/italy/northern-italy/arco-trento-area), ascents are listed with an area "unknown" in the logbook:

<img width="711" alt="screenshot 2017-03-20 10 52 44" src="https://cloud.githubusercontent.com/assets/54371/24095310/d28833e2-0d5c-11e7-90eb-dbf9326cf9b6.png">

Examples:
https://www.thecrag.com/climbing/italy/parete-san-paolo/route/579887076
https://www.thecrag.com/climbing/italy/massone-policrumble/area/15954109

Is this a problem of the strange structuring of the crags in this area? There are regions on the same level as crags, and for the first example, there are even routes on the same level as sectors.

**Comment by brendanheywood** [comment] 2017-03-20 10:29
This may be because we are rebuilding all the stats, this loks fine on the dev box and I just checked the hierarchy and everything looks good to me. I'll move this into this release and mark as must resolve and we can remove that if it turns out to be something else after the stats rebuild.

**Comment by scd** [comment] 2017-03-20 11:03
This is a bit weird. I cannot actually see it now. @quaestor can you confirm if it is still a problem for you?

**Comment by brendanheywood** [comment] 2017-03-20 11:28
I saw it on this page:

https://www.thecrag.com/climbing/italy/parete-san-paolo/route/579887076/ascents

It's gone for me too, @scd would the stats rebuild have affected this? Is that running right now?

**Comment by quaestor** [comment] 2017-03-20 11:35
@scd It's gone for the first example now, but I still see it for the second, i.e. Massone.

**Comment by scd** [comment] 2017-03-21 00:29
It is gone for this page as well. It is definitely not caused by stats processing.

The word 'unknown' comes from the web helper `linkArea`, when there is no name parameter. My guess is there is a transient TLC issue when the ancestors have had their TLC changed. The logic is fairly complex in `crumbtrailPartial` template.

I am satisfied that it is not a serious issue and is transient. I don't think it is a priority to track down the root cause just now.

**Comment by quaestor** [comment] 2017-03-21 09:58
It's not gone for me. I still see it here:

https://www.thecrag.com/climbing/italy/massone-policrumble/route/1137883719/ascents

**Comment by scd** [comment] 2017-03-22 21:49
@quaestor is it still there for you. I just checked again and it is fine for me. If it is still there then could you please send me a screen shot, as we should not be getting different versions of this.

**Comment by quaestor** [comment] 2017-03-22 23:40
@scd indeed, meanwhile it is resolved.

**Comment by scd** [comment] 2017-03-23 03:38
I am grateful there is nothing else to do here for the moment, but I fear there is something significant to resolve one day.

**Comment by Mdemaillard** [comment] 2020-06-09 08:49
closing - no update in 2 years, major update since then.

**Closed by Mdemaillard** 2020-06-09 08:49 UTC
Labels: 2: Bug fix, Feature: TLC, X: Need to be monitored
