### ISSUE TITLE
Route count indicator shows one route more than it should

### ISSUE THREAD

**Issue by dkleinrath** [theCrag/website#3793] opened 2020-11-23 13:00 UTC
**What happened?**

When hovering over the route count indicator at the top of an area, it always adds one route more than it should. For example: Hovering over the 4th grade (UIAA - see first screenshot below) shows 4 routes, which indicates that there are supposed to be 4 routes in the 4th UIAA grade in this area, but in reality there only exist 3 routes in the 4th grade (1 less - see second screenshot below). 

This bug seems to happen *almost* always, no matter what area (at least for UIAA - not tested with other rating systems): i.e. for the linked area it shows 2 routes for UIAA 4+ (actually only 1 exists), 3 routes for 5- (actually only 2 routes exist) etc. Interestingly for the 7th grade the hover shows the correct number of 5 routes...

Example url(s) to reproduce the problem:
https://www.thecrag.com/de/klettern/austria/wien-vienna-area/area/967327584

screenshots:
![grafik](https://user-images.githubusercontent.com/9556202/99964105-13c43400-2d93-11eb-959b-04c443bb86f5.png)

![grafik](https://user-images.githubusercontent.com/9556202/99963894-c47e0380-2d92-11eb-84f4-ca33b516ebe2.png)

**What you expected:**

* [ ] When hovering over a grade, the correct number or routes for the area should be shown.

[tested with Firefox 82.0.3 (64-Bit)]

**Comment by DaneEvans** [comment] 2020-11-24 01:34
duplicate of #3545

**Comment by rouletout** [comment] 2020-11-26 17:10
Closing as duplicate

**Closed by rouletout** 2020-11-26 17:10 UTC
