### ISSUE TITLE
topo tool, add "free drawing tools"

### ISSUE THREAD

**Issue by gogulfresh** [theCrag/website#3234] opened 2018-08-14 20:34 UTC
**What happened?**
I would like to add the ascent/decent on a topo

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/germany/oberbayern/area/356281389

Ideally also provide screenshots:

**What you expected:**
Smth like attached screenshot: Adding path w/ arrows + free text box. 
![sommersonnesonne_180806_181545_ascent](https://user-images.githubusercontent.com/18306619/44116867-f815f376-a011-11e8-85e4-1e5211eab3c8.JPG)

**Comment by brendanheywood** [comment] 2018-08-15 00:16
thanks @gogulfresh I will close this as a duplicate of this one:

https://github.com/theCrag/website/issues/1614

Note we use the number of comments on an issue as a rough guide to help set priorities to it's better to merge these.

**Closed by brendanheywood** 2018-08-15 00:16 UTC
