### ISSUE TITLE
Grade slider ranking facet plot range issue, climbers can overlap grade system labels on left

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2680] opened 2017-03-30 14:48 UTC
1704 position is overlapping with the two scales, and 1705 is half way outside the left side of the graph (it looks like a different problem then #2679)
   
![screen shot 2017-03-31 at 11 21 31](https://cloud.githubusercontent.com/assets/19304867/24546768/b0f38618-1604-11e7-9b79-1e65c6582861.png)

https://www.thecrag.com/climbing/world/climbers/using-stat/boulder-rating/?page=69

**Comment by brendanheywood** [comment] 2017-03-30 23:45
@nclementel can you edit the issue above to flesh it out with some more detail? If this a duplicate of https://github.com/theCrag/website/issues/2679 then can you please close it and comment there instead?

**Comment by Mdemaillard** [comment] 2020-04-04 13:34
This is mostly noticeable when the filter option leaves a small number of climber, thus covering a large grade band.
https://www.thecrag.com/climbing/world/climbers/from-country/belgium/using-stat/sport-rating/?page=1

**Comment by rouletout** [comment] 2021-01-02 15:47
But in neither of the examples it it shows what Nicolas initially reported, closing

**Closed by rouletout** 2021-01-02 15:47 UTC
Labels: 2: Bug fix, Area: CPR / Ratings / Rankings, Area: Display/Layout
