### ISSUE TITLE
No grade suggestion in gyms routes

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4157] opened 2022-12-22 17:41 UTC
there is no way to suggest a grade change (this I think it has been already reported) in a gym tick, this should be configurable by the gym owner but it looks like it is not (or all gyms I've seen have it deactivated)

![image](https://user-images.githubusercontent.com/17315806/209194226-f8c1566f-76e1-4fc7-97d5-e609606cae37.png)
rock routes

![image](https://user-images.githubusercontent.com/17315806/209194300-d3fb53b4-638d-41a2-ae00-df8a24e4fc9d.png)
gym routes

**Comment by rouletout** [comment] 2022-12-26 02:56
Duplicate of https://github.com/theCrag/website/issues/4112 - closing

**Closed as completed by rouletout** 2022-12-26 02:56 UTC
