### ISSUE TITLE
New tick flow - limited set of tags

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#4131] opened 2022-11-02 21:05 UTC
I like the idea of adding tags while logging ascents, opposed to entering into editing the route. However, the accepted (or listed) tags are just a small subset, currently unknown to me. E.g., I'd like to tag a climbed crack as "crack" and "dirty", which currently doesn't seem to be supported.

**Comment by rouletout** [comment] 2022-11-02 21:13
I think this is a duplicate of https://github.com/theCrag/website/issues/1713

As for the tags available now, these are Ascent tags (all are new) and not directly related to the route.

Side note, adding route related tags was evaluated but discarded as it overloads the Ui and creates issues with permissions. 

Closing this but leaving 1713 open for now.

**Closed as completed by rouletout** 2022-11-02 21:13 UTC
