### ISSUE TITLE
Topo edit at top right corner is not possible hidden behind buttons

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1844] opened 2015-02-03 08:10 UTC
It seems impossible to edit points after they have once been placed "under" the hide / deselect button. Possible solution: Move the two buttons outside of the actual topo, i.e. just some pixels higher.

**Comment by brendanheywood** [comment] 2015-02-04 00:19
yeah the plan is to move these to the editing panel on the left, and then also make the editing panel float above the topo and also be dragable

**Comment by brendanheywood** [comment] 2015-02-27 23:22
See duplicate #1651

**Comment by lordyavin** [comment] 2018-01-08 06:34
Duplicate of #1651

**Comment by brendanheywood** [comment] 2018-01-08 06:37
Yeah I think I'll just close this and track it in the older #1651

**Closed by brendanheywood** 2018-01-08 06:37 UTC
Labels: 2: Bug fix, Feature: Phototopo
