### ISSUE TITLE
Ability to reparent/move multiple areas/routes to a new node

### ISSUE THREAD

**Issue by jalonavens** [theCrag/website#3443] opened 2019-05-18 12:20 UTC
Issue:
Unless I'm mistaken (or don't have the necessary privileges) it is not possible to reparent or move multiple routes or areas to another parent.
After selecting multiple routes if I right click on a route the "Move" option is greyed out. See screenshot below.

This would be quite useful in these situations I've often encountered:
- a need to move multiple routes in the wrong sub-areas of a crag
- a need to split up a crag with far too many routes into sub-areas (e.g. [Stanage Popular](https://www.thecrag.com/climbing/united-kingdom/stanage/area/654583173) which has nearly 500 routes in the crag directly)

Screenshot showing greyed out Move item in Route menu:
![image](https://user-images.githubusercontent.com/13288347/57969507-01598500-79bb-11e9-89c6-f1f36b06cfe5.png)

**Comment by brendanheywood** [comment] 2019-05-18 12:39
You can do this, just not from the context menu when you have selected multiple routes.

Try this:

![image](https://user-images.githubusercontent.com/187449/57969850-aa08e400-79bd-11e9-9b3c-4ccd8a6a9602.png)

then:

* Reparent children of selected node

Then select the batch to move

Being able to do this from a selection is a duplicate of this one: https://github.com/theCrag/website/issues/3154

**Comment by scd** [comment] 2019-05-18 12:56
To reparent multiple routes, start the process at the area level. The
system should ask you if you want to select routes

**Comment by jalonavens** [comment] 2019-05-31 08:15
Thanks for this tip - saved me quite a bit of work organising some messy
crags!

As you you've probably seen I raised an issue to get the menu item renamed
a bit more appropriately https://github.com/theCrag/website/issues/3456

**Closed** 2019-06-03 06:03 UTC
