### ISSUE TITLE
Logbook permits logging in the future

### ISSUE THREAD

**Issue by Wyko** [theCrag/website#4138] opened 2022-11-07 10:58 UTC
If you check [the world logbook](https://www.thecrag.com/climbing/world/ascents) you will see several ascents in 2023 and beyond, which obviously is incorrect. This probably shouldn't be permitted.

**Comment by rouletout** [comment] 2022-11-09 00:52
duplicate of closed issue https://github.com/theCrag/website/issues/31

**Closed as completed** 2022-12-26 02:31 UTC
Labels: 7: Idea for discussion, Area: Logbooks Ticking & tick lists
