### ISSUE TITLE
Place low-offs in topo independent of actual climb

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2638] opened 2017-03-07 08:52 UTC
It seems to be impossible to add markers to a topo, which are not linked to an actual climb. In my case, I wanted to add the location of a lower-off, which is not directly part of the (trad) climb and common for all routes onto this rock tower. To have only one lower-off per rock tower is standard in [Elbsandstein](https://www.thecrag.com/climbing/germany/sachsische-schweiz). This information can be quite important, because sometimes it is a major problem to locate the lower-off once you have reached the summit.

**Comment by brendanheywood** [comment] 2017-03-07 12:10
thanks - I'm going to close this as a duplicate of #1614 please read that and comment on it as needed

**Closed by brendanheywood** 2017-03-07 12:10 UTC
