### ISSUE TITLE
UI: Create route and tick at the same time

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2491] opened 2016-12-24 03:21 UTC
Question by Jakob Schubert: "is there a way when you create a route in the system to directly tick it at the same time?"

This is obviously only an issue where you have to do that for many non-existing routes (like all the hard ones he climbed). Ultimately I think we should solve taht by providing the content ahead of time...

**Comment by Mdemaillard** [comment] 2020-03-17 11:20
Duplicate of #1559. Closing

**Closed by Mdemaillard** 2020-03-17 11:20 UTC
Labels: 5: Enhancement, Area: Logbooks Ticking & tick lists, Content editing
