### ISSUE TITLE
Multipitch aid grades and alternative grades

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3527] opened 2019-09-16 19:01 UTC
**What happened?**

I tried to enter some multipitch routes with combined aid grades in some pitches, like "6a/A1". This is not displayed correctly. See here:
https://www.thecrag.com/climbing/portugal/lisbon-area/area/2665471839
The aid grade appears only in the total grade of the route, not in the display of the individual pitches.

Also, there seem to be no possibility to enter alternative grades, like "6a/A1 (7a)". For sure this can be done in some additional free text, so this is just a detail.

**Comment by rouletout** [comment] 2019-09-16 19:08
The second part (aid and alternative free garde) is covered here: https://www.thecrag.com/de/artikel/grades#beispiele

<img width="673" alt="Screenshot 2019-09-16 at 14 06 24" src="https://user-images.githubusercontent.com/19162952/64985857-75356c80-d88b-11e9-9790-fe1cf22d04fc.png">

**Comment by birgander2** [comment] 2019-09-17 06:40
Ah, thanks, got it. But the result is still a mess: "6a A1 [6c], 6a" should result in either 6a A1 or in 6c for the entire route. Another example:
https://www.thecrag.com/climbing/portugal/lisbon-area/route/2665537215
Total free grade should be 7a here, not 6b+

And sorry for updating the data in the meantime, now all pitches have alternative free grades and the first problem is not visible anymore. What I mean was that for "6a A1, 6a" the combined aid grade is not included in the individual pitch display.

**Comment by brendanheywood** [comment] 2019-09-18 07:51
For the second part of the bug, can I confirm that what you are saying you expect is this:
![image](https://user-images.githubusercontent.com/187449/65128363-b7ea7680-da3c-11e9-9e9b-03194ad9c035.png)
instead of this:
![image](https://user-images.githubusercontent.com/187449/65128338-aa34f100-da3c-11e9-89ff-201b1b1e4d2e.png)

**Comment by birgander2** [comment] 2019-09-18 10:02
Exactly. And 7a as the route grade, not 6b+.

**Comment by lordyavin** [comment] 2019-09-20 06:33
https://www.thecrag.com/climbing/united-states/boulder-canyon/route/20886763
![grafik](https://user-images.githubusercontent.com/1528540/65304605-58e24a00-db81-11e9-92c7-9aaff21af14c.png)
![grafik](https://user-images.githubusercontent.com/1528540/65304615-613a8500-db81-11e9-8384-e54f7abad73a.png)

**Comment by brendanheywood** [comment] 2019-09-20 06:49
@scd for the pitch part of this bug, can you see any issue with displaying the raw grade as it was entered (just escaped) rather than the grade it was parsed as? In the majority of cases these are equivalent, but I there will be some cleanup of the grades, like upper / lower case etc

**Comment by brendanheywood** [comment] 2019-10-26 10:16
I've pushed the change so that the grade shown in the pitches the grade as it was entered, not as it was parsed. I think in general this is better but it will likely make some things worse. But in those cases it's probably better if the data was cleaned up anyway and this exposes it.

I won't close this as the second half of the issue isn't done

**Comment by Mdemaillard** [comment] 2020-03-22 12:04
as a test in sandpit, i logged 2 2-pitches with the same ratings, but inverted which one is in bracket. Even if one should be the preferred input way, this highlights a few issues

1. free grade [aid grade]
https://www.thecrag.com/climbing/test-area/route/3166194117
The overall grade gets the right value, but add erroneously the aid component
![image](https://user-images.githubusercontent.com/60388146/77248914-f2300d00-6c45-11ea-8fbe-0ebf95df4ad0.png)


2. aid grade [free grade]
https://www.thecrag.com/climbing/test-area/route/3166194048
the overall grade for multipitch is wrong
![image](https://user-images.githubusercontent.com/60388146/77248904-dfb5d380-6c45-11ea-8a82-779d7c85729f.png)

**Comment by Mdemaillard** [comment] 2020-03-29 21:32
see #3133

**Comment by scd** [comment] 2020-11-10 06:09
This will sort of be fixed for next release. However please note that the interpretation of `7a [A0]` is 7a OR A0. In otherwords you can do it as a 7a or it is an A0 aid pitch.

I think it should be used as `7a A0` which means it A0 route with 7a free climbing. 

So I think this can be fixed now in data entry but next release you should see it come through as an Aid route in the pitch.

**Comment by scd** [comment] 2020-11-10 06:10
See also https://github.com/theCrag/website/issues/3651

**Comment by rouletout** [comment] 2020-11-30 18:23
Fixed with release 88

**Closed by rouletout** 2020-11-30 18:23 UTC
Labels: 2: Bug fix, Area: Multipitch, Feature: Grades
