### ISSUE TITLE
Help Article has starnge blue boxes

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3356] opened 2019-02-05 14:32 UTC
**What happened?**

https://www.thecrag.com/de/artikel/cprtimeline shows light blue boxes under each graph - see screenshot

Ideally also provide screenshots:

**What you expected:**

no boxes
<img width="694" alt="screen shot 2019-02-05 at 08 32 16" src="https://user-images.githubusercontent.com/19162952/52280065-9363e300-2920-11e9-8f99-684498b0a42e.png">

**Comment by brendanheywood** [comment] 2019-02-07 05:47
@scd the root cause here is this article is just not using the responsive iframe template. Look at the CPR article and minor/responsive-iframe

**Comment by Mdemaillard** [comment] 2020-03-04 14:49
not visible for me on Desktop + Chrome. Closed already ?

**Comment by Mdemaillard** [comment] 2020-03-22 12:30
Also not appearing on android phone. closing.

**Closed by Mdemaillard** 2020-03-22 12:30 UTC
Labels: 2: Bug fix, Area: Help
