### ISSUE TITLE
Grades are displayed strange

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1913] opened 2015-04-23 07:56 UTC
Since the last update, grades are displayed in a strange way. Have a look here:
http://www.thecrag.com/climbing/france/fontainebleau/area/391703718

Now there is "{FB}" instead of "FB", and if there are multiple grades registered, all of them are shown in the overview, not only the local one. Looks very confusing....

**Comment by brendanheywood** [comment] 2015-04-23 08:01
Very odd. Definitely a bug.

**Comment by scd** [comment] 2015-04-23 11:15
There are two things going on here:

1. We should be assigning the context to FR. The new code properly handles FB (Font) grades in the French context when the route is a boulder gear type. The {FB} is there to explicitely indicate that the route's context is different from the default context for the country. So this is working, just bad data.

2. There was some historical code which was not turned off which forced the foreign context flag for a different reason. So even if you changed the routes context to French, it still snuck through as a FB foreign conext. I have fixed this in prod.

**Comment by birgander2** [comment] 2015-04-23 18:47
Do you really think that issue is closed?

- Local grade system is correctly set to Fontainebleau, but still one gets the brackets:
http://www.thecrag.com/climbing/france/fontainebleau/area/392559174
- Multiple grades are still displayed quite chaotically:
http://www.thecrag.com/climbing/france/fontainebleau/area/391703718
- Additionnally, wrong grade / systems cannot be cleaned up / deleted anymore in edit mode (was complicated before, but working)
- How can one distinguish between for example FB4 and FR4? The community grade has no indication.
- FB grades are default in France (and elsewhere), and so are SX grades in Germany:
http://www.thecrag.com/climbing/germany/sachsische-schweiz/gebiet-der-steine/area/15757363

Sorry guys, but before it was much better. This looks like a debug mode.

**Comment by scd** [comment] 2015-04-23 22:23
> Do you really think that issue is closed?

Yup substantially. The multiple grades being displayed has not been resolved, which I missed in your comment. I will raise a separate issue for that. You have made some interesting points below which I will address individually. Have you read issue #1874 ?

>    Local grade system is correctly set to Fontainebleau, but still one gets the brackets: http://www.thecrag.com/climbing/france/fontainebleau/area/392559174

Actually we have been trying to get rid of Fontainebleau context. The correct context for this crag should be set to France. Note that there is a difference between grade context and grade system. Have you read the grade article:

http://www.thecrag.com/article/Grades

There are some updates toward the end that are interesting. Especially the examples and the try it yourself section.

An 4c+ in France for a boulder will be interpreted by the system as a Font grade. However if it is a sport route then it will be interpreted as the standard french grading system. 

I have changed the context for the routes in this area. There might be quite a few more of these, so I am wondering if it is worthwhile writing a bulk update. 


>    Multiple grades are still displayed quite chaotically: http://www.thecrag.com/climbing/france/fontainebleau/area/391703718

Now raised in issue #1914. This probably needs way more discussion and something we missed in our analysis.

>  Additionnally, wrong grade / systems cannot be cleaned up / deleted anymore in edit mode (was complicated before, but working)

???. This was the main motivation behind this change. It was so difficult to change things before that nobody did it. Now you just edit the text. Maybe you could outline more where the issue is. Maybe the UX is not so clear.


>    How can one distinguish between for example FB4 and FR4? The community grade has no indication.

If it is a boulder it is a font grade, otherwise it is a standard french grade.

>    FB grades are default in France (and elsewhere), and so are SX grades in Germany: http://www.thecrag.com/climbing/germany/sachsische-schweiz/gebiet-der-steine/area/15757363

SX is a problem because it clashes with UIAA and Germany uses both. This is raised in issue #1915

In France please either change FB context to FR context, or let me know so I can do it.

> Sorry guys, but before it was much better. This looks like a debug mode.

:( 

Actually we appreciate the feedback so we can get through the teething issues. I put this issue off for so long because of the complexity. This is actually a massive improvement. We did do lot's of testing, but clearly there are still issues remaining. Besides, there is no going back.

I will keep this issue open so we can discuss anything else that comes up.

**Comment by brendanheywood** [comment] 2015-04-24 03:08
>> How can one distinguish between for example FB4 and FR4? The community grade has no indication.

>If it is a boulder it is a font grade, otherwise it is a standard french grade.

For weird reasons, like maybe a highball boulder with a route grade, you can also still force a system like this:

![image](https://cloud.githubusercontent.com/assets/187449/7311642/5636ca8c-ea82-11e4-844c-9692511dda8a.png)

![image](https://cloud.githubusercontent.com/assets/187449/7311657/74db74ec-ea82-11e4-8010-37a85e63a55f.png)

One problem with this is that which code prefixes to use isn't documented anywhere, we need to add this to the grade table help doc. Only a single example for 'UKT:5c'

**Comment by birgander2** [comment] 2015-04-24 07:39
> Actually we have been trying to get rid of Fontainebleau context. 
> The correct context for this crag should be set to France.

This is something I find confusing. The "local grade system" there is Font not French, but ok. At least you should call the box differently then, not "local grade system". And I think that overall the context thing is not that easy. In Germany for example, we have UIAA and Font grades for bouldering, as well as UIAA and Saxon (and even French) grades for routes...

> I am wondering if it is worthwhile writing a bulk update.

Well, yes, at least whole Fontainebleau needs to be set to French according to your logic. But not yet whole France, you probably missed the Annot boulder grade system (B1 - B15)  ;-)

> Maybe you could outline more where the issue is. 

For cleaning up, I miss the systems. What means the second 4 in "4B 4 V0" in case of a Font boulder for example ?  The missing code prefixes are confusing, you know what's going on, but not me. To update the doc would be a first step, but honestly, I think a different input box would be better. You know, people never read the docs... Personally, I don't like the brackets when having a "wrong" context. You already add the letters (SX or FB), that should be sufficient.

**Comment by birgander2** [comment] 2015-04-24 07:45
Just one example, especially have a look at route #8: Why here "{FR} FR:7a+", while the next one "{FR} 6b"? Very confusing at the moment. I would expect "FR 7a+" and "FR 6b".
http://www.thecrag.com/climbing/germany/oberbayern/area/439569120

**Comment by brendanheywood** [comment] 2015-04-24 13:00
> This is something I find confusing. The "local grade system" there is Font not French, but ok.

Yes agree completely this is a long standing typo bug that's come up before. @scd this isn't in the codebase, assume it's config data somewhere? I think it only appears on the single route edit page so will shortly be moot when we use bulk edit for everything.

> Why here "{FR} FR:7a+"

Also agree the context is overkill and in pretty well all cases redundant because it should show the system if that system isn't in the default list for the country.

@scd I'm not sure on what the final business logic was that went live last release, this is how I would think it would work if you can confirm this:

* for each part of a grade, parse it into a system based on the context provided etc
* unless it is prefixed with a system code, eg FR: which forces the system
* so now each part of the grade has a grade and system
* look at the country default context, if each system is local to that then show nothing, if not then show the system prefix eg FR:

ie I think the subtlety is that the context drop down in my way above is only used for parsing the grade and not used directly in any way for displaying the grade?

> And another one: "9- FR:". How can I delete the FR? Seems not possible.

That was really weird! I just edited it, added a space, deleted the space, it previewed fine, I saved it and it was gone. No idea what was going on there

> you probably missed the Annot boulder grade system (B1 - B15)

This seems reasonably sane to add as a new system, roughly V grade + 3 and won't clash if only FR and boulder. How many problems do you reckon total use this system and is it still alive and well?

>  front traverse grade

FTW? We've seen some crazy grade systems but this is probably the craziest. So I guess this means you could have two 7a+ boulder problems on the same rock, but those grades mean different things because one is a traverse and one is up? We currently don't have a solid way of flagging a 'traverse' as different to any other boulder problem. I'm thinking it's not worth trying to get that one working. How many problems would it apply to?

**Comment by birgander2** [comment] 2015-04-24 14:36
> How many problems do you reckon total use this system and is it still alive and well

Annot is a quite large bouldering area, between 1000 and 2000 problems. The system is alive there to my knowledge, but very likely only there... 

> We've seen some crazy grade systems but this is probably the craziest.

Well, there are probably thousands of traverses only in Font. And unluckily, this practice is common also in other places. In topos, it is often written as "FB 7a+ trav." But I think you have a solid way of handling it, only the FB_trav system is currently missing ;-)

**Comment by brendanheywood** [comment] 2015-04-25 04:34
Ah, I've done a bit more research and in theory a traverse grade is long enough so it gets a grade in the normal french sport system. This is actually fairly sane. I just checked a few FB trav grades using our conversion table and this mostly matches up to the french sport system. 

So some options:
* without doing anything we could force the French sport system just using FR: for the traverses. We could then automatically show any forced French sport grades on Boulders with a 'trav' suffix, but I'm not sure that's a safe assumption. We could even detect a FR grade and swap the style to 'Traverse' magically. But this magic is a little like the 'Trad + x bolts = Mixed' magic which I regret as it's caused a lot of confusion and isn't obvious to editors.
* we could mark those routes are sport, which is lame but would work from a grade perspective 
* If it turns out that the FB trav grade has diverged from the FR route grade then a new system would make sense. We would get just about everything we need by just using TRAV:7a+ with the existing system parsing, which is slightly different to '7a+ trav' but close enough to be obvious to editors and users. We would not make it a default system in the French context on purpose so it showed up in the grade.
* If it hasn't diverged from FR we could invent a new style of 'Traverse' to go between 'Sport' and 'Boulder'. In this we'd map the Traverse type to the French route system instead of FB system. Even in Australia some really long boulder problems like in hollow mountain have been given route grades for similar reasons. Traverse would have to get included in boulder stats and searches.

None of these options jump out as clearly superior, all have downsides. Probably the last is the cleanest semantically, it is the style of the route which is sufficiently different to warrant a different grade system in real life. It is only a few thousand routes but I guess that's still more routes than the number of via ferrata, ice and alpine which we deal with.

**Comment by brendanheywood** [comment] 2015-04-25 04:40
Some references with comparison tables:

http://www.dpmclimbing.com/articles/view/bouldering-there-and-back

http://italiaoutdoors.com/outdoors-italy/bouldering-italy/618-boulder-difficulty-rating-chart-bouldering-italy

**Comment by scd** [comment] 2015-04-25 04:48
New system, parsing 7a+ trav before 7a+ for French and font context.

**Comment by birgander2** [comment] 2015-04-25 13:01
I am really not an expert in the traverse grades, but I always heared that they are somehow in between Font boulder grades and French route grades. That would mean it has diverged from the FR route grade. But again, I don't know, some hints from a Bleausard could clarify...

**Comment by brendanheywood** [comment] 2015-04-25 13:10
The consensus seems to be making a new FB_TRAV system which means it doesn't matter if the grades have diverged as long as that divergence is well defined somewhere.

@scd on a side note, is there an outstanding reason why we still need the Font context? Or is this considered deprecated and we just need to do a bit of data cleanup and migration in order to remove it?

**Comment by scd** [comment] 2015-04-25 22:45
From memory Hong Kong had some wierd usage of French, Font and UK grades which meant we needed to explicitly set Font in some places.

**Comment by brendanheywood** [comment] 2015-04-27 11:53
We need to batch fix up Hong kong too:

http://www.thecrag.com/climbing/hong-kong/hong-kong-island/area/12484843

**Comment by scd** [comment] 2015-09-08 00:28
This is a massive discussion of multiple issues. It is way to diverse to resolve as a single issue. I have just spent some time separating all the issues so they are manageble descrete chunks. Please let me know if there is something in this discussion which is not covered elsewhere.

Therefore I am closing this issue. Remaining tasks should be managed on their separate issues. Please feel free to add to this discussion or create new issues.

**Closed by scd** 2015-09-08 00:28 UTC
Labels: Feature: Grades
