### ISSUE TITLE
Re-Parenting: User interface enhancements, show node type

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3173] opened 2018-05-13 16:52 UTC
**What happened?**

When re-parenting it is impossible to see what node type you select (see screenshot). In case you have annotations, routes or sub-areas in the list it is impossible to identify them resulting in errors (e.g. can not re-parent itself) or wrong selections.
<img width="525" alt="screen shot 2018-05-13 at 10 46 54" src="https://user-images.githubusercontent.com/19162952/39969613-a2cb07d6-569b-11e8-9c60-cc06fcfed2c8.png">

**What you expected:**

Add another column showing the node type (e.g. route, annotation, area) in the selection screen.

**Comment by brendanheywood** [comment] 2018-05-15 00:45
I would go one step further and add the description, or the first line of the description of each area / routes and possible other details like grade or height. Some areas have good route details but poor names

**Comment by Mdemaillard** [comment] 2020-03-29 22:08
duplicate of #2232

**Closed** 2020-04-14 08:47 UTC
Labels: 5: Enhancement, Area: Reparent/Merge
