### ISSUE TITLE
node area stats # of topos not correctly calculated

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3072] opened 2018-02-24 08:39 UTC
**What happened?**

https://www.thecrag.com/climbing/france/fontainebleau/area/14018467

![image](https://user-images.githubusercontent.com/187449/36652206-6150735c-1b01-11e8-9be9-7120d21d5c24.png)

-1 topos are displayed for sub-node "off-circuit". In fact, this happened after I moved the only one topo in there to the main node.

**What you expected:**

number of topos = 0

**Comment by brendanheywood** [comment] 2018-04-22 13:33
Probably the same root cause issue:

https://www.thecrag.com/climbing/brazil/minas-gerais/area/500912274

Photos says -6 ?!

![image](https://user-images.githubusercontent.com/187449/39095526-6241313e-4685-11e8-84da-a5adf68f8cd1.png)

Photos page say 13:

https://www.thecrag.com/climbing/brazil/minas-gerais/area/500912274/photos

**Comment by Mdemaillard** [comment] 2020-03-14 18:39
both nodes posted above are now displayed correctly.
![image](https://user-images.githubusercontent.com/60388146/76688202-67428780-6633-11ea-991f-0408e8dd7f0a.png)

![image](https://user-images.githubusercontent.com/60388146/76688207-76c1d080-6633-11ea-8c65-85461c5124cd.png)

was there an update in stat calculation ? or just a refresh ?
I checked a few dozens area without finding issues.
candidate for closure

**Comment by scd** [comment] 2020-03-15 22:37
Generally there are three areas in the system where there could be apparent data integrity issues due to a form of caching:

 * Sometimes we duplicate data in fields in order to make the database more efficient. Occasionally there is a bug where that duplicated information is not updated when the master data is not updated. For example grade band is stored on the route as well as the grade, so sometimes the band can be different from the grade. This use case is a bug.

  * There is a stats database which stores all index stats for fast access to everything we need to operate   efficiently. This is update acsyncronosly (sometime after the update). Typcially you will see the stats update about 10 minutes after the data is updated. 

  * There are occasional bugs in the stats package which either the stats are miscalculated or the trigger to recalculate after an update is missing. This is kind of like the first case and is a bug.

  * There is a cache for nodes/accounts. Updates to any data associated with a node should reset the cache, but sometimes there are bugs and the cache is stale. If this happens the cache for the node/account will be reset within 2 weeks. There are some known edge cases where we have not been able to fix stale caches because the coding is really difficult (eg if you update an area all the descendants caches could be stale for some types of updates).

So it is really complex and sometimes issues are a mixture of problems.

**Comment by scd** [comment] 2020-03-15 22:38
Please close if you think this is done

**Comment by Mdemaillard** [comment] 2020-05-20 17:55
For your explanation on point 3 - missing recalculation. 
I guess there can be a lot of individual bugs, edge case situation (whichever component disconnected or crashed at the wrong moment). So trying to catch them all will never end.
Are count errors like these corrected over time, or maintained over time ? 

If an event triggers an increment/decrement of a value, then the error will be maintained over time.
If an event triggers a reocunt (which would be more expensive in ressource), then an error will be erased the next time an event is triggered.

**Comment by scd** [comment] 2020-05-20 22:43
Stats have a delta and baseline mode. Updates to the database mostly trigger a delta change to the stats so further user updates will not erase the error. We do schedule baseline recalculations, which means the stats will be corrected systematically at some point, however this could be a while.

**Comment by Mdemaillard** [comment] 2020-05-21 11:49
Interesting. We cannot close the issue, even if it will not be on the priority any time soon, because we have had multiple reports of that kind, and lots of occurrences are still visible to users, which don't correct easily with crag update or cache reset.
We can channel all reports and comments here with your explanation.

**Comment by scd** [comment] 2020-05-21 11:53
Sounds like it will save work, so I approve of the idea.

**Comment by rouletout** [comment] 2021-01-03 09:21
The wrong stats above are gone - closing despite the suggestion. Log new issues if this occurs again.

**Closed by rouletout** 2021-01-03 09:21 UTC
Labels: 2: Bug fix, Area: Statistics
