### ISSUE TITLE
Norwegian/scandinavian grades seem to be a bit off

### ISSUE THREAD

**Issue by scd** [theCrag/website#2278] opened 2016-07-24 06:29 UTC
Hey! I've noticed the Norwegian/scandinavian grades seem to be a bit off on the conversion table used by thecrag. The most accurate table I've found for the scandinavian (the swedish and norwegian systems are effectively the same) system is this one from 8a.nu. I currently climb in Norway and sweden and use thecrag to log my ascents, so it would be excellent if it fit in better with the climbs I've done in other parts of the world!

**Comment by Mdemaillard** [comment] 2020-06-04 17:05
Duplicate of #1004

**Comment by Mdemaillard** [comment] 2020-06-04 17:05
closing since 1004 was reopened conerning this topic, and has more data and latest user feedback

**Closed by Mdemaillard** 2020-06-04 17:05 UTC
Labels: 2: Bug fix, Feature: Grades
