### ISSUE TITLE
Massive explosion of browse history

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#4165] opened 2022-12-28 19:52 UTC
Hey guys, I just experienced strange behaviour. No idea if it is related to the performance issue but may be it is a hint.

I opened the index entry for a [route](https://www.thecrag.com/en/climbing/italy/finale-ligure/rocca-dellorera/route/14131213) from link provided by an [stream event](https://www.thecrag.com/event/7007547522). Then I wanted to go back to the previous page but nothing changed. Then I had a look at my browsers history and got that:

![grafik](https://user-images.githubusercontent.com/1528540/209586878-c167b774-7333-449c-8282-9d44d3953aac.png)

Either this is a firefox bug or the website redirected my browser more than 30 times to the same page. I'm sorry but at the moment I have no idea if that is something on my side. I tried to reproduce the issue but did not see that much history entries again.

Opening the [route page](https://www.thecrag.com/en/climbing/italy/finale-ligure/rocca-dellorera/route/14131213)  from the [stream event](https://www.thecrag.com/event/7007547522) again created this:

![grafik](https://user-images.githubusercontent.com/1528540/209587162-47f6bb3b-6b41-46cf-bd8e-36edf21eb701.png)

I expect to have just one history entry, because I just clicked once and waited until the browser stopped indicating progress.

_Originally posted by @lordyavin in https://github.com/theCrag/website/issues/3976#issuecomment-1365494441_

**Comment by lordyavin** [comment] 2022-12-28 19:55
Got it again. This time on iPadOS using Firefox.

**Comment by quaestor** [comment] 2022-12-29 13:34
Can confirm.

![image](https://user-images.githubusercontent.com/54371/209961222-5c29b820-0589-4677-80c3-d4caeb59d376.png)

This is from just a single click on a route from the dashboard.

**Comment by quaestor** [comment] 2023-01-04 13:54
This bug sometimes brings the browser on my phone to its knees, and I even had to close frozen tabs on my desktop PC quite a few times now due to it.

**Comment by Arzorth** [comment] 2023-01-05 23:39
Same problem here, including the frozen browser (chrome on iOS)

![651D8988-2E55-4417-AF94-17B46C551E40](https://user-images.githubusercontent.com/17315806/210900522-4ed56ff8-f028-4bc8-b654-cae398c97760.png)

**Comment by lordyavin** [comment] 2023-01-06 10:36
BTW what do you guys mean with "frozen"? Is the UI completely blocked? No tab switches possible, reload or something else?

**Comment by Arzorth** [comment] 2023-01-09 10:53
> BTW what do you guys mean with "frozen"? Is the UI completely blocked? No tab switches possible, reload or something else? 

What I mean is that the browser interface buttons didn't work (new tab, view open tabs, go back...) and I had to close the app and open it again.

I could not reproduce it today but the history explosion is easily reproducible. (I made a video but it fails at uploading)

Regards,

Jose Maria

**Comment by nicHoch** [comment] 2023-01-09 11:05
we found the issue and it will be fixed with next release

**Comment by lordyavin** [comment] 2023-01-09 11:14
> we found the issue and it will be fixed with next release 

And what is the cause. Please let us know.

**Closed as completed** 2023-01-21 21:32 UTC
Labels: 2: Bug fix, Area: Navigation, 2: Regression

**Comment by lordyavin** [comment] 2023-01-23 07:55
Please be more transparent. When will be the next release? Is there any roadmap?

**Comment by Arzorth** [comment] 2023-01-23 08:13
I tried it yesterday and it looks it is already fixed, but it is true that we would appreciate more details.
