### ISSUE TITLE
allow multiple tick types eg solo + fa, break type into flags

### ISSUE THREAD

**Issue by cgome** [theCrag/website#1217] opened 2013-09-08 05:46 UTC
User suggestion (support email):

When you log the ascent type (redpoint, flash, solo etc) it might be a good idea to have a couple of drop down boxes of the choices as opposed to all the options in one.
I mean this because I often have to choose between logging a flash or a first ascent. I put up alot of problems and with alot of them, they are flashes but also first ascents. I don't really like having to choose one OR the other... Today I put up a route that I solo'd onsight... So Onsight, solo, FA... I could only log as one of the three..

Not sure if it could be implemented with a 2 drop down box system (take a look at the UKclimbing.com logbook to see what I mean. I can send screenshots if it helps) but just food for thought.

**Comment by brendanheywood** [comment] 2015-07-14 06:04
Some outriders to test the model:

* Top rope a boulder problem (often for highballs)
* Trad lead a sport route (green point)
* Trad lead a DWS
* Aid an established trad route
* Trad climb an established aid route
* Onsight on top rope at a  gym

An attempt at finding all the dimensions of an ascent, ideally each dimension would be independent but that clearly isn't going to be the case. Many of the dimensions are continuous but generally fall into discrete steps, I've made what I think to be a pragmatic mapping each onto at most 3 levels for each dimension.

Context | Dimension | Purest | Middle | Less pure | Example
--- | ---- | ----- | --- | --- | ---
Route | History ascents | No FA | attempted before | done before | Onsight vs FA
Route | Fall Consequences | Death | Injury | None  | Solo vs DWS
Route | Permanent pro | None | - | Sport
Climber | Personal Attempt | First | attempted before | done before | Onsight vs redpoint
Climber | Knowledge | none | onsight | Beta or prior attempt | Onsight vs flash
Ascent | Completion | Complete | - | Retreated | Working / Retreat
Ascent | Level of protection | None | Self placed | Preplaced | Red point vs pink point
Ascent | Means of ascent | Free |  Rested / fell  | Aid | Tick vs dog
Ascent | Permanence of pro USED | Temporary no damage | Temp but may damage | Permanent (sport) | Red point vs green point
Ascent | Means of belay | Self | From below |  From above  | 

The context determines where we source the info from in order to potentially limit the choices in each dimension. Now I do not think that the best UI is giving all of these as options to the ticker, some of these can be inferred or at least defaults based on the various contexts. ie if we didn't complete the route, do we really care about whether we place the gear or not, or if it was lead or top roped?

Obviously there are some dependencies between dimensions, ie it doesn't make sense for you to be climbing 'virgin' rock yet there is permanent protection. I've tried to list the dimensions in dependency order, so answers to the first questions might remove choices in later dimensions. In particular:
* Route pro - if not sport then can't 

Ideally once this is all sorted we should be able to turn each dimension into a facet filter, the 'route' one's we should already have in some form already.

In terms of UI, I don't think what we have is particularly bad and doesn't need a radical make over. Just because some more esoteric combinations of the above are possible doesn't mean we should add them add make the UI worse for no reason. So I'm thinking that this is mostly an under the hood set of changes which will allow us to more easily filter / suggest the list of tick types based on the route, route history, and the climbers prior ascents. If we really want to give people the fine grained ability then we'd simple have an 'other' tick type which opens up the fully gory details. That could also be a neat way of giving them a very small list of tick types in some contexts, ie for a boulder only give then 4-5 options and the rest under 'other'.

**Comment by scd** [comment] 2015-07-14 06:15
I think we need to do a gap analysis?

**Comment by scd** [comment] 2015-07-15 01:43
Here are is the current list of tick types:

 * General ascents
    * Tick
    * Clean
 * Lead ascents
    * Lead
    * Onsight
    * Flash
    * Red point
    * Pink point
    * Dog
    * Lead Solo
 * Seconding ascents
    * Second
    * Second clean
    * Second with rest
 * Soloing ascents
    * Solo
 * Top roping ascents
    * Top rope
    * Top rope onsight
    * Top rope flash
    * Top rope clean
    * Top rope with rest
    * Roped Solo
 * Aid ascents
    * Aid
    * Aid solo
 * Historical ascents
    * First ascent
    * First free ascent
 * Attempted ascents
    * Attempt
    * Working
    * Retreat
    * Ghost
 * Aspirational ascents
    * Target
    * Hit
    * Mark

**Comment by scd** [comment] 2015-07-15 02:25
Gap analysis of what needs to change:

 - [ ] Aspirational ascents will become part of generic lists
 - [ ] Historical ascents will become the FA route info so will go. Although an extra status field will tie the ascent to the FA record of the route.
 - [ ] Keep Tick as a catch all
 - [ ] Clean and Lead ascents are used as a statistical grouping, but not required to be selectable.
 - [ ] Add Green Point to what is currently in the Lead ascents group.
 - [ ] Merge 'Lead ascents' to 'General ascents' to be more inclusive of various route types (boulder and DWS). Lead applies to sport and trad routes, but you can also onsight a boulder or dws. 
 - [ ] Merge 'Soloing ascents' with 'General ascents' for reasons as for Lead ascents.
 - [ ] Add Onsight solo
 - [ ] Add a repeat flag. For some tick types this is implicit (eg Onsight), but others it is useful to make this explict (eg Red point). The first time you do a Red point of a route you are working is a different experience to repeating a route you have done before.

Leave aid, top roping and seconding ascents as is.

I think we can leave some info for the ascent comment field. For example if you trad lead a sport route. 

Review availability of each tick type with each route gear style and gym routes.

**Comment by scd** [comment] 2015-07-15 02:35
@brendanheywood I have limited bouldering experience. Do people onsight boulders, tick them, send them, solo them?

**Comment by birgander2** [comment] 2015-07-15 07:03
Boulder. basically only flash and send. Onsight is possible but it's not really common to call it like that. Maybe toprope, but there is already a toprope group. Generally, I would not reduce the list according to the ascent style but to leave it to the climber what to select. The current subgroups are quite a good solution.

And don't forget to include "bobpoint": a very common style of ascent in which an ascent is not actually made. It is merely enough to claim that you were (easily) capable of doing the route, but having excuses like: “too tired” “too late” “too hot,”. Important component is not to touch any hold, if you did you'screwed the bobpoint. Usually done at grades much higher than you redpoint level.

**Comment by brendanheywood** [comment] 2015-07-15 07:34
I think that's quite a regional thing: I onsight boulder problems all the
time and everyone I know calls it that.

The words I hear commonly used are:

Onsight
Flash
Send (same as red point, I've used red point when logging)
Tick (send or repeat)
Attempt / working (same difference as climbing, whole route vs just some
section)
Dab (if you're foot brushes a mat, or you kick a spotter while dynoing
which can be enough marginal difference to send when you perhaps would have
fallen)

It's very common if you dab to get heckled to do it again properly

Sent from my iPhone

On 15/07/2015, at 5:03 PM, Anderl <notifications@github.com> wrote:

Boulder. basically only flash and send. Onsight is possible but it's not
really common to call it like that. Maybe toprope, but there is already a
toprope group. Generally, I would not reduce the list according to the
ascent style but to leave it to the climber what to select. The current
subgroups are quite a good solution.

And don't forget to include "bobpoint": a very common style of ascent in
which an ascent is not actually made. It is merely enough to claim that you
were (easily) capable of doing the route, but having excuses like: “too
tired” “too late” “too hot,”. Important component is not to touch any hold,
if you did you'screwed the bobpoint. Usually done at grades much higher
than you redpoint level.

—
Reply to this email directly or view it on GitHub
<https://github.com/theCrag/website/issues/1217#issuecomment-121510960>.

**Comment by brendanheywood** [comment] 2016-08-10 23:41
Some thoughts about the FA tick type, I think medium term we should deprecate it completely and eventually remove the tick type itself. This data should go into the FA field of the route, and we probably need some extra logic in the streams or ticks to show this data in a similar way to how we currently do. When migrating the FA tick type we'd convert it to a generic 'Tick' and try to auto fill the FA field of the route but with lots of sanity checking, ie if the FA field is already filled out then ignore it, or if the dates are more recent then ignore it. We'd need to do some prototyping for this to check the heuristic as it might just not be feasibly. In which case we'd not internally remove the tick type but not make it available from the gui any more??

**Comment by MelwinQ** [comment] 2016-09-21 19:07
I am not sure if I correctly understand the subtleties of the "attempt"-tags. However, I would like to record if I failed at route while leading or while seconding.

**Comment by brendanheywood** [comment] 2016-09-21 23:58
Have you read through this page?

https://www.thecrag.com/article/TickTypes

Note we are reviewing this and will in a couple months roll out some new tick types and probably remove some, and also filter them to the appropriate ones for the style of climbing when you are ticking routes.

**Comment by MelwinQ** [comment] 2016-09-22 06:28
Indeed, I had consulted this page. But still I cannot see the difference between
a) "I attempted, but did not complete, this route." and
b) "I attempted this route but retreated [...]"
Does it mean in case a) I did not retreat but am still bivouaqueing in my portaledge while logging the ascent, hoping to complete tomorrow, whereas in b) I have already given up? But then c)  "I am working on this route or problem as a personal project." might be the better choice for the first case?
Never mind, I just wanted to express that for me these descriptions don't clarify much. I am courious to see the upcoming changes.

**Comment by johnpitcairn** [comment] 2017-03-23 05:08
Hi, I read through the spreadsheet, couple of comments:

Greenpoint would be worth making available to trad routes as well, there are plenty of routes classified as trad that have some bolts or pitons, ie "mixed". I know some would argue it isn't a greenpoint unless you also chop the bolts/pitons, but that's a fairly contentious stance.

I do quite like "Lead with rest" as separate from "Hangdog". Hangdog is a fairly derogatory thing in my book, I see a lot of gym climbers dogging from bolt to bolt and claiming the ascent. Dangle and thrash. But if I have one rest on a #2 RP at the crux, is that also a hangdog?

Lead solo and free solo are different things. Lead solo should not be renamed to free solo, it is rope soloing on lead with a ground anchor. The separate Solo category should remain with just "free solo" in it, or you could move all the other solo ticks in there:

Free solo
Lead solo
(Top) rope solo
Aid solo

Depends what you consider to be the main characteristic of a solo ascent I guess. Does a gym autobelay count as solo?

**Comment by Drazhar** [comment] 2017-03-23 05:45
Hey,

IMHO too many tick types are confusing for the most people. Right now there are already a lot of types and you have to scroll quite far to get for example to attempt.

Lead with rest is a hangdog. It doesn't matter if you rest 1 or 100 times, it's always no clean ascent, why differentiate?

**Comment by johnpitcairn** [comment] 2017-03-23 05:47
If you're resting on a #2 RP there sure as hell is a difference ;-)

**Comment by DaneEvans** [comment] 2017-03-23 05:53
Agreed. At the very least there needs to be a commonly used at the top so we don't see the ones that we don't, and likely will never use. 

I use about 6 tick types. 
Onsight, red point , dog, attempt, solo and tick (probably should use clean looking at that list). 
I'd be surprised if many people had more than 10 that they used regularly( or ever), which is a lot nicer to scroll through than the full 30

**Comment by johnpitcairn** [comment] 2017-03-23 05:55
Could the "Ascent types" be broadened but made part of the user settings, so that if you don't want to see greenpoint or lead with rest or aid or whatever when logging ascents, you can customize the ascent type menu?

**Comment by brendanheywood** [comment] 2017-03-23 05:55
Everyone, one of the main aims of the new tick types is to actually reduce the number of tick types per climb type, so while the number of tick types will be increased and be more reflective of real life, the number of tick types in the drop down will be reduced and will also be re-ordered to better reflect the most common ones that people actually use

**Comment by Drazhar** [comment] 2017-03-23 05:58
Same for me, but I use a bit more: Onsight, flash, red point, pink point, dog, toprope, attempt. Sometimes even toprope clean.

I think the problem is to get rid of types without annoying people :D

But if we are talking about, what is the difference for the climb if I toprope or second a route? Just the position of the partner changes, which shouldn't influence the difficulty for me. Also some "attempt" categories could be removed.

**Comment by brendanheywood** [comment] 2017-03-23 06:00
> Lead with rest is a hangdog

There is lots of cultural issues here which are not consistent globally. Some people distinguish between a 'clean lead with falls' vs a hangdog, ie you fell but got back on at the same place and did every move clean, vs pulling on gear. There are subtle distinctions with many of these things which are definitely not universal. Even the use of red point vs pink point is not consistent worldwide which is a bigger issue.

Our golden rule is to match reality, so if enough people want something we will add it, the trick is just not cluttering it up for everyone else

**Comment by brendanheywood** [comment] 2017-03-23 06:04
> Also some "attempt" categories could be removed.

agree

Also not everyone will have seen it, this is the working document we are referring to:

https://docs.google.com/spreadsheets/d/1HhDomfKxrARGdxMSAyJGQ0nywYLSWF5OShdsyMGLaLE/edit#gid=0

**Comment by johnpitcairn** [comment] 2017-03-23 06:06
> what is the difference for the climb if I toprope or second a route?

Lots. Seconding sport, you need a hand free to clean the draws. Seconding trad routes can be harder than leading. I've seconded trad routes that required me to get 2 hands free to clean the gear, when the leader placed and set it one handed.

**Comment by johnpitcairn** [comment] 2017-03-23 06:07
> the trick is just not cluttering it up for everyone else

Sounds like a user setting to me.

**Comment by brendanheywood** [comment] 2017-03-23 06:09
> Seconding trad routes can be harder than leading

Yes when we've run the stats it has confirmed this same suspicion, some seconds are definitely harder than a top rope 

> Sounds like a user setting to me.

As a general philosophy I like to avoid more user settings, it just results in things that never get discovered or used. I think the key focus here is on making the common tick types at the top of the list

**Comment by johnpitcairn** [comment] 2017-03-23 06:11
I think perhaps "retreat" should only be applicable if the route is more than one pitch? Though that does beg the question of what happens if you want to bail when you are 40m up a 60m route with only one 60m rope...

**Comment by johnpitcairn** [comment] 2017-03-23 06:20
> As a general philosophy I like to avoid more user settings, it just results in things that never get discovered or used. I think the key focus here is on making the common tick types at the top of the list

Sure, but make the common types the default and allow users to hide/unhide/rearrange tick types as a user setting. I really hate "hangdog" for use on trad routes, it's a sport term. Though I did see somebody do exactly that the other day at Mt Eden quarry ;-)

**Comment by Drazhar** [comment] 2017-03-23 06:30
> Lots. Seconding sport, you need a hand free to clean the draws. Seconding trad routes can be harder than leading. I've seconded trad routes that required me to get 2 hands free to clean the gear, when the leader placed and set it one handed.

Oh, I remove the draws/gear on 95% of my toprope ascents, because the most time I toprope something is after my partner and then I clean the route during the ascent. I always thought that second means in a multipitch if my partner is belaying from above :)

But yes, toprope and second dont really matter to me, I just use them to get an idea what I have climbed this day. Also for hangdog I thought this always means to clean climb each passage, if you don't then it should be aid or attempt?

**Comment by birgander2** [comment] 2017-05-17 11:20
An tick type which is missing imho is "A.F." / "all free" sometimes also denoted "red circle". This is somehow the similar to "hangdog", but meaning that you have climbed clean, didn't pull on gear, didn't use rope drag, but rested on bolts. This type of ascent is, for example, a valid ascent in [Sächsische Schweiz](https://www.thecrag.com/climbing/germany/sachsische-schweiz). In fact, some routes there even have two different grades, one (optional) for redpoint and one (standard) for AF ascents. Ring anchors are rare there in most routes, so it's trad with few bolts. AF is also quite common in more alpine ascents.

Currently, I have to use "tick" for such an ascent.

**Comment by brendanheywood** [comment] 2017-05-17 11:33
* [ ] Yes "all free" has been discussed in this issue and in other places but under various names such as "clean with rest". I didn't know about the red circle though which is good to know.

Can you provide any references to definitions elsewhere so we can get some consensus on the best name to use? It would be good to get a feeling for if it is called different things in different countries (even in English) and where it tends to get commonly used.

**Comment by birgander2** [comment] 2017-05-17 14:14
I found only [German sites](https://de.wikipedia.org/wiki/Begehungsstil#a._f.) describing a.f., so I assume it's more a German thing. However, as mentioned, quite relevant / default in Saxony. And I think I was wrong with the red circle, this seems to refer to the (american) yoyo-style. Or maybe both.

Red cross seems to be user for toproping without rest (didn't know that)

Greenpoint would be an important addition (getting quite popular), but this is mentioned before.

**Comment by scd** [comment] 2017-05-28 08:05
@brendanheywood I have added some tick types in my dev and filtered by route gear style when logging ascents. The filter is configured in code so we can play with it if we need to. The driver here is getting boulder ticks clearer.

Boulder tick:

![tc-tick-type-boulder](https://cloud.githubusercontent.com/assets/373058/26527108/2afc82c2-43d0-11e7-925d-a37b9ff8551c.png)

Sport tick:

![tc-tick-type-sport](https://cloud.githubusercontent.com/assets/373058/26527109/322445d0-43d0-11e7-818a-fd2b2f08accc.png)

It will be a while before this makes it's way propery to public dev.

**Comment by birgander2** [comment] 2017-05-29 06:18
Just a comment: "All free" certainly should be without fall, but with a rest. Otherwise it would be an (unsuccessful) attempt.

**Comment by brendanheywood** [comment] 2017-05-29 12:44
Ok looks good. I'd move Dab below Send. Is there also scope for re-ordering the groups dependent on geat style? If so I'd move all the top rope stuff and general ticks below for boulder so it is just Bouldering ascents, Attempted ascents, Top roping, General.

**Comment by scd** [comment] 2017-05-29 22:42
@brendanheywood I will look into making those changes. One think I want to get to the bottom of is the 'all free' tick, which we have said is 'all free with fall', but there is a suggestion it should be 'all free with rest'. Should there be two separate tick types, should we change it to 'all free with rest' (which actually makes more sense to me, but in my view is still a hang dog) or just change it to 'all free'.

**Comment by brendanheywood** [comment] 2017-05-30 00:01
Does "all free with fall" exist at all or have we accidentally made that up in this discussion?

**Comment by rouletout** [comment] 2017-05-30 00:10
I don't know that and I think this is hang dogging

**Comment by scd** [comment] 2017-05-30 00:21
It was an outcome of our discussion. 

https://docs.google.com/spreadsheets/d/1HhDomfKxrARGdxMSAyJGQ0nywYLSWF5OShdsyMGLaLE/edit#gid=0

It was late. I think we originally had 'All free (with fall)' and I just removed the brackets for implementation. I never understood the 'all free' tick type. Whether it is a 'rest' or a 'fall' it makes no difference to me.  But I guess there is a similar concept in bouldering with a 'Dab'. In otherwords, I almost did it properly.

Just because I would never log an All free ascent, it does not mean others would not want to log this.

Now that we have unleashed this tick type in implementation I need an outcome to this discussion.

**Comment by brendanheywood** [comment] 2017-05-30 01:04
I think "All free (with fall)" is a complete dud and it should only be "All free (with rest)" and we just missed this subtlety internally when discussing it. I've finally figured out the google foo and now found a whole bunch of references to this, searching for "alles frei" is much more useful than "all free":

> RP VIIIa : Still another unique aspect of Saxonian climbing is the af (from alles frei or all free) style. Here it is valid and considered good climbing style to rest at each ring. Normally all grades are given for the af-ascent. However, climbing certain routes without any stops increases their difficulty. In this cases the RP (from rotpunkt or redpoint) grade is added to the af grade.

https://elllocesaqui.wordpress.com/tag/saxony-climbing-grades/

> The climb is then rated 'a.f.' which means 'alles frei' (all free). In destinction to redpoint 'a.f.' allows resting at the rings/bolts (there are not much of them in Saxon routes, if any since this is a trad area). 

http://www.rockclimbing.com/forum/Climbing_Disciplines_C6/Trad_Climbing_F20/Does_a_shoulder_stand_count_as_free_climbi_P1297085/

> Bei einer a.-f.-Begehung (a. f.: alles frei oder all free) darf an den Sicherungspunkten geruht werden. Nach dem Ruhen muss aus der letzten Kletterstellung weiter geklettert werden, die der Kletterer innehatte, bevor er sich am Haken ausruhte. a. f. ist vor allem im Elbsandsteingebirge gebräuchlich und per Regelwerk anerkannt.[2] In den anderen Klettergebieten ist es als historischer Begehungsstil bekannt, wird jedoch nicht als Begehung anerkannt, sondern ausschließlich zur Vorbereitung für die spätere Begehung in einem anerkannten Stil benutzt.

Or auto translated:
> In the case of an a.-f.-walk (a. F .: all free or all free), the fuse points may be dealt with. After resting, the climber has to climb further from the last climbing position, before he has rest on the hook. A. F. Is mainly used in the Elbe Sandstone Mountains and is recognized by regulations. [2] In the other climbing areas, it is known as a historical walk, but it is not recognized as an excursion, but is used exclusively for the preparation for the later visit in a recognized style.

https://de.wikipedia.org/wiki/Begehungsstil#a._f.

**Comment by birgander2** [comment] 2017-05-30 06:39
Yes, with fall it is a fail, there should be only all free (with rest).

To give you some more context: In Saxony, the majority of the grades are a.f. grades, only few routes have an (additional, harder) redpoint grade. This is a bold trad climbing area, intermediate ring bolts are rare and typically only present if no natural protection is possible. Natural pro is only on slings and knots, no friends, nuts, etc. For first ascentionists it is mandatory to place ring bolts on lead(!), so you might understand the idea of a little rest. After resting, you have to restart in the prior climbing position. If you fall, weight the rope, etc., it is a fail. Maybe watch [this](https://youtu.be/gLQtytqJ_KM) or the movie "The Sharp End" to see it live. In fact, the climbing ethics in Saxony are pretty strict, just a bit different to the rest of the world (but hey, this is widely considered to be the birthplace of modern sport climbing).

The only problem I see if people start using a.f. in other sport climbing crags, because on an abstract level, a.f. and dog is of course the same.

**Comment by brendanheywood** [comment] 2017-08-14 14:23
I'm thinking this epic issue can be closed off too. Everything unfinished has it's own issue, and the internal flag concept I don't think matters any more.

**Closed by brendanheywood** 2017-08-14 14:23 UTC
Labels: 10: Common support issue, 3: Mostly done, 5: Enhancement, Area: Logbooks Ticking & tick lists

**Comment by brendanheywood** [comment] 2019-09-27 07:17
I don't want to lose the analysis done in this issue so I've moved it here:

https://docs.google.com/spreadsheets/d/1HoNp90LYJnLGzNWTiSJWR63ymlChjK3Eda95NHuQaz8/edit#gid=0

This is public and anyone can comment on it
