### ISSUE TITLE
Chat Comments

### ISSUE THREAD

**Issue by lionelterray** [theCrag/website#794] opened 2012-10-05 23:59 UTC
enhancement request - 1. ability to edit and delete own chats  2. ability to move chats from route to general chat area (editors only privilege)

**Comment by brendanheywood** [comment] 2017-04-23 14:19
The first half of this is done in https://github.com/theCrag/website/issues/746, the second half is a duplicate of https://github.com/theCrag/website/issues/2441 so closing this one as dup (even though it's older)

**Closed by brendanheywood** 2017-04-23 14:19 UTC
Labels: Area: Forums & Messgaging
