### ISSUE TITLE
Presentation of Grade and Routes on Profile

### ISSUE THREAD

**Issue by Telefonzelle** [theCrag/website#3168] opened 2018-05-08 07:22 UTC
**What happened?**
When i choose a grade system at thecrag.com there is no change on my profile side. On my profile https://www.thecrag.com/climber/telefon I can see different grade systems. Besides UIAA, FB and Fr there is also a grade system with V0, V0+, V2 and so on. However,  I havn´t made a boulder in this grade system in the past.

**What you expected:**
Normally, I can choose for example FB, UIAA or FR grade system. Afterwards my collected routes should shown over timeline in the choosen grade. Furthermore I would like to know, why my "Boulder" Ascents (for example Tafelsteinkante 6A) are listed in "notable ascents" as Lead Ascents. I expect that Lead Ascents only contain Ascents of Sport and Traditional routes.

Thank you in advance,
Holger

**Comment by scd** [comment] 2018-05-08 07:31
There are a few components of the profile page which have not been updated yet from recent changes. We need to find some time to do further work on the profile page.

**Comment by lordyavin** [comment] 2018-05-09 05:57
+1

**Comment by brendanheywood** [comment] 2018-08-15 03:07
Closing this as a duplicate of https://github.com/theCrag/website/issues/2860

**Closed by brendanheywood** 2018-08-15 03:07 UTC
Labels: Area: Climbers / Profile, Feature: Grades, Social
