### ISSUE TITLE
Robust process for deleting nodes

### ISSUE THREAD

**Issue by scd** [theCrag/website#1238] opened 2013-09-26 02:30 UTC
- [ ] need a process to deal with the node graveyard.
- [ ] need to change status to deleted rather than removing the node from the database so that it works properly with a callback system
- [ ] need a mechanism to inform apps that the index structure has changed to remove deleted nodes. Actually quite complex and relates to reparenting and needs to fit in with any methodology we choose for syncing apps without getting the whole index.
- [ ] UI must be able to delete stuff at admin level with appropriate warnings about what other data is associated with that node, and a note on how the data is going to be dealt with.

The trigger for all this work is the app syncing.

**Comment by brendanheywood** [comment] 2017-08-20 02:35
Deleting this as a duplicate of https://github.com/theCrag/website/issues/1011, I've copied over the todo list

**Closed by brendanheywood** 2017-08-20 02:35 UTC
