### ISSUE TITLE
Facet filters 'is multi pitch' vs 'has pitches'

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3104] opened 2018-03-07 10:51 UTC
**What happened?**

![image](https://user-images.githubusercontent.com/187449/37088443-7b4eae3e-2251-11e8-982b-1cc822af47b8.png)

Two flags that appear to be the same, but seem to do different things.

**What you expected:**

I would probably say we keep them both, but make
* [ ] 'is multi pitch' filter on the pitch count field
* [ ] 'has pitches' filter on the grade and height breakdown field and tweak the language slightly

**Comment by brendanheywood** [comment] 2018-03-07 10:55
ah maybe this is already doing exactly what I want...

https://brendan.thecrag.com/climbing/north-america/routes/assert/has-pitch/?sortby=length,desc

vs

https://brendan.thecrag.com/climbing/north-america/routes/assert/is-multipitch/?sortby=length,desc

**Comment by brendanheywood** [comment] 2018-03-07 11:08
Hmm no there is something weird here, eg Calamari appears in both, but only has a number of pitches with no breakdown of either grades or hieghts. But other routes in or out of either list would suggest it's kinda half doing what I think it should

https://brendan.thecrag.com/climbing/canada/alberta/banff/route/846673752

**Comment by michaelwgnr** [comment] 2018-10-03 07:49
To me (pure user perspective) it looks like both work on the pitch count field, where "is multi pitch" shows all routes with pitch count >1 and "has pitches" shows all routes with pitch count >= 1.

Sorry to jump on this, but concerning searching for multi-pitch or single-pitch routes, I think it would be more helpful if one could actually search for a range of number of pitches (e.g. exactly 1 pitch or from 6 to 8 pitches). As it is right now, I can only search for multi-pitch routes (and not single pitch routes) and simple two pitch routes come up along huge 20 pitch monsters. When e.g. looking for a suitable route for a climbing trip, that behaviour is not really useful.

**Comment by brendanheywood** [comment] 2018-10-04 12:38
As a workaround in the mean time you can still sort by height. As well as having a range filter for height

**Comment by Mdemaillard** [comment] 2020-03-30 10:41
see #1769

**Comment by rouletout** [comment] 2021-01-03 14:25
closing as "is multi pitch" and "has pitches" works as intended and rest is covered in #1769

**Closed by rouletout** 2021-01-03 14:25 UTC
Labels: 5: Enhancement, Area: Multipitch, Area: Search and facets
