### ISSUE TITLE
Discussions labels as both private and public at the same time in streams / forums

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3263] opened 2018-09-05 13:16 UTC
**What happened?**

The discussion was a comment on a stream event. So it is a public one.
But  two labels are shown: public and private!

Example url(s) to reproduce the problem:

https://www.thecrag.com/discussion/1474128000/hallo-sam-danke-fr-deine-updates-es-gibt-schon-ein-niederbibb-hier-httpswwwthecragcomclimb

![grafik](https://user-images.githubusercontent.com/2226714/45094939-10deb980-b11d-11e8-95c8-feb01464f0f8.png)

**What you expected:**

* [ ] one correct label

**Comment by brendanheywood** [comment] 2018-09-18 02:36
@scd did you do anything here? I can't reproduce

**Comment by scd** [comment] 2018-09-18 04:50
No I have not done anything. I am wondering if it is different from Nicky's perspective because he started the discussion.

@nicHoch are the clashing labels still there for you. They are not for Brendan and I.

**Comment by brendanheywood** [comment] 2018-09-25 01:15
Another case, the raw event:

https://www.thecrag.com/event/2006460402

1) Kai saw the event, which is odd and the first bug, he should not have been able to see it and I'm not sure what context he saw it in (eg dashboard or node page) 

2) Then he commented on it and mentioned me. Bug 2: We should either not allow mentions for people who cannot see something, or the mention should be marked as non-invite (facebook does this as a greyed out name if you force it, and it does not autocomplete).

3) Bug 3: I then got this new discussion in my daily email, which leaked some of the comment title in the email. But when I click on the discussion I can't view it because it's private.

**Comment by brendanheywood** [comment] 2018-11-30 04:05
+1 from support query

**Comment by nicHoch** [comment] 2018-11-30 08:59
meanwhile only the public label is shown:
![grafik](https://user-images.githubusercontent.com/2226714/49279012-a1136d00-f486-11e8-9563-40937040cd8a.png)

**Comment by brendanheywood** [comment] 2018-12-01 12:38
This is a deeper issue that, that event is public, and the thread on the event is public, but the direct discussion url is not. Eg if you are not logged in you can not see this:

https://www.thecrag.com/discussion/1474128000/hallo-sam-danke-fr-deine-updates-es-gibt-schon-ein-niederbibb-hier-httpswwwthecragcomclimb

but you can see this:

https://www.thecrag.com/event/1474090323

Both should be visible and marked as public

**Comment by nicHoch** [comment] 2018-12-19 11:18
here an other example:

https://www.thecrag.com/discussion/2163073965/do-not-see-the-change-what-is-the-improving-update-suppose-the-gyms-have-been-moved-from-fichtelge

![grafik](https://user-images.githubusercontent.com/2226714/50217149-361fcc80-0388-11e9-99c6-3855919f803d.png)

**Comment by scd** [comment] 2019-02-18 07:26
Fixed event, but the same needs to be done for ascents, trips and photo discussions

![screenshot from 2019-02-18 18-24-51](https://user-images.githubusercontent.com/373058/52934506-c4292b00-33aa-11e9-8964-d2ccb615895a.png)

**Comment by scd** [comment] 2019-02-18 23:19
This is ready for release

**Closed by scd** 2019-02-18 23:19 UTC
Labels: 2: Bug fix, Area: Forums & Messgaging, Area: Streams / feeds
