### ISSUE TITLE
Missing navigation 'up' from topo

### ISSUE THREAD

**Issue by georg-d** [theCrag/website#3690] opened 2020-06-01 23:11 UTC
**What happened?**
On my mobile, I landed on a topo page like https://www.thecrag.com/climbing/germany/frankenjura/allersdorf/area/346143675/topo and did not find an easy way back to the main / overview page of the area. As most mobiles do only have a virtual touch keyboard (not _that_ nice to work with dirty fingers) and the Internet connection is sparse and/or slow at the crags (often none or 2G despite using 2 providers), it's not comfortable to start over from theCrag's home page.

**What you expected:**

Some link "back to area's overview" or "leave topos" or the like. 

An even more general and thus better alternative would be to introduce an "local/detail navigation" between the different "view points" for an area, so overview, photos, topos, weather,... making it easy to "rotate" between the different pages of an area. I can imagine that as tabs, be it including the visible boxes or without (similar to github - just scroll up).

**Comment by lordyavin** [comment] 2020-06-02 05:57
Just click/tap on index

**Comment by georg-d** [comment] 2020-07-28 13:55
Works fine.

**Comment by matozoid** [comment] 2020-07-29 07:12
I've also wondered how to get back from "locate" "topo" "photos" etc. This seems to be more of a UX problem.

**Comment by georg-d** [comment] 2020-07-29 11:18
@matozoid Do you think renaming "Index" to something else would have helped you? For me, I think yes, but I do not find a short & clear name: 
- "Crags hierarchy" is speaking but slightly long (think small mobiles).
- "Home" or "Front page" is not properly describing the link target. 
- "Crag", "Area" etc. are too specific, as the button may mean any of them - even if the name changes depending on what enity you're currently watching, when using a mouse, the pop-up-menu on mouse-over event does show regions, areas, crags, sectors etc.

**Comment by matozoid** [comment] 2020-07-29 19:13
Hmmm, I don't think a rename would help. Here's what I mistakenly try to do. Let's say I'm at https://www.thecrag.com/climbing/belgium/hotton/locate

Okay, I want to get back to the normal view, so I click on "Hotton" in the left list. That doesn't do anything. If I look at the top there is "Index" but it is underlined so it is not inviting me to click it. Not sure where I would end up anyway (top of the index? Index, Map, Climbers etc. are so much above the rest of the page that they seem to be high-level choices for the site,) I just want to go back to Hotton :-)

(For locate specifically I guess having a "Done" button that goes back, instead of a "Save" button that stays, would be a quick fix.)

Anyway, this is my input for a possible reorganization of the UI :-)

**Comment by killakalle** [comment] 2020-07-30 15:18
+1

I remember struggling a long time when I started using theCrag. I used to be quite confused about where I was in the navigation and how to get back to _normal_ view. And I've heard similar struggles from other people starting out.

"Normal" view - you are at 'Index' of a crag/sector. Index is underlined.
![image](https://user-images.githubusercontent.com/30682796/88920748-a46b8700-d26d-11ea-91cb-da90d7e993fe.png)

First confusion - you click "Edit location". When you're done editing, or simply want to get back, you are wondering how to get out of this. Index is already underlined (so not inviting to click it). But you need to click Index again to get back to "Normal view"
![image](https://user-images.githubusercontent.com/30682796/88920806-bf3dfb80-d26d-11ea-9e10-b36a07cd845f.png)

Second confusion - Topo editing. Same problem as described for "Locate"
![image](https://user-images.githubusercontent.com/30682796/88921175-5c009900-d26e-11ea-83e5-434054b68976.png)

**Comment by killakalle** [comment] 2020-08-16 23:15
Here's another one regarding topos that is a bit confusing:

The left side shows the topo editor. The right side shows photos filtered for topos.

What is confusing, is that they almost show identical breadcrumbs (topo vs topos). You wouldn't notice unless you compare them side by side.

On the left side, you can add additional topos, on the right side there is no such button.
![image](https://user-images.githubusercontent.com/30682796/90346047-0f66dd00-e026-11ea-9f8f-b64b667bd3a0.png)

In order to "reproduce" the right screen:

1. Click on "Photos"
1. Notice how "Photos" becomes underlined
1. Click on "Topos"
1. Notice how "Index" becomes underlined, although we are still in "Photos"

**Comment by georg-d** [comment] 2020-08-19 23:24
@killakalle & @matozoid: Do you think it would help at least a little to have 
1) "Index" a littled faded out and overlayed with a stronger text "Topos", "Locate" etc. and maybe a visualization (arrow, text size difference, or the like) that you're in a "sub page"? This would be visible on mobile, too.
2) The breadcrumb navigation (and similar in the left side navigation, i.e. sub entries like Hotton's sectors) not only showing "Hotton : Locate" leading to the page where you are, but instead "Hotton > Locate" where clicking "Hotton" leads to the 'main page of Hotton' and clicking "Locate" leads to the page where you are? Breadcrumb would be visible on mobile, too, but not left side.

**Comment by matozoid** [comment] 2020-08-20 09:25
I like idea #2

Now that I thought about it a little more, your original idea to rename "Index" is also a good plan, because it is a very fuzzy concept to me (possibly because I'm not native English speaking.) Isn't it just the "route list"?

Generally I think the overall layout is confusing: Index, Photos, Topo, etc, are all way too dominating for what seems to be different views on a crag. The crag list and the logo should be more to the outside, the views more to the inside.

**Comment by rouletout** [comment] 2020-08-24 08:01
Thanks for this valuable discussion - we will assess this issue with our UI team and come back with a proposal.

**Comment by rouletout** [comment] 2020-09-01 07:08
We have a proposal for the missing navigation up (eg once you are done editing topos or locations, etc.). We propose to intriduce a button called "Done editing" on top right. Any suggestions?

<img width="1138" alt="Screen_Shot_2020-08-31_at_4 10 54_PM" src="https://user-images.githubusercontent.com/19162952/91813226-a93ba600-ec32-11ea-86a3-c44ae55cff28.png">

**Comment by matozoid** [comment] 2020-09-01 08:50
That image shows an interesting inconsistency: "Wild Iris Locate" goes on top of the crag list, while the "Wild Iris" index page is to the right of the list. In my opinion everything related to what is selected in the list should be to the right of the list.

Is Index going to be renamed "Crags" or "Crag"? To me it seems you are navigating back to the main crag view, not to the index.

Hmmm, all confusion seems to be about the list on the left. I really wouldn't mind if it showed only the sectors of the crag. The Index would be the full tree and the area map. One mode for "I'm currently at this location and want to climb something" and another mode for "where shall I go climbing today?"

But "Done Editing" will solve the concrete issue of not knowing how to get out of the locate screen :-)

**Comment by georg-d** [comment] 2020-09-02 11:17
> As for Index the proposal is to change it to Crags, knowing that not all items listed here are crags it is still less techie than Index.

+1 for using a little less technical term.
If it still looks good (size etc), something like "Areas & Crags" makes clearer it's not only about literal crags.

> In my opinion everything related to what is selected in the list should be to the right of the list.

+1 

> Hmmm, all confusion seems to be about the list on the left. I really wouldn't mind if it showed only the sectors of the crag. 

The current state of left side tree is IMHO only one subtle piece of the overall issue (just like the term "index" in the main navigation) and slightly _extending it_ would IMHO result in a better solution than _reducing it_: Imagine the left side navigation continues to show "the related" crags/cliffs/sectors/... _but_ it _also_ shows what I actually do / which "dimension" of the crag I currently see (routes, locate, topos,...), be it via suffix in the name ("Wild Iris: Locate" so like breadcrumb does at the moment) or with a child element "Locate" (sibling of "Zorro" but different color, indention or the like). Like this, the left side navigation supports the orientation within the different "dimensions" of current crag (change) and also continues to be (unchanged) a very quick overview & navigation a) between siblings and b) into children (just to anchestors you can go as fast - via bradcrumb).

> But "Done Editing" will solve the concrete issue of not knowing how to get out of the locate screen :-)

+1

**Comment by rouletout** [comment] 2020-09-03 20:12
@matozoid yes correct - we will also tackle that at the same time.

**Comment by killakalle** [comment] 2020-09-04 15:12
@rouletout 

+1 for "Done Editing"

Will you add the button also to the Topo editing view? This one has the same problem.

I'm not sure the following has been addressed, yet:
![image](https://user-images.githubusercontent.com/30682796/92254718-972b6300-eed1-11ea-93a3-f87d4afa24ee.png)

To get to the above view, click:

- Open any crag
- Mouse over "Photos"
- Click "Topos"

You are in Topo view - though not editing mode - and `Index` is underlined. Would expect `Photos` to be underlined.

**Comment by rouletout** [comment] 2020-09-05 08:31
@killakalle yes, also for Topo Editing. Thanks for the other hint as well...

**Comment by scd** [comment] 2020-09-07 03:14
"Done Editing" has been hotfixed for topo and locate.

**Comment by killakalle** [comment] 2020-09-07 22:06
@rouletout this is a similar example

You are inside the Search, and you need to click the already underlined Index to exit the search
![image](https://user-images.githubusercontent.com/30682796/92418285-04a3f180-f167-11ea-975e-c4fec0840d33.png)

**Comment by rouletout** [comment] 2020-09-30 16:16
The "Done Editing" as well as the rename of Index to "Crags" is done - will look at the "minor navigation issues" next

**Comment by rouletout** [comment] 2021-01-15 10:01
open items collected in https://github.com/theCrag/website/issues/3831, closing here

**Closed by rouletout** 2021-01-15 10:01 UTC
Labels: 5: Polishing, Area: Navigation, Feature: Phototopo
