### ISSUE TITLE
Annotations should not take the numeration from the routes

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4161] opened 2022-12-24 09:14 UTC
Annotations should not take an index in the routes listing (as they are not routes), this causes misalignments with the climbing guides:

![image](https://user-images.githubusercontent.com/17315806/209429005-6f1a329a-e133-4aa3-aecc-c0d2bcce6f7e.png)

![image](https://user-images.githubusercontent.com/17315806/209429020-a2cc7136-1d9d-41df-82a7-ff42fe8280a3.png)

Annotations "give" the functionality of skipping one number in the indexing order, but that can be achieved with a dummy route.

In order to maintain sorting during big chunks of routes + annotations moves, there should be an internal indexing to keep them sorted, but that doesn't have to be the same as the routes enumeration.

Regards,

José María

**Comment by scd** [comment] 2022-12-24 09:17
Ta, we know about this. It is fairly irritating, but unfortunately it is a really big piece of work. Not going to be fixed for quite some time.

**Comment by Arzorth** [comment] 2022-12-24 10:19
Understood, I think as a temporary workaround, I will opt for including these notes inside the routes instead.

**Comment by rouletout** [comment] 2022-12-26 02:58
Duplicate of https://github.com/theCrag/website/issues/3753 - closing

**Closed as completed by rouletout** 2022-12-26 02:58 UTC
