### ISSUE TITLE
Bulk edit pulling wrong variable

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2641] opened 2017-03-08 23:07 UTC
The page x of Y text at the top, Y is pulling node count rather than page count. 

![image](https://cloud.githubusercontent.com/assets/22091505/23728287/1ea805be-04b0-11e7-8b79-df664acd41a6.png)

**Comment by Mdemaillard** [comment] 2020-03-08 17:19
Duplicate of #2911, that i tested and closed today already.
Closing.

**Closed by Mdemaillard** 2020-03-08 17:19 UTC
