### ISSUE TITLE
New ascent log - too many commas

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4091] opened 2022-07-04 08:26 UTC
Using the new ascent log, somehow there is a comma where there should be none - as if there was an additional (invisible) person.
![image](https://user-images.githubusercontent.com/30682796/177114020-e0f79287-21ea-4a81-8924-9b35ecf6a120.png)

In the ascent details all looks fine to me
![image](https://user-images.githubusercontent.com/30682796/177114150-5e5abe34-972d-405d-acb9-a6cf1cf075f8.png)

Stream event:
https://www.thecrag.com/event/6267194670

**Comment by rouletout** [comment] 2022-07-07 23:25
This looks like a small bug

**Comment by scd** [comment] 2022-07-11 06:34
I am not sure what happened here. I was unable to reproduce in my dev.

When I resaved your ascent the commas disappeared. Until we identify what caused the extra comma in the first place I don't think there is anything else we can do.

I am closing but please re-open or create a new issue if you discover how to repeat this bug.

**Closed as completed by scd** 2022-07-11 06:34 UTC
Labels: 2: Bug fix, Area: Logbooks Ticking & tick lists

**Comment by skomaroff** [comment] 2022-07-12 18:07
I can reproduce this.  Enter " ," (one space followed by a comma) for the climber's name.  Two or more spaces works too.

The empty climber's name disappears when editting the route.

![image](https://user-images.githubusercontent.com/84152181/178562588-3faa4f5e-a718-416b-8f4a-3035502dcbdd.png)

![image](https://user-images.githubusercontent.com/84152181/178562804-3b8e5ddb-8a3d-43bf-b529-f71da66f999e.png)



Essentially a duplicate of #3973

**Comment by skomaroff** [comment] 2022-07-12 18:09
It's possible to get a lot more extra commas too: 

![image](https://user-images.githubusercontent.com/84152181/178563103-733ddb27-a7aa-4445-9ba6-f0fa883a5ac7.png)

**Comment by scd** [comment] 2022-07-18 23:13
In dev I have fixed the storing of extra commas. For next release
