### ISSUE TITLE
Grades doubled

### ISSUE THREAD

**Issue by FF-Flo** [theCrag/website#4167] opened 2023-01-01 16:12 UTC
In this area (https://www.thecrag.com/en/climbing/portugal/area/6168535725) route 11 and 12 shows the grade "5c 5+" instead of 5c. Maybe because I changed grades fromm 5+ to 5c and/or merged routes somehow?

**Comment by killakalle** [comment] 2023-01-01 18:07
Probably duplicate of https://github.com/theCrag/website/issues/4153

**Comment by lordyavin** [comment] 2023-01-04 20:52
I believe the erroneous data was created by the merge operation you did previously. If this happens again please try to "record" what you did and what possibly led to the failure.

It is possible to work around the issue by editing the grade forth and back. See my update on https://www.thecrag.com/en/climbing/portugal/route/6171134553

**Comment by lordyavin** [comment] 2023-01-04 20:57
Duplicate of #4153

**Closed as completed** 2023-01-04 20:57 UTC
Labels: Content editing, Area: Reparent/Merge, 2: Regression
