### ISSUE TITLE
Special characters on Web-page not displayed correctly or at all

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2874] opened 2017-08-06 19:58 UTC
**What happened?**

Umlauts and other special characters are not displayed in the German version of the web-site on Google Chrome (Version 49.0.2623.112) - see attached
![thecrag com_4 8 17](https://user-images.githubusercontent.com/19162952/29006534-5ce6f038-7a9e-11e7-9fa8-84c4934a74fb.jpg)

Also, some pictures in the stream are not displayed

(please also provide urls and screen shots)

**What you expected:**

**Comment by scd** [comment] 2017-08-06 22:41
It works for me. I cannot see anything obvious here.

What operating system?

Do umlaut characters show on other websites or is it just ours?

Here is a discussion suggesting that it may be the clients system:

https://stackoverflow.com/questions/10134754/why-isnt-google-chrome-showing-the-proper-encoding

I think we need more info to work out whether it is our website or the browser.

**Comment by brendanheywood** [comment] 2017-08-07 02:13
That is clearly the wrong font for all body text, so perhaps they have overridden this locally?

**Comment by brendanheywood** [comment] 2017-08-10 15:05
@rouletout This is nerdy but I think the quickest, and possibly the only way, is to do this:

1) open web page
2) select any random text that we want to find which font it is using
3) right click inspect:

![image](https://user-images.githubusercontent.com/187449/29176935-b40faab8-7e30-11e7-9585-16269eb38cab.png)

4) Click 'computed' and then at the bottom you will see the exact font being loaded and how many glyphs from that font. There may be multiple fonts involved.

![image](https://user-images.githubusercontent.com/187449/29176987-d5e1216c-7e30-11e7-8c9e-e27df44890db.png)

5) Take a screen shot and dump it here just like those ones

**Comment by brendanheywood** [comment] 2018-05-16 12:53
closing as we cannot reproduce and looks like an overridden font issue

**Closed by brendanheywood** 2018-05-16 12:53 UTC
Labels: 2: Bug fix
