### ISSUE TITLE
Detect retina for topo display

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3054] opened 2018-02-11 23:31 UTC
**What happened?**

Topos always look blurry on retina displays, especially when enlarged.

<img width="1680" alt="screenshot 2018-02-12 00 28 24" src="https://user-images.githubusercontent.com/54371/36080128-c8d6f630-0f8b-11e8-8cb1-e8c9507992b8.png">

**What you expected:**

Simply double the size constraints if a retina display is detected (and not on mobile?), as seen in the inspect tool in the screenshot:

<img width="1680" alt="screenshot 2018-02-12 00 28 06" src="https://user-images.githubusercontent.com/54371/36080130-d1c921a0-0f8b-11e8-843a-28a27070fa8d.png">

**Comment by brendanheywood** [comment] 2018-02-11 23:51
thanks for this @quaestor 

I'm going to close this as a duplicate of https://github.com/theCrag/website/issues/1911

There is lots of moving parts to this, some of it is adding a responsive srcset which will do the retina detection, but there is other complications like the scaling is currently done in css and in some browsers this is gpu accelerated which means it's a static 2d bitmap scaled up which is the root cause. In any case the whole topo scaling code will be replaced, I'm about half way through this but had to put it aside to finish more urgent stuff. I hope to get back to this for the next major release

**Closed by brendanheywood** 2018-02-11 23:51 UTC

**Comment by quaestor** [comment] 2018-02-11 23:59
@brendanheywood Ah, I see. I remember #1911, but I thought it had already been resolved and this was a separate issue as I couldn't find any issue mentioning retina displays. My -- albeit possibly temporary -- fix above works for me, though, so I might go with a user script to double the respective values as long as this isn't resolved, because it's really annoying to draw topos having blurred visuals, or change to a non-retina monitor for that.

**Comment by brendanheywood** [comment] 2018-02-12 00:22
yeah there is probably around 10 topo zoom related issues which are all interrelated and I want to knock them all off together. The long term end game is being able to zoom in and out of topos like google maps, which also enables 'mega' topos like this:

https://www.thebmc.co.uk/zoomtopo/stanage/

**Comment by quaestor** [comment] 2018-02-12 13:58
All right, that's something to look forward to! But meanwhile, for those who don't want to wait and still edit topos on a retina display, here's a userscript:

https://gist.github.com/quaestor/74bd03a10a5a52f2a790f6701f82bd84
