### ISSUE TITLE
When merging two routes, specify a single pitch vs multipitch variant

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3352] opened 2019-01-26 11:18 UTC
**What happened?**

Eg route A is pitch 1 of route B and we wish to merge them

https://www.thecrag.com/discussion/2218872870/exasperator-p1

**What you expected:**

If these are merged the ascents of A should end up the same as a pitch 1 only ascent of B

**Comment by lordyavin** [comment] 2019-01-26 11:34
@brendanheywood what is the consequence for now? Should I leave the routes as they are and wait until the issue is fixed? Shall we document all merge candidates here to have it tracked?

**Comment by brendanheywood** [comment] 2019-01-26 23:10
I don’t have a good answer. I think if the number of ascents is very small then merge. If it is large then document it here.

Note that I think in some specific cases it is better to is better to split the multipitch apart than merge them together, it is case by case judgement

**Comment by Mdemaillard** [comment] 2020-03-04 15:00
duplicate of #3367 
yes this one is older, but 3367 has more content

**Closed** 2020-03-25 18:46 UTC
Labels: 5: Enhancement, Area: Logbooks Ticking & tick lists, Area: Multipitch, Area: Reparent/Merge, Content editing
