### ISSUE TITLE
Some grades start or stop early on either end of the grade slider

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2669] opened 2017-03-28 11:19 UTC
![screen shot 2017-03-28 at 13 16 14](https://cloud.githubusercontent.com/assets/19304867/24402462/ff537898-13b8-11e7-96fa-1bf38915c6e4.png)

https://www.thecrag.com/climbing/north-america/climbers/using-stat/sport-rating/?page=58

**Comment by nclementel** [comment] 2017-03-28 11:41
The 5 climbers in the V17 area where suspicious and I think that there are several issues connected with this plot:

- 1 and 2: they are there due to the fact that the two problems use respectively the France scale and UIAA scale which are then translated to bouldering scale.

- 3, 4, 5 and: I have no idea why they there ( 3 hardest ascent registered is a V13, 4 has 1 V16 3 years ago, 5 hardest boulder is a V11),  this looks like a bug.

**Comment by scd** [comment] 2017-03-28 12:17
Have another look in 24 hours. We are 're running the stats

**Comment by nclementel** [comment] 2017-04-11 13:17
The problem is not showing anymore in the boulder ranking, but I think is still there.
Looking at the grades table in the help section, some "grade numbers" and "grade bands" are not present for some grading systems.

Example for sport climbing at the two extreme of the spectrum (grade band/number missing respectively for YDS and UKT):

![screen shot 2017-04-11 at 15 02 08](https://cloud.githubusercontent.com/assets/19304867/24910487/3f7f97d4-1ec8-11e7-9d76-7c2b3d3eee89.png)

![screen shot 2017-04-11 at 14 07 07](https://cloud.githubusercontent.com/assets/19304867/24910488/3fa8da86-1ec8-11e7-8f5a-ef8617baeb53.png)

**Comment by scd** [comment] 2017-04-17 06:20
I am removing the 'Bug fix' label because the problem is a grade configuration issue. With regards to YDS, this s where the YDS difficulty level starts and with regards to UKT 7c is the highest UKT grade we have configured.

Do we need to create two separate issues for the UKT and YDS configuratons?

Do we want the grade slider to always be green to the left of any missing grade configurationand always purple to the right. This would hide the missing configuration issue. If not then we can close this issue.

**Comment by brendanheywood** [comment] 2017-04-19 15:36
I was going to treat this purely as a display issue in the grade slider and fill in the missing colors at both ends of the spectrum. I think we should also fix the grades where we can in new issues, but I'm not going to assume that all the systems will fill both ends.

And either way I would have labeled this as a bug somewhere, it looks broken to end users which is all that matters.

**Comment by scd** [comment] 2017-04-19 22:21
I will leave it with you then. I have changed the title.

**Comment by rouletout** [comment] 2021-01-02 15:42
gone, closing

**Closed by rouletout** 2021-01-02 15:42 UTC
Labels: 5: Polishing, Area: CPR / Ratings / Rankings, Area: Display/Layout
