### ISSUE TITLE
image galery thumbnails are very blurry 

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2326] opened 2016-08-18 12:44 UTC
see here for example:

https://www.thecrag.com/climbing/spain/alto-mijares/casucho/photos?page=2

**Comment by scd** [comment] 2016-08-18 23:19
For some reason the system is displaying different dimensions to the image request. For example:

```
<img itemprop="photo" width="420" height="315" src="https://static.thecrag.com/img/x320/c4/9a/c49a49feec94f43c71e2d2bc259cdf0d59b69d43" alt="" />
```
Gets the following image

https://static.thecrag.com/img/x320/c4/9a/c49a49feec94f43c71e2d2bc259cdf0d59b69d43

But displays it in a larger dimension.

This is possibly related to the thumbor bug with rotations not aligning #2303

**Comment by brendanheywood** [comment] 2016-08-19 02:33
I think there are two bugs:
1) the image dimensions should be passed to thumbor, but only one is, ie that picture should be

https://static.thecrag.com/img/420x315/c4/9a/c49a49feec94f43c71e2d2bc259cdf0d59b69d43

instead of 

https://static.thecrag.com/img/x320/c4/9a/c49a49feec94f43c71e2d2bc259cdf0d59b69d43

2) If you go through and manually fix these in the browser then most pics work perfectly, but there are a couple which look wrong and I suspect the aspect ratio is swapped around and so would be a rotation bug:

![image](https://cloud.githubusercontent.com/assets/187449/17797061/04287f48-6609-11e6-9b09-fff41bbce92b.png)

**Comment by scd** [comment] 2016-08-19 02:40
Thumbor only needs one dimension unless you are cropping. That is not a bug, it is intentional. 

There is a chance that when we fix #2303 this will automatically fix itself. This was a massively shitty issue and took many days to work out. It is very difficult to debug other issues with this one in the background.

**Comment by brendanheywood** [comment] 2016-08-19 02:44
True but it makes the other bug worse. If we specify it we get a cropped but great looking pic right now with 1 line of code change. When we fix the other bug then the cropping will get sorted. I think we should do that now as a hotfix. Long term it can stay there, there is no real downside. We might shave a few bytes in url lengths but that's not worth worrying about.

**Comment by brendanheywood** [comment] 2016-08-19 02:47
Also possibly another minor maths but, that image dimension wax x315 but the size rendered in html is 320 not 315, so there is some other discrepancy there as well to resolve.

**Comment by brendanheywood** [comment] 2017-07-15 07:14
> Thumbor only needs one dimension unless you are cropping. That is not a bug, it is intentional.

fyi this is dimension issue is now forced, by the time it gets back to the template both dimensions are always known which is required for responsive images which don't force a page re-layout. As an example here is prod as the page loads:

![image](https://user-images.githubusercontent.com/187449/28237363-d24214c2-6980-11e7-8e7b-b25cb33e059f.png)

and this is now dev while the page loads, so when the images turn up the layout doesn't jump around wildly

![image](https://user-images.githubusercontent.com/187449/28237372-f70c8a44-6980-11e7-850a-dba862c5f549.png)

I'm also closing this issue as the original issue I think is long fixed

**Closed by brendanheywood** 2017-07-15 07:14 UTC
Labels: 2: Bug fix
