### ISSUE TITLE
Could “cliff” be a line instead of an area on the map?

### ISSUE THREAD

**Issue by Beakerboy** [theCrag/website#4290] opened 2024-09-05 11:39 UTC
When a user is locating a region, area, crag, cliff, etc on the map, they must always draw a polygon. Would it make sense to allow some of them to be open lines instead? I can imagine a convoluted canyon where the north side is one wall and the south another. A user would currently have to draw two oddly shaped boxes, one around each. Instead they could just draw two squiggles. A sector could be two or more sequential points on the line, and a feature of a cliff or sector could be a sequence of one or more lines on the cliff.

A raised plateau or mesa could be a closed line, but not an area, just the outline rendered as a solid line or whatever you do.

**Comment by brendanheywood** [comment] 2024-10-27 09:49
There is two different concepts here, one is the bounding polygon around the cliff or boulder, and one are various features that could be on the map. So you might want to potentially draw anything on the map like tracks, the cliff line, or navigational land marks like ants nets or obvious features.

I've going to close this as a duplicate of https://github.com/theCrag/website/issues/1924

**Closed as completed by brendanheywood** 2024-10-27 09:49 UTC
