### ISSUE TITLE
breadcrumbs dropdown arrow should be to the right of node title

### ISSUE THREAD

**Issue by ajlowndes** [theCrag/website#3034] opened 2018-01-29 03:31 UTC
**What happened?**
In the breadcrumbs area, the dropdown arrows are to the left of the name of the area you are referencing. Should be to the right for better readability.

**What you expected:**
If I am in Australia > Victoria > Melbourne and Surrounds > Camels Hump, and I want to choose an area INSIDE Camel's Hump (say "Omega Block area") then I would expect to click the '>' arrow to the RIGHT of the title "Camel's Hump". Instead I need to click the arrow to the left, which doesn't make as much sense.

**Comment by brendanheywood** [comment] 2018-01-30 05:57
duplicate of https://github.com/theCrag/website/issues/2965

**Closed by brendanheywood** 2018-01-30 05:57 UTC
