### ISSUE TITLE
New coordinator not displayed

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2968] opened 2017-11-29 09:34 UTC
**What happened?**
We added myself as a coordinator to the [Kletterwerk](https://www.thecrag.com/climbing/kletterwerk) but my account is not listed on the ["Account Permits"](https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3APushReturnURL=%2Fclimbing%2Fkletterwerk&D%3ANetworkNodeID=528538971&C%3AState=18025&C%3AHideNavigation=1) page.

![grafik](https://user-images.githubusercontent.com/1528540/33367994-a1089c9c-d4f0-11e7-8027-7512cbb635a9.png)

I got the message that the my role changed:
![grafik](https://user-images.githubusercontent.com/1528540/33368221-5c8c7af6-d4f1-11e7-856f-14f0aad8eef0.png)

**What you expected:**
The ["Account Permits"](https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3APushReturnURL=%2Fclimbing%2Fkletterwerk&D%3ANetworkNodeID=528538971&C%3AState=18025&C%3AHideNavigation=1) page displays all account permits and provides a button for each account to update the permission instantly.

**Comment by scd** [comment] 2017-11-29 22:00
This is a wierd one. I will have to look into it. For debugging purposes I have confirmed that captainhook is a coordinator for that node.

**Comment by scd** [comment] 2017-12-11 00:38
@lordyavin I finally got a chance to look into this and it seems to be working now. Can you please check.

I have reviewed the code and cannot see why it was even broken and cannot reproduce. I have fixed another permissions issue in the meantime, but I cannot see how it is related. 

If it works please close.

**Comment by lordyavin** [comment] 2017-12-11 08:36
Logged in as admin and checked the permits page. It displays now me as a direct coordinator of the gym and all other permits of parent nodes. I assume that the parent node permits are displayed because @nicHoch switched back to community managed. To verify that issue is fixed the gym should be logged again.

BTW: I would prefer a table per node where all applicable (direct and inherited) and unique permits are listed.

Account | Level | Inherited From
-------- | ----- | ---------------
Kletterwerk (KLETTERWERK) | Administrator | Kletterwerk
Ulfi (ROULETOUT)| Administrator | World
Nicky (NICKYHOCHMUTH)| Administrator | World
Campbell Gome (CGOME)| Administrator | World
Simon Dale (SCD)| Administrator | World
Brendan Heywood (BRENDANHEYWOOD)| Administrator | World
Kai (CAPTAINHOOK) | Coordinator | Kletterwerk
Christoph Rauch (QUAESTOR)| Coordinator | Germany
Juergen Bollinger (JUERGENBOLLINGER)| Coordinator | Germany
Durand D'souza (DURAND)| Coordinator | Germany
Markus (OPAHLE)| Coordinator | Germany
Richard Goedeke (RGOEDEKE)| Coordinator | Europe
Bernii (BERNAAVARFUCHSLUEGER)| Coordinator | Europe
Philip (DRAZHAR)| Coordinator | Europe
Lukas Elsner (LUMAN)| Coordinator | Europe
Vanessa Wills (VWILLS)| Coordinator | Europe
Max Stein (STEINREICH)| Coordinator | World
Melwin Quacke (MELWIN)| Coordinator | World
Lee Cujes (LEECUJES)| Coordinator | World
Tobias (TOBI_)| Editor| Germany
Marcel Czink (MCZINK)| Editor| Germany
Anderl (ANDERLNOUGHT)| Editor| Germany
SCRAG (SCRAG)| Editor| Germany
Dirk W (SPELEODIRK)| Editor| Germany
andi scan (ANDERL)| Editor| Germany
Lenni (LENNI)| Editor| Europe
Jakob Schubert (JAKOBSCHUBERT)| Editor| Europe
LMD (LOUISD)| Editor| Europe
Moxi (MOXIFLOXI)| Editor| Europe
sandsteinklettern.de (SANDSTEINKLETTERNDE) | Editor| Europe

**Comment by scd** [comment] 2017-12-12 02:03
@lordyavin I have locked. Could you please re-verify but don't close the issue as I want to discuss with Ulf whether we should keep the gym locked or unlocked for the time being.

Also I am a little confused with your suggestion about the table. Are you suggesting a different sort order? From the point of view of a gym owner reviewing permissions I think your suggestion is reasonable.

**Comment by lordyavin** [comment] 2017-12-12 12:35
Checked the "Applicable Permit Records" again. Looks good.

Yes I'm suggesting a different sort order. Order first by permission level (admin=1, asc), then sort by nodeLevel (world=1, desc) and filter duplicates with least significant permission and node level. Additionally the order of the displayed columns as mentioned. Beyond that it would be nice to have some JS to change sorting of the table.

**Comment by scd** [comment] 2018-01-09 05:57
I now know what is happening here. When the gym is locked your Europe Coordinator assignment is being filtered out and also mistakenly clobering your gym assignment.

**Comment by scd** [comment] 2018-01-09 06:18
I cannot reproduce this on dev and kletterwerk is not in my dev database. Either it is fixed already or there is some strange interaction either with your account or kletterwerk.

I am going to have to wait until after the release to get a refreshed database.

**Comment by lordyavin** [comment] 2018-01-09 12:52
acknowledged

**Comment by lordyavin** [comment] 2018-05-09 05:39
Status updates? Is this still an issue?

**Comment by lordyavin** [comment] 2018-05-09 07:03
I added a new coordinator just now to [kletterwerk](https://www.thecrag.com/climbing/kletterwerk). The account is not [listed](https://www.thecrag.com/processmap/reviewpermit/528538971) as coordinator.

**Comment by rouletout** [comment] 2021-01-03 08:40
@lordyavin is this still an issue? If so, please update, otherwise close

**Comment by lordyavin** [comment] 2021-01-03 09:32
I can't verify this as I don't have the permissions anymore. You need to talk to one of the gym managers or create a test gym.

**Comment by rouletout** [comment] 2021-01-03 09:47
OK thanks - from what I can check this is no issue and haven't heard anything from kletterwerk - closing

**Closed by rouletout** 2021-01-03 09:47 UTC
Labels: 2: Bug fix, Area: Gyms, Feature: Permissions
