### ISSUE TITLE
stats using route registered grade instead of grade ascent was logged as

### ISSUE THREAD

**Issue by jedparkes** [theCrag/website#2257] opened 2016-07-18 00:21 UTC
If you look at my grade 26 ascents it is showing that i have done 7 grade 26's
https://www.thecrag.com/ascents/with-route-grade/AU:26:26/with-tick-type/on+tick+clean+lead+onsight+flash+redpoint+pinkpoint+leadsolo+second+secondclean+toprope+topropeonsight+topropeflash+topropeclean+ropedsolo+on+aid+aidsolo+on+solo+on+firstascent+firstfreeascent/by/jedparkes/?sortby=when-climbed,asc
That is because it is going off the registered grade no the grade i logged the ascent as.
If you look at this ascent for Big City Life you can see that i logged it as grade 22
https://www.thecrag.com/ascent/274645353
Can this be fixed up so my stats are correct?

**Comment by scd** [comment] 2016-07-18 00:28
It can be changed, but currently snowed under so it will be a while.

**Comment by jedparkes** [comment] 2016-07-18 00:32
Great thanks, let me know once done

**Comment by scd** [comment] 2016-07-18 00:34
I will close this issue when it's done. I think you will be notified when the issue is closed.

**Comment by jedparkes** [comment] 2017-01-16 00:55
This is also wrong on the ascents page
If you look at the ascent i logged for Anomia i put grade 22
https://www.thecrag.com/ascent/1048157853
But on the ascents page it is showing 24
https://www.thecrag.com/climbing/australia/mount-wellington/organ-pipes/route/298959768/ascents

**Comment by brendanheywood** [comment] 2017-01-16 01:10
cross linking to duplicate issue #2524

**Comment by scd** [comment] 2017-01-16 02:38
I have just made an assessment of what we have to do here and I need further business rules defined.

We should keep the 'with-route-grade' and create a new facet 'with-ascent-grade'. Is this reasonable?

Also the with-route-grade does the search based on the converted internal grade so it captures the level of difficulty across grading systems. This level of difficulty is cached on the route so the query is a one liner and very efficient. This means an Ewbanks search will return french grades of equivalent difficulty.

We don't have this same information available in the ascents. So technically I could just restrict the search to a specific grading system or if we want the cross grading system then I will have to do more investigation. I think with the rating system upgrade there is now a table which has this conversion information in a convenient table so I could do a cross rating system search, but I am not sure of the performance. If the performance is shit then we will have to do the same thing we did for route grades and cache the internal difficulty level.

So the business question is, do we want the ascent-grade search to be cross grading systems?

**Comment by brendanheywood** [comment] 2017-01-16 03:00
Yes we should definitely search across grade systems. Isn't LowInternalGrade the lower grade boundary of the ascent grade? I would have thought once you've converted the grade range in the url into an internal grade you'd just filter according to LowInternalGrade and InternalGradeWidth and you wouldn't care at all about the system or context, and you don't need any joins.

And yes we should have both a route grade facet and an ascent grade facet.

**Comment by scd** [comment] 2017-01-16 03:33
LowInternalGrade and InternalGradeWidth are cached values for the Rating algorithm and hence are route grade. They give us more flexibility for creating dynamic Rating queries, but perhaps not named so well given this recent discussion on route versus ascent grade.

**Comment by brendanheywood** [comment] 2017-01-25 23:17
@scd I was about to close this, but I've just noticed a regression from the other day. The ascent grade filter (as opposed to the route grade filter) no longer works and results in a 500:

https://dev.thecrag.com/climbing/australia/mount-wellington/organ-pipes/route/298959768/ascents/with-ascent-grade/AU:20:39/?sortby=when,desc

It could possibly be something busted with my dev box. Looking at the code it has lots of logic for filtering on the secondary grade and aid grade and stuff which all seems iffy to me, this should only be filtering on the technical grade. Or worse case should be filter so that any of the grades match OR, not AND.

I've added the must be done tag too

**Comment by scd** [comment] 2017-01-25 23:48
I think it is something to do with the dev box as it works on my dev.

I will keep this open and test in UAT before release.

**Closed** 2017-01-28 01:38 UTC
Labels: 2: Bug fix, 3: Mostly done, 4: Release followup, Area: Search and facets

**Comment by jedparkes** [comment] 2017-01-28 08:09
This issue is still not working for me?
Is it just waiting to move from dev page to live page?
Big City Life is still showing in my grade 26 list when i logged it as grade 22
https://www.thecrag.com/ascents/with-route-grade/AU:26:26/with-tick-type/on+tick+clean+lead+onsight+flash+redpoint+pinkpoint+leadsolo+second+secondclean+toprope+topropeonsight+topropeflash+topropeclean+ropedsolo+on+aid+aidsolo+on+solo+on+firstascent+firstfreeascent/by/jedparkes/?sortby=when-climbed,asc

**Comment by scd** [comment] 2017-01-28 08:11
The facet search you used was the route grade. You need to search on the ascent grade:

https://www.thecrag.com/ascents/with-ascent-grade/AU:26:26/with-tick-type/on+tick+clean+lead+onsight+flash+redpoint+pinkpoint+leadsolo+second+secondclean+toprope+topropeonsight+topropeflash+topropeclean+ropedsolo+on+aid+aidsolo+on+solo+on+firstascent+firstfreeascent/by/jedparkes/?sortby=when-climbed,asc

**Comment by jedparkes** [comment] 2017-01-28 08:24
yep you're right, everything is working, not sure where that old link came from. awesome work!
