### ISSUE TITLE
PDF Topos: Contributors not listed in intro

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3083] opened 2018-03-01 01:07 UTC
**What happened?**

the contributors by Karma are not shown (just the heading for it)

**What you expected:**

List of top contributors should be shown

**Comment by lordyavin** [comment] 2018-03-01 11:21
Duplicate of #2793

**Closed** 2018-03-01 11:21 UTC

**Comment by brendanheywood** [comment] 2018-03-01 11:31
@lordyavin if you close something as a duplicate can you please add a comment to the first issue with a +1 and @ mention whoever created the new issue

**Comment by lordyavin** [comment] 2018-03-01 11:47
I thought the automatic references are enough. Will do so next time.

**Comment by brendanheywood** [comment] 2018-03-01 12:06
thanks - because  we use the number of comments as a rough heuristic for setting priorities. The links don't count as comments
