### ISSUE TITLE
Image previews in markdown editor are broken, not fully qualified thumbor urls

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2994] opened 2017-12-30 02:43 UTC
**What happened?**

eg editing markdown which contains image tags / urls here:

https://www.thecrag.com/climbing/australia/kaputar

![image](https://user-images.githubusercontent.com/187449/34450774-276d7526-ed67-11e7-8d88-c5e2205f2474.png)

The root cause is that the image tags are not fully qualified and so you end up with munter urls like this:

https://www.thecrag.com/CIDS/cgi-bin/img/160x213/c9/40/c9403041a2623ec6b9d1dab19c4d567ef55666dc

**What you expected:**

* [ ] fully qualified urls to thumbor

**Comment by brendanheywood** [comment] 2017-12-30 02:49
Something very weird here, as they toggle on and off between a broken and working preview as you edit in different places in the markdown.

**Comment by scd** [comment] 2017-12-30 04:11
Just to confirm, was this an issue at all on the main index page. I had a look and the main index page looked ok.

This looks suspiciously like a cache issue, but it is not obvious how it got this way. 

Just in case there a fullyQualified param which was not set, that I now set and hotfixed. I could not reproduce the issue. 

Please close unless you think it requires further investigation.

**Comment by brendanheywood** [comment] 2017-12-30 04:37
It's still there, edit the node and make small changed to the markdown like add space:

![image](https://user-images.githubusercontent.com/187449/34451319-6f3d0a60-ed76-11e7-93cf-0e08a8c65e44.png)

and then I add a random char, this tim eI added am 'e' which I expected to break the second photo preview but should not have affected the first one at all:

![image](https://user-images.githubusercontent.com/187449/34451328-9e9eae58-ed76-11e7-8bd6-e97282a4fc44.png)

the image tags are relative links:

![image](https://user-images.githubusercontent.com/187449/34451337-c82f6230-ed76-11e7-9efd-af1c78a50433.png)

It's quite weird, I can add and remove random chars and some times it's good and others it's busted. That said it feels like it's getting harder to reproduce so maybe it's something cache related. I'm having trouble doing it again

**Comment by brendanheywood** [comment] 2017-12-30 04:45
Even weirder I've noticed that sometimes the photo previews have 'kaputar' and others have 'Kaputar' with a capital K so the layout jumps slightly, it feels like there is two different processes which get hit randomly which do slightly different things.

That might be completely unrelated and also the same bug as this:

https://github.com/theCrag/website/issues/1456#issuecomment-233837130

**Comment by scd** [comment] 2017-12-30 04:53
Let's leave this open until after the release because there is a lot going on with partial hot fixes. I want to see if this is just fixed after the release. One issue it could be is that in dev we need relative urls and in prod we need static.thecrag.com urls for images. The dev one could be triggered in error sometimes, and that maybe a confluence of hot fixes.

**Comment by brendanheywood** [comment] 2017-12-30 05:00
I think it needs to be fully qualified in all cases, but in dev it should point to itself.

**Comment by scd** [comment] 2018-01-15 06:07
This seems a lot more stable after the release. Closing now

**Closed by scd** 2018-01-15 06:07 UTC
Labels: 2: Bug fix, 3: Mostly done, 4: Release followup, Content editing, Feature: Markdown
