### ISSUE TITLE
Logging an Aid route as free without changing the aid grade

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3564] opened 2019-11-30 00:46 UTC
**What happened?**

While it is our standard policy to change an aid route to sport or trad and adapt the grade accordingly, there are many routes that can be either done free or with aid. A notable example is The Nose (https://www.thecrag.com/climbing/united-states/yosemite-national-park/route/20685193) and the free ascent by Barbara Zangerl (https://www.thecrag.com/ascent/2936265048) which was free but it isn't visible as such. It thus also is not calculated correctly for CPR or marked correctly in any profile stats.

Not a perfect analogy is Green Pointing a sport route - here we have changed the stats based on tick type (counts as Trad CPR, not sure how it ends up in your pyramid though).

This topic requires some discssion and many thoughts - this is the place to collect them.

Ideally also provide screenshots:

**What you expected:**

A way to log an aid route as free without changing the grade / style of the route.

**Comment by brendanheywood** [comment] 2019-11-30 03:48
> While it is our standard policy to change an aid route to sport or trad and adapt the grade accordingly

I would flat out reject that as our standard policy. My rule of thumb has always been 'what to the majority of people who climb it do?'. This applies to just about everything: which of multiple names should take precedence, should it be 2 pitches or a long link up, is it still sport if it's been green pointed etc. If most people still aid a route then its an aid route.

+1 Yes we definitely need to able to have two or more 'primary grades' for a route, but in the mean time we should not be universally swapping aid routes to trad if once they are freed. This is already logged a few times elsewhere #3527 and in particular in #1585. I'm going to close this as a duplicate of 1585

**Closed by brendanheywood** 2019-11-30 03:48 UTC
