### ISSUE TITLE
Route style filter in search not working

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#3285] opened 2018-10-08 04:27 UTC
**What happened?**

Searched for solo/OS solo ascents, limited style to trad + sport. 
Still a lot of DWS ascents showing up. no URL at the moment. 

Seemed to remove the boulder problems, so I think it's a DWS issue rather than system wide

Safari on iPhone, iOS 12

**What you expected:**
to be able to remove DWS routes from the list,

**Comment by brendanheywood** [comment] 2018-10-08 04:33
@DaneEvans can you please provide the url of the page you are one so I know exactly what you mean?

**Comment by DaneEvans** [comment] 2018-10-08 04:40
https://www.thecrag.com/climbing/australia/ascents/with-ascent-grade/AU:15:39/with-tick-type/on+solo+onsightsolo/with-ascent-gear-style/trad+sport/?sortby=all-time-rating,desc&page=2

Now I can

**Comment by brendanheywood** [comment] 2018-10-08 04:52
Ok there is the 'ascent style' and there is the 'route style'. ie it's edge cases but you could top rope a boulder or rope climb a dws etc. Use the 'route styles' instead:

https://www.thecrag.com/climbing/australia/ascents/with-ascent-grade/AU:15:39/with-tick-type/on+solo+onsightsolo/with-route-gear-style/trad+sport/?sortby=all-time-rating,desc

@scd it appears that DWS solos are counted as Sport ascents:

https://www.thecrag.com/climbing/australia/ascents/with-ascent-grade/AU:15:39/with-tick-type/on+solo+onsightsolo/with-ascent-gear-style/sport/with-route-gear-style/dws/?sortby=all-time-rating,desc

Is that by design or is that a bug? Either way I don't think the 'ascent style' filter is what most people want so I think we should de-emphasize it

**Comment by DaneEvans** [comment] 2018-10-08 05:19
Ahh that makes sense, I think on mobile I just saw style and clicked it. It’s hard to see the subsections on a small screen. 

Seemed like an odd corner case bug

**Comment by rouletout** [comment] 2021-01-04 15:39
Closing

**Closed by rouletout** 2021-01-04 15:39 UTC
Labels: 7: Idea for discussion, Area: Search and facets
