### ISSUE TITLE
Crag shows unlocated route, but everything seems to be located

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3810] opened 2020-12-15 20:08 UTC
**What happened?**
Crag shows an unlocated route, but everything seems to be located.

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/corbera

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/102266895-59e76000-3f19-11eb-89a3-6b31d5dbc83e.png)

**What you expected:**

* [ ] Do not show "unlocated routes" message, unless there really are unlocated routes

**Comment by gui84** [comment] 2020-12-17 02:01
Same as https://github.com/theCrag/website/issues/3770

**Comment by lordyavin** [comment] 2020-12-17 19:34
Duplicate of #3770

**Comment by killakalle** [comment] 2020-12-21 16:55
The ticket is maybe a duplicate, but the issue is not resolved. Suggest to re-open again until actually fixed, @lordyavin
you can see for yourelf: 
https://www.thecrag.com/es/escalar/spain/corbera

**Comment by rouletout** [comment] 2020-12-21 16:57
@killakalle I re-opened - it is actually on observation as we try to figure out when this happens. Eg. after a merge or some other action that fail to update this stat value. If you find more areas with this issue, please add them here.

**Comment by rouletout** [comment] 2022-12-28 01:37
Seems to be gone - closing for now

**Closed by rouletout** 2022-12-28 01:37 UTC
Labels: Area: Statistics
