### ISSUE TITLE
*/directory crawl errors

### ISSUE THREAD

**Issue by scd** [theCrag/website#2420] opened 2016-10-25 22:16 UTC
The largest crawl error in webmaster tools is a failure for all */directory urls.

http://www.thecrag.com/climbing/australia/cairns/directory

This is actually no longer used and I have not dealt with it properly.
 - [x] Update robots.txt
 - [ ] Do we need to do anything on webmaster tools
 - [ ] What is the standard return code for permanently removed url.

**Comment by brendanheywood** [comment] 2016-10-25 22:51
404 is fine, the problem has always been that these pages were incorrectly returning a 200 since we deprecated the directory stuff so google has been thinking all along that they are still ok but just a bit empty.

BUT the real problem here is not that the page doesn't exist, the problem is that it is still being linked to. If you google that url, then you will find the pages that link to it such as:

https://www.thecrag.com/climbing/australia/glasshouse-mountains/xhtml

which in turn is mentioned on this page:

http://www.vidinfo.org/video/10776447/4x4-fails-bush-bashing-at-glasshouse-mountain

So we have two tasks:
* [ ] generic: find the back links and remove them ( eg from the /xhtml template)
* [ ] specificly in this case, that /xhtml page should also not be crawled at all, so block that in the robots.txt The external page we have no control over

**Comment by brendanheywood** [comment] 2016-10-28 00:11
Confirmed this is working probably as best that it can in the webmaster tools so closing this

**Closed by brendanheywood** 2016-10-28 00:11 UTC
