### ISSUE TITLE
Route history and maintenance, + alerts for required work (dodgy bolt etc)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1865] opened 2015-02-22 02:27 UTC
Split off from #1313 and mentioning @tomkjaerolsen / @lordyavin 

My latest thoughts on the route history concepts are that we could have a much simpler data model (than what is proposed in #1313) which still works, effectively making 'editorial version history' a purely thecrag concept, while making 'physical route history' the real data model change. We already have a route history set of tables for FA and FFA, Set, so the only thing we need to do is add a 'Maintenance' type for history.

So we effectively completely ignore 'edit history' and focus purely on what happened in real life

| Name / grade | Who | Comment | Date | Type |
| --- | --- | --- | --- | --- |
| Mark's project 24-27 | mark | Mark found cleaned rock | Jun 1997 | Set |
| Into thin air 26 | mark | FA by Mark but not clean | Jul 1997 | FA |
| Into Thin Air 26 | greg | FFA by Greg | Oct 1997 | FFA |
| Into Thin Air 26 | dreeve | Rebolting in titanium, new anchor | Feb 2014 | Update |
| Into Thin Air 26 |   | Column fell over in storm | 2016 | Removed |

See #1244 for 'removed' route thoughts

So this would involve the following changes:
- [ ] Add a new history type of 'Update' (or Maintenance, or Fix, need something succinct that covers new anchors, glueing holds, rebolts, chopping bolts, removing dangerous rock etc)
- [ ] 'Updates' probably wouldn't get shown in list view, only in the route detail page
- [ ] Each history item currently doesn't have anything about name or grade. Adding this is more 'correct' and would really solve the other problem #1313 but is probably of limited value so leaning towards not bothering. Needs more discussion
- [ ] Hand in hand with the ability to add new 'Updates' is a way to report or list these in isolation, ie something like this page on chockstsone:

http://www.chockstone.org/Rebolting/RoutesQld.asp?Sort=Date

However I don't see the point in making work for ourselves for no reason. I'm pretty sure there are lots of benefits to ACA specifically moving from the chockstone DB to ours if we made this feature, but there is no point doing it unless they are going to move. Sure other similar clubs will also benefit but I'd want to get at least 1 or 2 on board from the start to make sure it solves the problem properly. So need to chat to David Reeve / ACA at some point or maybe @tomkjaerolsen you could help with this? Or point David to this issue
- [x] as a bonus would be nice for climbers to flag the need for this, eg 'Needs maintenance' and then the ACA could see a list of routes which need a look. Again don't want to even think seriously about this until we have someone like the ACA on board to make sure we do this right
- [x] There is some cross over with gyms, often a gym ticking app will have a 'needs maintenance' flag for spinning holds / broken holds etc
- [ ] There may be value in simply an 'Inspection' ie safer cliffs comes and tests / rebolts a bunch of stuff, some stuff is ok but it's worth marking that with a date
- [ ] After each inspection or rebolt, it may be worth having a 'review date' ie if the traffic / glue / metal is expected to last 10 years then set a reminder to review it at that point
- [ ] are there any requirements from government 'asset management' stuff where local climbing groups are part of management plans and need to document risk management and mitigation?
- [ ] From Neil: It would be good for the original bolting type to also be recorded (if known) as this is useful info for any problems that might occur in the future. (Brendan: ie an FA could enter this when they create the route, or anyone could go back and enter data for existing routes)

**Comment by nicHoch** [comment] 2015-02-22 22:17
I really like both thinks.
The "Update" Route history and the need maintenance flag.
We already had a "route update" in our old Alto Mijares database - but this information went lost during migration - because there was no direct mapping. 

In the current version of our Alto Mijares homepage (powered by the WP-Plugin) we connected an additional Plugin to provide the possibility to request changes for a route/area. Two kinds of changes - database issues but also real route maintenance like: new anchor required.  

We would be happy to withdraw that additional plugin if we could manage such thins direct in the crag:

See at the bottom of:
http://altomijares.org/wpcrag-node/?thecrag_node_id=637438569&lang=de&thecrag_topolabel=5

**Comment by brendanheywood** [comment] 2015-02-23 00:14
Screen shot of the alto stuff:

![image](https://cloud.githubusercontent.com/assets/187449/6321314/dcaba12e-bb4c-11e4-8267-5e2adff9dd05.png)

**Comment by brendanheywood** [comment] 2016-03-15 23:30
From Leith via email:

> 
> Just like with water, roads, power, enviro pollution, etc. There's so many more fault loggers than fixers. 
> 
> And just like in the above cases it becomes a bit chaotic without a decent system in place.
> 
> Climbing bolts aren't quite 'there' yet in reaching a state of deterioration that warrants a 'global' database system... but it's approximately a thousand bazillion times easier to manage if a system is in place before it gets 'there'. It's awesome there's already the safer cliffs tables etc. 
> 
> Having a background priority that feeds off the type of defect would be handy - such as a loose bolt would have a higher priority than cracked surface glue
> 
> Eventually a list of all the faults would be big enough that it becomes 'meaningful' and high trafficked and high priority defects are addressed first.

Some thoughts based of this:
* any climber can 'Report route issue' and we've had a dropdown of issues, each type might be classified as a 'Notice' and 'Warning' or 'Critical', eg a notice would only go into the log and you have to look for it to see it, a Warning would get flagged in the normal route list somehow, in a similar way to a X grade. A critical would be shown as 'Do not climb this route', ie major bolt failure, rock fall etc.

**Comment by davidreeve** [comment] 2016-03-19 08:42
I think we need to distinguish climbing-community-facing, from land-manager-facing, aspects of any sort of climbing infrastructure maintenance system we might consider. I think the Crag is clearly community-facing, whilst within the ACAQ we are necessarily manager-facing.

I suspect this means we are looking at too different things, but that is not to say there should not be communication between them.

After a few false starts going back some years, I believe the schema that suits the land-manager-facing application has to organised on a bolt by bolt, anchor by anchor basis. Bolts and anchors have to be independent of each other, as are all the bolts on any given route. The reason for this is that maintenance often occurs piece meal... fix an odd bolt here, part of an anchor there. Thus if you want to know the status of a particular route, you need to query for all the infrastructural components that comprise it and build a report. 

I've attached the schema for what I'm referring to as 'bolts_on_routes' or bolts currently installed on a cliff out there somewhere. The anchor situation uses similar tables, but is more complex due to the multiplicity of components that can comprise an anchor.

[Database Schema.pdf](https://github.com/theCrag/website/files/180720/Database.Schema.pdf)

**Comment by brendanheywood** [comment] 2016-03-20 04:42
Thanks heaps David,

I think it's clear that we (thecrag) should probably leave this on the back burner - it's pretty clear the ACA has, or will have soon, something pretty solid. I still think there is a lot of synergies and elimination of duplication of effort by combining this into thecrag, but maybe another group like the ACA will come along and be the catalyst for getting this right and being a 'sponsor' of this new feature. (or the ACA in the future if their internal DB doesn't work out for whatever reasons)

A few comments:

> I think the Crag is clearly community-facing, whilst within the ACAQ we are necessarily manager-facing. I suspect this means we are looking at too different things,

thecrag as a platform is more than capable of exposing different views to different audiences and we already have several features along these lines - you may just not be aware of them because you can't see them. We could hypothetically add more 'access roles' that can be assigned to people at the crag level like 'Lang manager' but this is probably overkill and we could re-use to the 'coordinator' role, ie only allow aggregation of maintenance history and issues / stats to crag coordinators. Coordinators so far have generally been the people doing the bulk of the crag development / guide book authoring and usually overlap quite a bit with the people doing rebolting / track work etc.

> I've attached the schema for what I'm referring to as 'bolts_on_routes'

This looks pretty solid, and there is unsurprisingly quite a lot of overlap with our internal schema. Some general comments:

* Bolts on routes, and Maintenance records both have links to routes AND crag, which seems a little redundant to me. The crag link is implicit, so I'd either remove the link, or make it readonly and updated under the hood so it's always correct. We have to deal gracefully with a lot of region / area / crag restructuring, its better if the data model is resilient to changes like these.
* Bolts vs fixed hangers - these two tables are probably satisfactory for the ACA but if we were to adopt / adapt this schema we have a whole bunch more types of pro to deal with across the world, and it seems like there is enough overlap (eg material, supplier, title etc) for these to be merged into a single table with an extra 'type' and a bunch of optional fields depending on the type. I would also change EN_959 compliance from a simple flag into a link to another 'specification' table so we could support multiple current and future compliance specs as they evolve.
* It may be over kill but possibly worth making (route + bolt_no) a joint foreign key for the bolts_on_routes table, it may be worth knowing that bolt 3 on route X is the same as bolt 5 on route Y, or perhaps it's enough to have a 'primary' route which is what the bolt_no refers to. 
* Some use cases that you may have missed is bolts and other hardware (and not sure if you covered this with anchors) that are not related to a route at all. Eg fixed lines for access traverses, bolts for practising anchor setup, bolts just for a long safety while you set up an anchor in a sketchy location, bolts for safety at the base of a crag with sketchy ledge etc
* Do you need to cover cases where there are permanent draws on bolts? Some other edge cases might be fixed wires, threaded slings, etc (whenever we come up with any data model because of our scale we always find edge cases which don't fit the mould)

Anyway thanks again for everyones input, if / when we come back to this in the future we'll be better prepared

**Comment by davidreeve** [comment] 2016-04-24 08:25
Apologies for the slow response Brendan. All good suggestions. I agree that there is nothing more certain than its the edge cases that screw over the best of schemas. We have done a couple of cases where we have provided 'access' anchors in cooperation with QPWS, so I'll put some thought into including them. 

I'm biting the bullet and have started loading data for KP and Brooyar. Is there any way I can grab a csv with route data from the Crag to save time? I'm after route-name, grade, height and date-of-FA only. I stripped data from the old ACA database, but decided against using it as it looked pretty out of data. The idea is once I have this entered we can have folks entering actual bolt by bolt stuff on site. It also lets me publish a form where the public can report problems with hardware.

**Comment by scd** [comment] 2016-04-24 22:40
No CSV, however we have a JSON api endpoint for the index structure.

It is probably worthwhile making a decision now where the 'master' copy of the routes is going to come from.
Option 1: Once off seed from theCrag then go your own way
Option 2: Sync from theCrag but do not allow routes to be manually added to your databasse without theCrag ID 
Option 3: Sync from the crag but allow non-theCrag routes to be added.

The option that requires the least long term work and provides the most flexibility is option 2. If every route in your database has a theCrag id then we can link directly to your form theCrag if somebody wants to report a problem. You could get a daily routes sync from theCrag using the API. The programming logic should be fairly simple if every route has a theCrag ID. 

If the databases become out of sync without ids then it is a huge amount of work to bring them together again.

If we can keep these databases in sync then the long term support will be significantly easier.

I am happy to give you the JSON API dump whenever you want as a once off. Otherwise we are also happy to set you up with an API key. The JSON API key needs to be associated with somebody who is on a monthly supporter status ($5 per month). For various reasons this is a rule for all developers and helps us clean up old API keys that are no longer in wanted.

**Comment by davidreeve** [comment] 2016-04-25 02:11
Excellent thinking re theCrag ID. This makes a lot of sense going forward. 

It looks like it is possible for Zoho to sync fields from TheCrag using JSON. This appeals, but I'm wondering whether it is isn't overkill given the purpose of the app. One of my key aims is to keep things really simple so that the maintenance can be passed on without too many dramas.

I don't envisage route/crag details being publically alterable. In fact, the crags needing maintenance records are the ones already fully developed, so I don't really see any of this stuff changing once loaded. Provided we have TheCrag ID in place as a facilitator of the sorts of db merges etc that might make sense a decade or more down the track, I think we will be all good.

If you can get me a JSON API dump, that would be great.

**Comment by scd** [comment] 2016-04-26 23:41
Please send me an email so I can give you a JSON dump. My email address is scd@thecrag.com

Whichever way you end up deciding to do it I highly recommend that all your routes have a theCragID. If you create routes without this id then there will be a lot more work to maintain the database in the long term.

**Comment by brendanheywood** [comment] 2016-12-06 08:59
Just dumping here a mockup from an internal email around the idea of 'setting' or development work, ie scrubbing, bolting, or new anchors etc, being logged and shown in the streams:

![image](https://cloud.githubusercontent.com/assets/187449/20918788/d163bcdc-bbec-11e6-8a04-966b3e5481e6.png)

**Comment by Flanagb** [comment] 2018-03-10 09:48
Thanks for the access to this thread Brendan. To all involved in this thread I recently emailed Brendan asking him if theCrag would be introducing bolting history such as types of bolts used, methods of applications and dates bolted.

I'm Sydney bolter who has been taught by experienced bolters who operate according to UIAA standards.

Has this project progressed any further?

Cheers,

Brendon

**Comment by davidreeve** [comment] 2018-03-10 12:43
Hi Brendon,

We've had the ACAQ bolt database running for several years, and I'm pretty happy with the level of engagement it has achieved. We have concentrated on Kangaroo Point because this is where it is most needed. We have close to 300 bolts audited, covering the majority of the popular routes. It is a bit of a mission getting auditors up to speed with inspection, especially learning to identify historical hardware, but overall it has gone reasonably smoothly.

Have a look here to see what the main database looks like..
http://bit.ly/KPBoltsPublic

There is a public facing portal for people to report problems which we advertise on signage at the crag itself. You can see it here .....
http://bit.ly/KPBadBolts

It can do cool reports like this ...
http://bit.ly/KPBoltAge

and this ....
http://bit.ly/KPBoltTypesGraph

We use The Crag ID for every route in out db to guarantee the possible linkage of our data to that in The Crag.

Currently we have stacks of capacity under our $120 Zoho subscription so could easily accept entries from other areas should some individual want to champion the cause.

cheers

Dave

**Comment by Flanagb** [comment] 2018-03-12 09:38
Thanks for the links David. It's excellent to see this data base in existence. I'm happy to champion it here in Sydney and ask other bolters to contribute to it.


How would we go about doing this?


Cheers,


Brendon


________________________________

**Comment by davidreeve** [comment] 2018-03-14 01:27
Hi Brendon,

 

I can certainly set you up to get something happening.

Normally what I do is set up for just one crag at a time. This is more manageable. Is there one particular area where you want to start? 

What I do is publish say a form that lets you enter route details for just that crag. Then I use another form that allows bolt by bolt entry for every bolt at that particular crag.

 

Let me know how you want to work this.

 

Cheers

 

Dave

**Comment by Flanagb** [comment] 2018-03-14 05:07
Sounds good. I'll start by working crags and routes that I've bolted then see if i can work with others with logging their work.


Can you please set me up for the following crag and allow me to register each bolt.


https://www.thecrag.com/climbing/australia/north-shore/area/276941769


Once I've got that one sorted I'll send you more crags for you to start up for me.


Cheers,


Brendon

[https://image.thecrag.com/267x200/58/2d/582db6bacd528bc1066f35272864e0b48bd7d525]<https://www.thecrag.com/climbing/australia/north-shore/area/276941769>

Ranger Daves School Yard For The Gifted Climber, Rock ...<https://www.thecrag.com/climbing/australia/north-shore/area/276941769>
www.thecrag.com
6 sport and trad routes in cliff • Ranger Daves School Yard For The Gifted Climber, a cliff inside Middle Cove, Australia • Rock climbing info





________________________________

**Comment by davidreeve** [comment] 2018-03-15 06:07
OK…. here is a link that gives a restricted view of Ranger Daves routes

https://creator.zohopublic.com/acapresident/acaq-bolt-register/view-perma/Ranger_Daves_Route_Entry/EknAyZFd14YtmCjS0C7hv04aEdFakkP7HP7xPjHVvNBZNqadAOaERMxeM9Zk3Jt0HKCH5Z6X6NSghRrXX9rmuB17FrV0aOCXrgDx

 

And here is one for bolts

https://creator.zohopublic.com/acapresident/acaq-bolt-register/view-perma/Ranger_Dave_s_Bolts/2eDgDAOCOqg7XsJPv6GzVfJAECxE3z89aD5VGxhRD5P7JF5r7pvZyM2tDBUJB3k6wmnrOZmVOyekVE1v180DV8ybVe8tGbJTTBXk

 

Note that although the view is restricted, when you go into the edit dialog, the drop downs are fully populated. I still haven’t figured out how to fix this, but it is not as dire as it looks. Just start typing and the list will resolve in a couple of characters.

Let me know how you get on. Identifying bolts is not a big deal unless they are old stuff. I’ve put in an arbitrary entry for 1 bolt… almost certainly wrong. Let me know if you have trouble making sense of the various bolt types. Once entered you’ll see you can get more info on them by clicking on the hyperlink.

We’re on a biot of a learning curve here, so do let me know what works and what doesn’t.

 

Cheers

 

Dave

My email outside of The Crag, is president@climb.org.au

**Comment by brendanheywood** [comment] 2018-11-12 23:49
+1 via facebook

**Comment by brendanheywood** [comment] 2019-01-01 09:53
+1 via support email

**Comment by killakalle** [comment] 2021-02-23 13:17
+1
I would like to have a means of recording the rebolting of a route (mostly date, rebolter) other than adding it into the route description.

**Comment by rouletout** [comment] 2021-02-23 15:25
This will be available from next release on - I leave that open till then.

**Comment by rouletout** [comment] 2021-03-23 18:56
available now, closing this until some of the discussions above become relevant.

**Closed by rouletout** 2021-03-23 18:56 UTC
Labels: 6: New Feature, Content editing
