### ISSUE TITLE
Cant revert multi pitch to single pitch route

### ISSUE THREAD

**Issue by danilobuerger** [theCrag/website#3680] opened 2020-05-21 15:00 UTC
**What happened?**

I tried to revert the route "Joker" which was set as multi pitch to single pitch. However, setting the number of pitches to 1 and setting the grade to 6+, the 2nd pitch still appears.

Example url(s) to reproduce the problem:

https://www.thecrag.com/climbing/germany/route/265972380

**Comment by Mdemaillard** [comment] 2020-05-21 15:17
Duplicate of #3587

**Comment by Mdemaillard** [comment] 2020-05-21 15:19
Thanks Dani, this a duplicate issue so i will close here. How long is the climb ? Are you confident it should be single pitch (only) ?
If yes i will edit the contradictory entry.

**Comment by danilobuerger** [comment] 2020-05-21 15:26
@Mdemaillard thanks for your quick response. So I climbed this route myself and have the guide book for the local area in front of me. Therefor, I am highly confident. The route is about 20-30 meters long, however, I don't know specifically as the guide book does not provide that information.

**Comment by Mdemaillard** [comment] 2020-05-21 15:30
thanks

**Closed** 2020-05-21 15:30 UTC
