### ISSUE TITLE
Forum Posts at World level

### ISSUE THREAD

**Issue by Mdemaillard** [theCrag/website#3650] opened 2020-04-19 13:26 UTC
This seems to be an issue again at the moment, I'm not sure if it's due to changes, or just a few more users prepared to use the world forum to post a help ticket. 

I think the higher level ones need to have more gates than just a low karma threshold. 

Maybe a page that has a large warning that you are targeting a large audience, and that unless it has wide appeal it will be removed, and offers you a list of more suitable alternatives 
- help pages
- message support
- a country/state level forum 

I can't think of a genuine use case for a 'world' post apart from admin messages.

_Originally posted by @DaneEvans in https://github.com/theCrag/website/issues/1365#issuecomment-597403750_

**Comment by rouletout** [comment] 2021-03-24 21:24
+1 from support, see also https://github.com/theCrag/website/issues/3881

**Comment by killakalle** [comment] 2021-03-27 00:34
I don't think making posting more difficult is the right way to go about this. 

What is the real problem here?

I think there are two problems:

**One**. Some (old) users do not want to read the questions of the group above. But they have no way of unsubscribing from those posts.

**Two**. Some (new) users have a need to ask basic questions about the functionality of the web page. There is no obvious place where this should be done. A natural reflex is to post this in the forum. So, let's take a look at what is offered in terms of forum.
![image](https://user-images.githubusercontent.com/30682796/112704203-fcf53180-8e99-11eb-8faf-36e4c911fbb8.png)
No help forum in the list. Well, then what's the next best choice? ....Spain. Maybe, but my help question is not related to anything in Spain. So, then World level seems the logical choice. Because anybody anywhere in the world could potentially answer a help question. Right, then World it is.

So, in my opinion, the problem is that the geographic-hierarchical structure of forum is good for any climbing related posts that have a connection to a geographic area, e.g.
- "Who removed the bolts at crag X" -> Forum of Crag X
- "Help, authorities want to restrict climbing in the entire area Y" -> Forum of Area Y

But anything that does not have a clear geographic context does not fit that structure well, e.g.
- help questions
- gear questions
- general random discussions
- potentially many more

I believe a few more "classic" forum options (see list above) would help.

**Comment by DaneEvans** [comment] 2021-03-27 02:24
A functionality of the webpage question should never be seen (forcibly) by
the entire user base.

 I still haven't seen a 'world' forum post that should be forced on
everyone. What use case is there for this?

 Admin has banners at the top which get used for promotions, bug issues
etc.  So they don't end up in here.

The categories that do are :
- Straight up spam / deleted spam, which is a good 50% of what I see there.
- The occasional research paper request has at least some value to a
worldwide audience.
- questions that are covered under help.
- questions that should be at a crag level 'I'm going to be at Araps, who
else is?'


Can you get stats on the number of users that have hit the mark as read or
leave buttons at world vs other levels?
They might be telling as to the value of those conversations.

**Comment by rouletout** [comment] 2021-04-24 18:48
+1 from support email (Luke Woj)

**Comment by rouletout** [comment] 2021-06-07 18:19
Example from Luke

![Screenshot_20210608_003126_com android chrome](https://user-images.githubusercontent.com/19162952/121069340-f8e76900-c792-11eb-84f8-ab0c8c2b2d13.jpg)

**Comment by rouletout** [comment] 2021-06-29 15:50
A Karma limit has been implemented to avoid accidental posts by new users and a warning with explanation and links to dedicated general forums (such as how to) - closing

**Closed by rouletout** 2021-06-29 15:50 UTC
Labels: 5: Polishing, Area: Forums & Messaging
