### ISSUE TITLE
Suggestion - Manual control of Topo order

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2484] opened 2016-12-13 02:33 UTC
The current system works quite well, but I often want to have an overview Topo/map at the start.

 If you don't put the topos in the right order at the initial upload, then the only way to force it is to have the first route only exist on the map, and not another typical phototopo. Or include a parent/sibling area

Seems that having manual control, or a checkbox to make it appear first would be useful, don't know how feasible it would be though.

**Comment by brendanheywood** [comment] 2016-12-13 03:20
Thanks @DaneEvans - this is a duplicate of #1190 so I'll close this issue, please read and comment on the other issue instead if you want

**Closed by brendanheywood** 2016-12-13 03:20 UTC
