### ISSUE TITLE
Multipitch grades breakdown coming from a random grade contribution instead of from the registered grade

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#3053] opened 2018-02-11 08:48 UTC
**What happened?**
I changed a pitch grade of a route ( https://www.thecrag.com/climbing/switzerland/alpen/sarganserland/route/521429469 ) from "7b,6a" to "7a,6a". Due to the change, the overall grade and the community registered grade were reduced to 7a as expected. But the Breakdown at the top and the grades overview at the route lists (which is a really cool new feature) didn't change.

![screenshot 2018-02-11 09 40 20](https://user-images.githubusercontent.com/3040689/36071587-9bafafec-0f10-11e8-8b4a-447a3fe11cfa.png)

**What you expected:**
The grades at the route list overview and the breakdown should also represent the new grade.

**Comment by Drazhar** [comment] 2018-02-11 08:52
Forgot to mention: The route height will be updated, only the grades won't.

**Comment by scd** [comment] 2018-02-11 09:00
Yes I know about this. The issue is that there is no 'registered' (official) component of the breakdown. If you notice that there are two grades contributed with breakdowns. The system just picks one.

It has some deeper implications because it is the same breakdown that appears by default when logging a multipitch route. 

I am not sure how to handle this right now. If you have an easy solution, like pick the latest rather then the first, then let me know. Otherwise it is probably going to have to be an extra db field and extra UI to make this work properly.

**Comment by Drazhar** [comment] 2018-02-11 14:15
Why don't you just pick the Community registered grade instead the user optinions?

**Comment by scd** [comment] 2018-02-11 21:12
Because community registered is not a breakdown, it is the overall grade.
We could also extend functionality to do this.

**Comment by brendanheywood** [comment] 2018-03-07 10:14
I'm not sure if this is the same bug, but this route has a community grade with the breakdown:

https://brendan.thecrag.com/climbing/mexico/el-potrero-chico/route/98049759

![image](https://user-images.githubusercontent.com/187449/37086596-0c401abe-224c-11e8-9afb-4d7428fddb82.png)

But the community grade is being ignored and some random grade (Zorba's) is being displayed instead:

![image](https://user-images.githubusercontent.com/187449/37086648-2e37763a-224c-11e8-8f80-f33055d30f15.png)

This is really confusing because you see the error, and then you go to fix it, and you can do everything perfectly and it just eats your edits and looks like they are discarded.

@scd is this really a data model issue? The community grade with the breakdown is being stored and you get correct roundtrip editing. It's just that the display pitches don't match the community grade pitches

**Comment by scd** [comment] 2018-03-07 10:25
I think pitches only works properly for grade citations. From memory if you
put pitches into a registered grade then only the overall grade will be
stored.

**Comment by brendanheywood** [comment] 2018-03-07 10:43
No, I am getting roundtrip editing:

![image](https://user-images.githubusercontent.com/187449/37088105-5cf85134-2250-11e8-834c-5876f0d48f50.png)

It's just the template data doesn't match it:

![image](https://user-images.githubusercontent.com/187449/37088136-73874cd4-2250-11e8-9520-1142878c2685.png)

**Comment by scd** [comment] 2018-03-07 12:41
I did not know round trip editing on registered grade multiplied is
working. There may be some downstream issues.

The grades for multiplying come from the first citation, so this issue
should be easy to fix. But we should make sure there are no other issues

**Comment by brendanheywood** [comment] 2018-05-22 14:02
Another data point for testing, this is a boulder problem:

https://www.thecrag.com/climbing/australia/sutherland/route/13093345

This is has a commuity grade of V5, but some random contribution has used a , instead of a / or -, and this grade is overriding the proper grade for the pitches, so we have ended up with a 2 pitch boulder problem :)

![image](https://user-images.githubusercontent.com/187449/40367318-5d678902-5e1c-11e8-91d3-cfa29c3be194.png)

![image](https://user-images.githubusercontent.com/187449/40367336-6e0ccc72-5e1c-11e8-9539-433531a469b1.png)

**Comment by brendanheywood** [comment] 2018-09-26 05:38
Another example, this route should have pitch grades of 16,17. The community grade was simply 17:

https://www.thecrag.com/climbing/australia/mt-maroon/route/12194509

This was the root cause:

![image](https://user-images.githubusercontent.com/187449/46059252-cdb6ba00-c1a1-11e8-90fd-261b1c7c2a58.png)

But even after I updated the community grade it still didn't work:

![image](https://user-images.githubusercontent.com/187449/46059312-ff2f8580-c1a1-11e8-976e-f254aea4ef37.png)

So I ended up updating that contribution from 15,17 to 16,17 which feels a little wrong works

**Comment by rouletout** [comment] 2020-11-10 08:29
I tried to reproduce these and couldn't. Can this be gone with the grade updates and the script that was run? Can anyone - especially @Drazhar reproduce this issue still?

**Comment by Drazhar** [comment] 2020-11-10 09:08
I think I saw this just recently. I will check it later or in the evening.

**Comment by Drazhar** [comment] 2020-11-10 20:50
So, I did some small tests. The bug which was known to me is gone. The grade of the route seems to be correct for the cases it wasn't in the past.

Also the breakdown at the top was removed. So the error regarding the breakdown is gone anyway 😛 

So from my side this issue can be closed.

**Comment by scd** [comment] 2020-11-10 21:32
Ok great. Closing

**Closed by scd** 2020-11-10 21:32 UTC
Labels: 2: Bug fix, Area: Multipitch, Content editing, Feature: Grades
