### ISSUE TITLE
Stream bug, why am I mentioned here?

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2433] opened 2016-11-06 23:16 UTC
https://www.thecrag.com/event/1003078644

![image](https://cloud.githubusercontent.com/assets/187449/20042713/2b5b7eb8-a4d3-11e6-81d1-6da9074a9ad9.png)

**Comment by scd** [comment] 2016-11-07 05:06
FYI, you can look at the data:

https://www.thecrag.com/event/1003078644/json

The involved flag is set. This can be set because you messaged the event or you were mentioned in the ascent, either in the comments or the with field.

If you messaged the event or then the discussedEvent field would also be set. 

In all cases I don't think the logic has been included to remove accounts who have been included once they have been mentioned. So if you were mentioned in the comment then later taken out this would explain what is happening.

I am guessing that you were never mentioned in this because it is in the ACT.

There is a StreamEventInvolved record with you associated with the event, so the display is working according to the data.

I don't think we can get any further on this one with the info we have got. We may want to raise an issue to remove 'involved' accounts if they have been removed from the mention source. However this is a lot of logic, for little gain.

My worry is that there is something bigger going on here. So we should look out to see if this is occuring more often

**Comment by rouletout** [comment] 2020-12-30 15:28
Not a bug, closing

**Closed by rouletout** 2020-12-30 15:28 UTC
Labels: 2: Bug fix, Area: Streams / feeds, X: Need to be monitored

**Comment by brendanheywood** [comment] 2020-12-31 06:21
This is 100% still a bug. The person mentioned me by accident, then he edited the tick to remove me, and the stream event mentions wasn't updated

**Comment by brendanheywood** [comment] 2020-12-31 06:22
> I frequently climb with a guy called Brendon - when I started logging the ascent, it suggested you (because you're name is similar to his? even though he wasn't actually there that day?) and I think I may have accidentally clicked you. When I realised what had happened, I deleted you.
