### ISSUE TITLE
Crag without webcover doesn't need a big frame on the generated PDF

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#3875] opened 2021-03-15 19:44 UTC
**What happened?**

The PDF for a crag that has no web cover (I assume) has no picture on the front. But it really doesn't need a big empty frame then.

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/netherlands/area/4320216585

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/55701/111211698-01366a80-85cf-11eb-854f-791d32b188ee.png)

**What you expected:**

Some kind of placeholder image, of a different cover with only text.

**Comment by rouletout** [comment] 2021-03-15 20:44
Duplicate of https://github.com/theCrag/website/issues/3397 - this has nothing to do with web-covers, it is simply broken :-(

Closing here

**Closed by rouletout** 2021-03-15 20:45 UTC
