### ISSUE TITLE
Linking photos as admin

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2957] opened 2017-11-18 21:25 UTC
Having admin permissions to a crag, I would expect I'd also be able to correct the linking of photos. Apparently, this is not the case. This would make sense, though.
Instead, when clicking a photo, I get a drowdown for selecting its priority for WebCover.  If this is intended, it would benefit from some expanation.

**Comment by scd** [comment] 2017-11-18 22:13
Two separate concepts. 

Currently you can only relink your own photos. This is a functional gap, which we will cover once we have a node selector widget. 

We covers are the images that are shown in the crag header.

**Comment by brendanheywood** [comment] 2017-11-19 07:33
thanks @MelwinQ - I will close this as a duplicate of https://github.com/theCrag/website/issues/1124

If you have more comments or feedback please add it over there

**Closed by brendanheywood** 2017-11-19 07:33 UTC
Labels: 6: New Feature
