### ISSUE TITLE
Ticks not showing on area page

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2531] opened 2017-01-15 06:39 UTC
I suspect this is another one related to 'area' as opposed to 'boulder'. 

On the list of routes in an area existing ticks are not showing up, it's all grey. It's working fine in all of the other types I checked, and I can't find any other 'areas' that I have ticks in directly. 

Particular area is https://www.thecrag.com/climbing/australia/pierces-creek-bouldering/area/11833147 - I'll change it to sector and see if that fixes it unless you want to have a look first?
![image](https://cloud.githubusercontent.com/assets/22091505/21960764/9794fc6a-db49-11e6-89cc-d8a8dd4a9fa8.png)

Seems like an Area shouldn't have routes directly below it anyway.

**Comment by brendanheywood** [comment] 2017-01-15 11:28
thanks @DaneEvans this is also mostly a duplicate of #2451 and also related to #1288 - but I won't close this one just yet as the bug is a bit more serious than #2451.

You should be able to use area, but yes in the mean time you can just set it to anything else eg sector and it should sort itself out (at least for new ticks, not for the old ones). But can you please leave it in the broken state as we really need to sort this properly and it's good to have a stationary target.

In my proposed algorithm the pseudo crag in absence of an explicit one would be 'Tidbinbilla area / Paddys River Rd'

@scd the bug here is more serious than simply having the wrong crag listed in the stream event - the whole stream event is completely missing.

**Comment by scd** [comment] 2017-01-16 00:06
This is fixed in my dev and will be available from next release.

**Closed by scd** 2017-01-16 00:06 UTC
Labels: 1: MUST BE RESOLVED FOR RELEASE, 2: Bug fix

**Comment by brendanheywood** [comment] 2017-01-16 03:42
Was just this stream bug fixed, or also the TLC definition?

**Comment by scd** [comment] 2017-01-16 04:47
Purely TLC definition issue. Fixing the TLC definition will fix most of the stream issues. The stream bug will be a significant minority of cases.
