### ISSUE TITLE
PDF Topos: Route labels unreadable

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3326] opened 2018-12-22 18:20 UTC
**What happened?**

For example in this area https://www.thecrag.com/climbing/mexico/el-salto/area/1667175816 the image of the topo has unreadable labels (see screenshot).

Ideally also provide screenshots:

![img_3808](https://user-images.githubusercontent.com/19162952/50377485-cefe5400-05e3-11e9-8a21-27128cb0cf4f.PNG)

Readable numbers on topo

**Comment by brendanheywood** [comment] 2018-12-23 00:09
Duplicate of https://github.com/theCrag/website/issues/2706

**Closed by brendanheywood** 2018-12-23 00:09 UTC
