### ISSUE TITLE
Stars: some ascents not considered (?)

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3940] opened 2021-07-03 15:59 UTC
**What happened?**

This route has one crap rating but it doesn't show on the route page / is not considered: https://www.thecrag.com/en/climbing/china/shandong/route/1825676319

![IMG_7723](https://user-images.githubusercontent.com/19162952/124360111-8cbf2000-dbed-11eb-8804-2284f434931a.JPG)
![IMG_7724](https://user-images.githubusercontent.com/19162952/124360114-8f217a00-dbed-11eb-8503-c4d282188549.JPG)

Might be related to https://github.com/theCrag/website/issues/3870

**What you expected:**

Display of all ratings.

**Comment by killakalle** [comment] 2021-07-03 21:39
Might be duplicate of #3857

**Comment by scd** [comment] 2021-07-26 02:14
For some reason stats got out of sync with the route. Reruning the stats fixed this one.

**Closed by scd** 2021-07-26 02:14 UTC
Labels: 2: Bug fix, Area: Statistics
