### ISSUE TITLE
parent map gets into funny state when moving last located child area.

### ISSUE THREAD

**Issue by scd** [theCrag/website#1077] opened 2013-04-29 04:25 UTC
I think this is a server problem, not a UI issue. I think the API provides buggered data.

If an area is unlocated, but has one located child then you move that child, the system still thinks the area has a cascading boundary, but it has buggered data, which causes the parent map to become erroneous.

**Comment by rouletout** [comment] 2020-12-18 08:15
Can't reproduce, super old - closing

**Closed by rouletout** 2020-12-18 08:15 UTC
Labels: 2: Bug fix, Area: API, Area: Maps
