### ISSUE TITLE
All ascents history of a route in gyms not working

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2173] opened 2016-04-12 09:47 UTC
As title. Gives an empty list. Also: no activity stream for a gym feature / line. At the end it's not straightforward to extract a list of ascents of a route or a feature / line.

**Comment by scd** [comment] 2016-04-12 21:59
Which gym. It sounds like there may be something wrong?

**Comment by birgander2** [comment] 2016-04-13 06:21
Two examples:
http://www.thecrag.com/climbing/germany/oberbayern/area/612829104
http://www.thecrag.com/climbing/germany/oberbayern/area/612839913
In the 1st link, I get an empty list for 'all ascents', while my own ascents are displayed correctly. In the case of the 2nd link, I seem to get the entire world's ascents displayed (no own ascents)...

**Comment by scd** [comment] 2016-04-13 12:19
I think I know what you mean. We are not showing the activity stream for the node and the ascents are difficult to find.

Under logbook -> Linie 56 ascents:
http://www.thecrag.com/climbing/germany/oberbayern/area/612829104/ascents
but it would be better to have stats links like a normal area

There is a stream but you cannot navigate there:
http://www.thecrag.com/climbing/germany/oberbayern/area/612829104/stream

Under the route pulldown -> all ascent history
http://www.thecrag.com/ascents/at//
which is the wrong url. Actually this is broken everywhere :)

**Comment by birgander2** [comment] 2016-04-13 13:00
Yes. And I think you still miss the first problem. Compare:
http://www.thecrag.com/ascents/at/830730198/
http://www.thecrag.com/ascents/at/830730198/by/356258205
The first link gives an empty list, the second shows something (but should be a subset of the first)

**Comment by scd** [comment] 2016-04-17 07:25
I have hot fixed the two links you referred too. How did you navigate to these links?

I think I need to do a full release for the other broken url. It works in my development server, so I think we may have fixed it coincidently. We will just have to wait until the next release goes out.

With regards to the gym streams. Do you want these appearing on the gym page. I think we need to have a more in depth discussion because they were intentionally left off so the page would be faster for ticking.

**Comment by birgander2** [comment] 2016-04-17 12:34
I was navigating to them by the route's pulldown, all ascents and my ascents.

Regarding the streams: I mainly found it annoying that it is spo hard / hidden to find out who had done the routes I get displayed. On a gym level it is ok, but on feature level (with 3 lines or so displayed) I would like to see the ascents of those routes. Maybe the same for sectors would be nice, too.

**Comment by scd** [comment] 2016-04-17 12:42
Ok we will probably engage a couple of other gyms with this one. I think it is important to get this right, and most probably we will end putting it back in.

**Comment by birgander2** [comment] 2019-04-05 07:27
I think this is resolved. "all ascents history" in the context meanu of a route seems to work now.

**Comment by Mdemaillard** [comment] 2020-03-26 08:14
confirmed working in 2 gyms for all ascents in gym, in a feature, in a single route.
Also the streams are visible everywhere. closing.

**Closed by Mdemaillard** 2020-03-26 08:14 UTC
Labels: 2: Bug fix, Area: Gyms, Area: Streams / feeds
