### ISSUE TITLE
add new date format to import

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2963] opened 2017-11-24 16:44 UTC
**What happened?**

"10.04.2012"

is rejected by the bulk import

**What you expected:**
additional format: DD.MM.YYYY

**Comment by scd** [comment] 2017-11-27 02:24
This is hotfixed in prod. 

@nicHoch where are you going to test it?

Please close when you are happy

**Comment by nicHoch** [comment] 2017-11-27 19:22
dates before 1969 are not excepted

**Comment by scd** [comment] 2017-11-28 00:12
Nicky, can you give an example. I just tested 1945-08-24 and it worked fine in dev.

There is a conversion to epoch to test if the date is a real date, but this allows for negative epochs which means we should be accepting dates up to early 1900s. The 1969 is near epoch zero.  Something strange is going on and I need the failure case to see if it is replicated in dev. This will point me to whether or not the issue is something in prod or a format issue.

Also are there any dates before the early 1900s?

**Comment by nicHoch** [comment] 2017-11-28 08:05
only the new date format did not work in this epoch:

"09.10.1969" (DD.MM.YYYY) was not working but 
"1969-10-09" (YYYY-MM-DD) was working fine.

Dates before 1900 i am not aware of but in this very historic areas it might be possible

**Comment by scd** [comment] 2017-11-28 22:27
That's weird. It seems to be working on my dev. Which server are you testing on? Can you send me the file?

**Comment by lordyavin** [comment] 2017-11-29 10:11
Got an error problem with an ascent:
![grafik](https://user-images.githubusercontent.com/1528540/33369731-cac2e93e-d4f5-11e7-94b1-7404d534f0d7.png)

But the stream displays the date incorrect:
![grafik](https://user-images.githubusercontent.com/1528540/33369816-017df1bc-d4f6-11e7-98f3-57b5eeec9882.png)

**Comment by brendanheywood** [comment] 2017-11-29 10:26
Stream event here:

https://www.thecrag.com/event/1529249688

template data is wrong:

"date": "2017-11-29",

**Comment by rouletout** [comment] 2021-01-03 08:33
This has been fixed with the new import - closing

**Closed by rouletout** 2021-01-03 08:33 UTC
Labels: 5: Enhancement, Data entry
