### ISSUE TITLE
Forum pagination bug

### ISSUE THREAD

**Issue by scd** [theCrag/website#3648] opened 2020-04-14 03:30 UTC
Hey Again :)

Noticed another bug. When you select `descendants` on the forum, hitting a different page (ie 2) breaks the descendants filter because the page is directly appended with the query string separator

Repro:

Go to
https://www.thecrag.com/climbing/australia/new-south-wales-and-act/forum?nodeFilter=descendants

Click second page, end up on:
https://www.thecrag.com/climbing/australia/new-south-wales-and-act/forum?nodeFilter=descendants?threadPage=2

Note `?threadPage=2`, should be concatenated with `&` instead. Manually changing the URL fixes it.

Thanks :)

**Comment by Mdemaillard** [comment] 2020-04-14 08:27
Duplicate of #3603

**Closed by Mdemaillard** 2020-04-14 08:27 UTC
Labels: 2: Bug fix, Area: Forums & Messaging
