### ISSUE TITLE
enable multible route ticking in faceted search

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2352] opened 2016-08-31 08:02 UTC
It is not possible to tick many routes at once if they are not located in the same parent node. With the faceted search it is possible to show a list of many routes side by side from many parents but it is only possible to tick every route on its own. 

use case: you climbed at a crag with many small sectors (boulder blocks) and climbed routes from many sectors on the same day. Right now you have to open each sector and tick routes separated.

**Comment by scd** [comment] 2016-08-31 08:06
I think the js will need upgrading.

Actually I think we need to refactor the dynamic menu js so it can be applied more widely and generically.

**Comment by rouletout** [comment] 2016-12-24 03:18
This was also a request by Jakob Schubert - should be doable from a list of search results

**Comment by brendanheywood** [comment] 2017-03-09 23:08
See also showing the ticks that you've already done:

https://github.com/theCrag/website/issues/1847

**Comment by brendanheywood** [comment] 2017-03-09 23:09
Closed #2643 as duplicate of this by @Drazhar

**Comment by Drazhar** [comment] 2017-03-10 05:51
Simon asked at #2643 how important multi logging is. For me there it's quite handy for two cases:

1. Log multiple ascents of the past. By logging then individual, I have to set the date each time.
2. The "default with" is handy. I think the with who you went climbing isn't that important.

The inline logging would at least help that you save time switching pages a lot.

**Comment by rouletout** [comment] 2022-09-10 19:09
Planned as follow up of the new ticking interface - keep open

**Comment by rouletout** [comment] 2022-10-01 14:15
Closing as this is available from eg Advanced Search (and soon from normal search) and the presets are kept for logging (date, who with).

**Closed by rouletout** 2022-10-01 14:15 UTC
Labels: 5: Enhancement, Area: Logbooks Ticking & tick lists, Area: Search and facets
