### ISSUE TITLE
In forum post, the quote `>` gets transformed to a `&gt;` when you hit "edit" and there is no way to go back.

### ISSUE THREAD

**Issue by FreddieChopin** [theCrag/website#3728] opened 2020-07-11 09:09 UTC
**What happened?**

1. Write a comment with a quote:
![Screenshot from 2020-07-11 11-02-50](https://user-images.githubusercontent.com/1139038/87220680-53e7c480-c366-11ea-9749-6bbeddbcb2c6.png)
2. Click "Add your comment":
![Screenshot from 2020-07-11 11-03-05](https://user-images.githubusercontent.com/1139038/87220690-64983a80-c366-11ea-831b-075df43f9b0a.png)
The comment has a quote block, this works fine.
3. Click on "edit"
![Screenshot from 2020-07-11 11-03-16](https://user-images.githubusercontent.com/1139038/87220695-75e14700-c366-11ea-8776-7d91706e21fe.png)
The `>` gets transformed into `&qt;`
4. **DON'T** click save, just go back and reopen this thread. The comment block is gone, even though the comment was not edited (there's no "versions" button):
![Screenshot from 2020-07-11 11-03-32](https://user-images.githubusercontent.com/1139038/87220725-b17c1100-c366-11ea-95c8-bf7cca667dcc.png)
5. Try to edit the comment, change the `&qt;` back to `>`:
![Screenshot from 2020-07-11 11-03-51](https://user-images.githubusercontent.com/1139038/87220735-c658a480-c366-11ea-9bc8-6b7c534cdcc8.png)
6. Click "save", the quote block is still not there:
![Screenshot from 2020-07-11 11-04-01](https://user-images.githubusercontent.com/1139038/87220742-dec8bf00-c366-11ea-8010-7eb8fbcccec3.png)

Example url(s) to reproduce the problem:
https://www.thecrag.com/discussion/3199886445/birds

**Comment by lordyavin** [comment] 2020-07-11 11:35
Duplicate of #2967

**Closed** 2020-07-12 08:40 UTC
Labels: 2: Bug fix, Area: Forums & Messaging, Feature: Markdown
