### ISSUE TITLE
Profile Page: Include a graph / stats on days climbed

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3457] opened 2019-06-02 22:57 UTC
**What happened?**

A statistic in the sense of "how many days did I climb in a specific period" would be nice. 

Ideally also provide screenshots:

**What you expected:**

A bar graph similar to the number of ascents on the CPR graph? Any good idea is welcome to answer this question.

**Comment by brendanheywood** [comment] 2019-06-05 11:27
This is mostly a duplicate of https://github.com/theCrag/website/issues/1220 so I'll close this and tidy that one up a little

**Closed by brendanheywood** 2019-06-05 11:27 UTC
