### ISSUE TITLE
Combined pitch descriptions don't display?

### ISSUE THREAD

**Issue by ajfclark** [theCrag/website#2204] opened 2016-05-21 23:18 UTC
I just tried to update the description of Twilight Zone and the final pitches don't display at all when entered as:

7-10. Meander R past Syrinx and the Wobble

Is there a better syntax for this kind of thing?

In the meantime I've just duplicated the pitch 4 times.

http://www.thecrag.com/climbing/australia/arapiles/tiger-wall-area/route/12908317

**Comment by scd** [comment] 2016-05-21 23:22
What you did is currently the best thing to do with the way the system interprets pitches at the moment.
What you suggest is a good idea.

**Comment by brendanheywood** [comment] 2016-05-22 23:24
@ajfclark I'm going to close this as it's a duplicate of #1571 - I'll ping you on that issue, could you please have a read of it and comment...

**Closed by brendanheywood** 2016-05-22 23:24 UTC
