### ISSUE TITLE
Setup postfix for relay to sparkhost

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2155] opened 2016-03-20 04:56 UTC

**Comment by scd** [comment] 2016-03-22 00:30
How long does it take postfix to get through a queue of say 50k emails?  

Can you queue jump? For example if you are sending out a big mailout and somebody requests a reset password link.

**Comment by brendanheywood** [comment] 2016-03-22 01:06
A good question, I've not done this. Postfix can have multiple queues and relays, and rules for prioritizing them. Generally our focus is just never having a large clump in the queue

**Comment by scd** [comment] 2016-03-22 01:21
At the moment this is not an issue for us because we have a queue with a couple of priorities. Any email that the system sends is kept in the system. It is placed in a queue with a priority and sent via a deamon. 

Clearly we could just keep using this and interface to postfix rather than directly to sparkhost. However there are some other considerations I want to take into account.

There are two things I did not know about when implementing our mail system. Firstly the possibility of using postfix (maybe the install procedure was not so simple 10 years ago). Secondly APIs to the email server that is sending our emails, which means we can keep emails by getting them from the email server rather than storing them. This means that emails could be sent outside the system and they will still end up in the system. For example all our correspondences to particular email addresses in google could be stored in the system.

I would like to get rid of the systems email queue (actually it is a communications queue and could include SMSs as well for example) because it is another thing that could go wrong. It also can have a thirty second delay as it is a polling system. I don't want to do this until I can confirm that Postfix handles multiple priority queues.

Like always, nothing is as simple as it first seems.

Also, given your rave, it is likely that I will end up using Postfix in my current commercial project, so maybe I should do it there first.

**Comment by scd** [comment] 2021-01-10 07:20
Closing as this will be managed internally if required.

**Closed by scd** 2021-01-10 07:20 UTC
Labels: 5: Enhancement, Area: Administrivia / settings / emails / T&C, Performance
