### ISSUE TITLE
Free Solo Ascents not in filter

### ISSUE THREAD

**Issue by braeuni** [theCrag/website#4221] opened 2023-08-16 08:42 UTC
The filter for free solo ascents does not filter for the new ascent style.

![grafik](https://github.com/theCrag/website/assets/7069305/46be3eb8-7140-401d-8a69-15eae1775470)

![grafik](https://github.com/theCrag/website/assets/7069305/790c777d-d2fe-46b0-8797-1b78d03af497)

**Comment by lordyavin** [comment] 2023-10-24 20:53
As mentioned in #4222, the facet search supports old and new ticks. Checkout the filter "Stil" where you are going to find the gear style "Free Solo".
https://www.thecrag.com/en/climbing/germany/frankenjura/alpenvereinswand/ascents/with-climbed-gear-style/solo/?sortby=when-climbed,desc

![grafik](https://github.com/theCrag/website/assets/1528540/39a0b294-7893-4b9d-9750-cf8ed09b80a7)

https://www.thecrag.com/en/climbing/germany/frankenjura/alpenvereinswand/ascents/with-climbed-gear-style/sport/by/sbrx/?sortby=when-climbed,desc
![grafik](https://github.com/theCrag/website/assets/1528540/57a0ec27-7953-429d-a1e2-46a00d57b505)

**Comment by lordyavin** [comment] 2023-10-24 20:55
Closing as duplicate of #4222

**Closed as completed by lordyavin** 2023-10-24 20:55 UTC
Labels: 2: Bug fix, Area: Logbooks Ticking & tick lists, Area: Search and facets
