### ISSUE TITLE
302 Moved - when adding 20 new routes

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2956] opened 2017-11-17 05:55 UTC
**What happened?**
I added a bunch of new routes to a new [crag](https://www.thecrag.com/climbing/austria/area/1512957633) and saved them. Then I got the 302 Moved error:

>Moved
>
>The server encountered an internal error or misconfiguration and was unable to complete your request.
>
>Please contact the server administrator, scd@thecrag.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.
>
>More information about this error may be available in the server error log.
Apache/2.2 Server at www.thecrag.com Port 443

Got that error several times before but never reported it. Luckily the process does not fail to add the routes. They are all there but the error is quite confusing and misleading.

**What you expected:**
No error message if there is no problem? I'm not sure what to expect.

**Comment by scd** [comment] 2017-11-17 05:58
Hmm, this is new. Just while your memory is fresh

Did you create the area then immediately afterwards add routes?

**Comment by lordyavin** [comment] 2017-11-17 06:04
Yes I did.

I read about the semantic of http status code 302 in the [RFC7231](https://tools.ietf.org/html/rfc7231#section-6.4.3). Maybe something is wrong with the Location header field so that the agent (in may case Firefox 57) is not able to redirect to the correct URI.

**Comment by lordyavin** [comment] 2017-11-17 06:08
BTW: Could you change the grade system to FR for this new crag. I think I set it before saving but it didn't apply.

**Comment by scd** [comment] 2017-11-17 06:18
This means it will start happening more often. Firefox has just done a major upgrade, so if you have got further routes to update then maybe you can add another couple and test again for us. Test adding one and test adding multiple.

I updated the area to FR

**Comment by lordyavin** [comment] 2017-11-17 06:32
I got the problem with previous versions of Firefox too. I'm not exactly sure if it always happens with Firefox. At home and mobile I use mainly Chrome. I could test it on sandpit.

**Comment by lordyavin** [comment] 2017-11-17 06:37
To be honest, I have no idea how to reproduce this error. Added a new test crag on sandpit and added 10 routes immediately. No error.

**Comment by scd** [comment] 2017-11-17 06:41
Thanks for trying. Keep logging it when it occurs and maybe something will become clear in how it is reproduced.

**Comment by nicHoch** [comment] 2017-11-17 07:57
I also had that error several times before. Sorry i did not reported it before but as @lordyavin pointed out no data is lost only the last redirect to the node where routed has been added is not working.

It happens if you add routes to a node and the time duration between starting and finishing the editing exceeds a certain span. It does not depends on the number of routes but the editing most likely needs more time if you add many routes at ones.

**Comment by birgander2** [comment] 2017-11-22 09:52
I also had this error several times, and already ages before. Usually when adding 30 routes, so I thought it is due to that, but Nicky might be right that it is due to the editing time span.

**Comment by lordyavin** [comment] 2017-12-20 09:16
Got the error again while adding routes via this [form](https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?routes=20&C%3APushReturnURL=%2Fclimbing%2Fsouth-africa%2Fmpumalanga%2Farea%2F1593733434&D%3ANetworkNodeID=1593733434&C%3AState=2059&D%3ANumberClimbs=20&D%3ASkipCite=1&C%3AHideNavigation=1). Routes were added correctly. See https://www.thecrag.com/climbing/south-africa/mpumalanga/area/1593733434

**Comment by lordyavin** [comment] 2017-12-20 15:44
And again [URL](https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?routes=20&C%3APushReturnURL=%2Fclimbing%2Fsouth-africa%2Fmpumalanga%2Farea%2F1593733494&D%3ANetworkNodeID=1593733494&C%3AState=2059&D%3ANumberClimbs=20&D%3ASkipCite=1&C%3AHideNavigation=1). Looks like this always happens if I use the "add 20 routes". form.

**Comment by scd** [comment] 2017-12-20 21:13
I think the quick fix is to make 10 routes the maximum.

**Comment by nicHoch** [comment] 2017-12-20 21:17
no please do not limit to 10. i usually never started to add routes less than 20 per node.
the error is annoying but not critical because in the end everything is added.

**Comment by scd** [comment] 2017-12-20 21:22
So maybe I look at extending time out by 20%

**Comment by brendanheywood** [comment] 2017-12-20 22:28
Why not just extend for say 2x or 3x?

**Comment by lordyavin** [comment] 2017-12-21 06:55
Why is there any timeout at all? Don't get the point. Someone could start the adding and leaving the form for hours before saving. This is a valid use case.

**Comment by scd** [comment] 2017-12-21 07:18
No it is the webserver time out. If a connection does not return a result within a certain time the connection is timed out. I have not played around with these settings for a long time and am only guessing that it would partly solve the issue.

**Comment by lordyavin** [comment] 2017-12-21 21:55
So the website and the forms are not stateless? Uh ... don't know if I like that.

**Comment by scd** [comment] 2018-01-01 06:51
@lordyavin approximately how long are you waiting when you get this problem? Minutes?

Our server timeout is quite long so I am guessing that this is not the issue here.

Next time it happens can you please note the time so I can search the error logs.

**Comment by lordyavin** [comment] 2018-02-02 07:49
Hey @scd, tried to reproduce the bug on sandpit. I created a [new crag](https://sandpit.thecrag.com/climbing/test-area/area/1643170046) and added 30 routes at once. It took me about 4 minutes and 40 seconds to click the save button. Of course this isn't a real example, but I got an error:

> **Internal Server Error**
> The server encountered an internal error or misconfiguration and was unable to complete your request.
>
>Please contact the server administrator at scd@thecrag.com to inform them of the time this error occurred, and the actions you performed just before this error.

> More information about this error may be available in the server error log.
Apache/2.4 Server at sandpit.thecrag.com Port 443

Unfortunately not the error I was seeking for :wink:

**Comment by nicHoch** [comment] 2019-05-19 16:24
+1 mail

**Comment by rouletout** [comment] 2020-11-30 18:36
Does this still happen? I never saw that in the last year or longer anymore.

**Comment by rouletout** [comment] 2021-01-03 08:31
Doesn't seem to happen anymore - closing

**Closed by rouletout** 2021-01-03 08:31 UTC
Labels: 2: Bug fix, Content editing
