### ISSUE TITLE
How to upload an Image on mobile (Android)?

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#1919] opened 2015-04-30 13:51 UTC
Hi

i tried to upload an image for a topo but both ways failed:

1: the "add Files" button is not working at all
2: the "load from an image URL" (i used an url from an image in my dropbox) opens the next page (select routes ...) but the image never shows up.

i use Chrome

Nicky

**Comment by brendanheywood** [comment] 2015-04-30 13:53
What was the url, and is it publicly available?

**Comment by nicHoch** [comment] 2015-04-30 14:05
https://www.dropbox.com/s/nryklvcme35ldo5/20150430_125520.jpg?dl=0

but it might be that this is not a direct url of the image itself. Just a page where the image is presented

Nicky

**Comment by brendanheywood** [comment] 2015-04-30 14:10
yeah thats a html page, try

https://photos-2.dropbox.com/t/2/AACLozUwdlE1wISyDIZmnmswGSr8o3tHgnRQ8otB6EgIhA/12/58155195/jpeg/1024x768/3/1430409600/0/2/20150430_125520.jpg/CLvB3RsgASACIAMoASgC/RiBxj_u-sOruCUPrDFHRfw0ReXC3RnRpaoTGznCBiAw

They've gone out of their way to get the raw url pretty hard

**Comment by nicHoch** [comment] 2015-04-30 14:27
any chance to get the "add files" browser upload working on a mobile devise?

The way of taking an image -> upload it to dropbox -> get the raw photo url and finally -> use the "load from a url" seams a bit complicate in the fields.

**Comment by brendanheywood** [comment] 2015-05-01 03:54
yeah this happens a bit, it's a moving target on mobile and usually just means we have to upgrade our version of the plupload library

**Comment by lordyavin** [comment] 2015-07-08 09:10
Hi there. Since some months I own an Android device and I'm missing the photo upload too. When are you going to fix this?

**Comment by scd** [comment] 2015-07-08 10:23
Due to personal circumstances we have not been able to do a release for some months now. I plan to look into seeing if a simple plupload new version fixes this issue for next release. We have not scheduled what will be in the new release yet as there are some several important big issues we need to work on.

**Comment by lordyavin** [comment] 2015-07-08 11:27
Never mind - as long as you fix it.

**Comment by lordyavin** [comment] 2015-07-09 05:28
Yesterday night I tried to upload an image again. And guess what - it worked. Did you update something?

**Comment by lordyavin** [comment] 2015-07-24 06:41
Gave it another try. The button "Add Files" is still not working properly if I touch on it. Layout should change for mobiles.

**Comment by lordyavin** [comment] 2015-08-07 06:26
Sorry, but I have to complain about this issue again. forget what I said a month ago. I need this fixed. I don't want to anoy you. Just a reminder.

**Comment by scd** [comment] 2015-08-07 08:35
I am working through the issues on the next release. I will look at this as part of this release. Your reminder was fine because I had not assigned it to the release yet. 

Just so you know, all developers at thecrag have been fairly distracted for a couple of months so it has been a while between releases.

**Comment by scd** [comment] 2015-08-11 06:49
@lordyavin I have just upgraded our third party software to the latest version and hot fixed in production. It worked for my andriod, but this is very old now. Could you please test?

**Comment by nicHoch** [comment] 2015-08-11 18:00
Does not work. Pressed the add file button and nothing happens.
Nicky
Am 11.08.2015 08:49 schrieb "Simon Dale" <notifications@github.com>:

**Comment by scd** [comment] 2015-08-11 23:49
bugger, it works on mine. I don't have access to another andriod. We are going to have to debug somehow. I have done some reading and this problem has popped up in various environments. One suggestion is a z-index hack to fix the problem. It is a total shot in the dark, but I have made a further change to prod, @nicHoch could you please retest.

Failing that could you please test pluploads, jsfiddle version:

http://jsfiddle.net/gh/get/jquery/1.9.1/dependencies/ui/jayarjo/plupload-demos/tree/master/2.x/queue/bundled

**Comment by lordyavin** [comment] 2015-08-12 05:35
Not working on my phone Sony Xperia Z3 Compact. Android 5.1.1, Chrome browser.

**Comment by scd** [comment] 2015-08-12 06:55
@nicHoch, do you have any time to play around with the jsfiddle and work out what we are doing that is breaking it. The javascript is in the html of the upload page, so progressively change stuff in the jsfiddle until it breaks or eventually is the same as our html page. If you do not have time for this then we will have to look for a plan B approach. I have got no devices which fail, so this is extra hard to debug.

**Comment by nicHoch** [comment] 2015-08-12 08:00
Hi Simon

Still not working on prod.
But on fiddler it works just fine.

What exactly should i do on fiddler?

Nicky
Am 12.08.2015 08:55 schrieb "Simon Dale" <notifications@github.com>:

**Comment by scd** [comment] 2015-08-12 08:33
I have never played with jsfiddle, but my understanding is you can make live changes and see what the result is. If you look at the raw html code of our upload page then you can see how our plupload is configured. Is it possible to progressively make changes to the jsfiddle until it breaks. 

I have never done this before so I am just guessing. It may not be possible to do what I am suggesting, or it may be very tedious. 

If you have any other suggestions then I am all ears.

**Comment by nicHoch** [comment] 2015-08-12 09:11
The problem is all sourse codes are somehow binary encoded.
Am 12.08.2015 10:33 schrieb "Simon Dale" <notifications@github.com>:

**Comment by brendanheywood** [comment] 2015-08-12 09:17
You mean the js one our prod site or the minified source for plupload? In either case just lop of the 'min' from the filename to see the original

**Comment by scd** [comment] 2015-08-13 00:44
@brendanheywood in my development environment I have parred back our plupload configuration to something almost the same as the demo version:

http://www.plupload.com/examples/queue

On Chrome on my mobile the demo version works but our similarly configured parred back version does not. Is it possible that we have some javascript touchscreen handling in our general libraries that is interacting with unintentional side effects?

**Comment by brendanheywood** [comment] 2015-08-13 00:57
Completely possible, just remove them all and add em back to see which script. Are you getting any js console errors?

**Comment by scd** [comment] 2015-08-13 02:38
I am well on my way to getting to the bottom of this. I have isolated it to the FastClick function, but have to go to lunch now.

**Comment by brendanheywood** [comment] 2015-08-13 02:39
Just kill it completely,I thought I had turned that off but perhaps only in common and not in process? It's the root cause of a bunch of touch bugs

**Comment by scd** [comment] 2015-08-13 03:53
Killing it fixes this problem, but the node.select event is no longer triggered for touch screens. This is used in the list view, in particular is needed to edit gym routes. 

FYI, the FastClick is only in common and was well and truly alive.

It needs a bit more thought. Maybe I could hack something for now by just turning it off for this upload form. 

If we no longer use FastClick, what should be done instead?

**Comment by brendanheywood** [comment] 2015-08-13 04:07
If we use fastclick we need to be very selective about only turning it on specific items, not open slather. eg apply to the header and to the table in list view. I'd still prefer to get rid of it completely as it messes up the header menus and makes for lots of weird offset click events when scrolling and janks up a lot. It also clashes a bit with the topo touch events which also need some love.

Fastclick just sends fake click events but faster, so if events are registered using a 'click' they should just keep working. If not there is something else going on, which could be an even deeper root issue

I'd prefer to can it, and then get it back into a clean working state using raw events, and then build up better touch events directly with more control.

**Comment by scd** [comment] 2015-08-13 04:38
Your right there is something else going on with the node.select. Gym nodes are working but outdoor node crags are not. As long as the gym is working I am ok with completely disabling fastclick.

Any problems with me doing a hot fix with this one?

**Comment by brendanheywood** [comment] 2015-08-13 04:49
push your fixes and I'll take a look tonight, I don't want to hotfix a regression of touch for 99% of the site, it all has to keep working.

**Comment by scd** [comment] 2015-08-13 05:02
Pushed, but the only thing I have done here is disable FastClick in the common file. I have not removed the code, but just commented out the last couple of lines of code in the file, which seems to be what enables it.

If your testing is ok, then I am ready to go with the hotfix.

**Comment by scd** [comment] 2015-08-13 22:46
@brendanheywood how did you go with testing this last night. It is ok if you are busy and want to push this back to me.

**Comment by brendanheywood** [comment] 2015-08-14 00:28
Started testing and list view is noticly better performing, but didn't get to the bottom of the select issue but have an idea that its an event ording issue which was different with raw click which means it is selecting and then in selecting the checkbox instantly. I've got work hassles now but will look later

**Comment by scd** [comment] 2015-08-14 08:48
I hope you get through your work issues. Don't worry too much, I can take a look after I have finished what I am currently working on.

**Comment by brendanheywood** [comment] 2015-08-14 13:40
I dunno what is going on here. It's something else completely, all the custom jquery events are simply not being fired and I can't figure out why. It looks like something somewhere else after page load is unbinding all events on document

**Comment by brendanheywood** [comment] 2015-08-14 15:21
Ok finally got to the bottom of this and it was a complete red herring. When the stream loaded it ajax'es in a complete html doc including scripts which are dups and re-run a bunch of stuff and reset everything. I really like what you did with the progressive ?embed=1 and ?embed=2, I've gone ahead and made an embed=3 which is even more minimal html chunk so there is less data over the wire and we skip the event stuff.

I've ONLY done this with the area stream only, I had a look at the account and route streams and I think the embed levels are not consistent? Route seems to use =3 already,

**Comment by scd** [comment] 2015-08-14 23:04
I was going to write up the progressive embed, because it solved some problems quite nicely. I forgot then got distracted.

That sounds like I can do the hot fix, because the streams are not in prod. Did you make any changes that are required for this hot fix? I have the js files from my changes ready to go on prod and static, I just need to point to them. If you have made any other changes then I will have to upload them again.

**Comment by brendanheywood** [comment] 2015-08-15 01:23
Yeah there is js and templates stuff, but please check and fix if needed the other streams I've only fixed areas

**Comment by scd** [comment] 2015-08-18 05:38
I have checked various things with the multi level embed in the streams and completed the work for account/stream. There are a couple of things. 
 * area/stream and route/stream templates are the same, sym link. There are a few templates like this which implies to me we should think about our page template structure again sometime. Not now though.
 * I will create an issue for us to make some more rigerous definitions for multi level embedding. For streams we only need levels 1 & 3. Level 2 can be used as a debugging level for streams, but may be useful in other situations. 
 * If there is nothing in the next stream window the system needs to show this somehow so it does not look broken. I will create another issue for this.

Anyway I am closing because this issue is complete in dev and waiting the next release. @lordyavin, unfortunately there this fix is touching too many things to risk a hot release.

**Closed** 2015-08-18 05:38 UTC
Labels: 1: MUST BE RESOLVED FOR RELEASE, 2: Bug fix, Mobile / Responsive

**Comment by brendanheywood** [comment] 2015-08-18 06:28
> area/stream and route/stream templates are the same, sym link.

This is fine, I think it's good to refer to separate templates and then let the templates choose or not to re-use other subtemplates or delegate to another template. I've done this a few times in places but I've used hash /  mason features to do it instead of symlinks ie:

```
<& some/other/template, %ARGS &>
```

This also makes it cleaner to add a tiny bit of route or area specific stuff and then pass it on to a common template.

**Comment by lordyavin** [comment] 2015-08-26 06:32
Where can I see the scheduling of milestones and releases?

**Comment by brendanheywood** [comment] 2015-08-26 06:38
https://github.com/theCrag/website/milestones

However while we do plan stuff and try to do batches of related things together there is no guarantee of the timeliness or the order of stuff.
