### ISSUE TITLE
Avoid duplicated adds in PDF guides

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2822] opened 2017-07-04 15:04 UTC
**What happened?**
![dup_adds](https://user-images.githubusercontent.com/1528540/27835316-cbb64898-60da-11e7-88d4-3f874c304014.png)

**What you expected:**
Mix the adds so no duplicates on one page.

**Comment by scd** [comment] 2017-07-04 22:11
This only happens because we don't have enough advertisers. We either show one advertisement or 4 advertisements.

We need to change the model so that advertisements can appear in the document, rather than just the beginning. Also different banner sizes. These two changes will give us the flexibility to just show one ad.

**Comment by rouletout** [comment] 2021-01-03 07:54
Closing based on explanation - this is by design

**Closed by rouletout** 2021-01-03 07:54 UTC
Labels: 5: Enhancement, Area: PDF, Area: Sponsor/Stakeholder
