### ISSUE TITLE
When locate a crag on the map, sometimes? the tooltip text show the name of another crag. 

### ISSUE THREAD

**Issue by FredrikEckardt** [theCrag/website#3654] opened 2020-04-25 09:49 UTC
**What happened?**

I have not been able to understand exactly when this happen, but I have seen it several times. 
I think only when drawing location first time. (Not when editing location). 

When drawing / locating a crag on the map, the tooltip text show the name of another crag than the one I am drawing location for. When it has happened, it has been a crag name I have recognised.
Not very serious, but a bit annoying. When it happens, I think I clicked on the incorrect crag (and are on my way to draw it incorrect on the map ...) 

Ideally also provide screenshots:

**What you expected:**

That the tooltip text show the name of the crag I am drawing / locating.

**Comment by rouletout** [comment] 2020-04-25 13:56
+1 - happens every time I draw a new crag - seems to pick the tooltip from a nearby crag.

**Comment by matozoid** [comment] 2020-04-25 17:57
+1 - yes, it's rather confusing. "I thought I was editing X but it says Y"

**Comment by Mdemaillard** [comment] 2020-04-26 15:51
Duplicate of #1295

**Closed by Mdemaillard** 2020-04-26 15:51 UTC
Labels: 5: Polishing, Area: Maps
