### ISSUE TITLE
Feature to "unwatch" a noisy discussion

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2853] opened 2017-07-20 07:53 UTC
**What happened?**
I follow Brendan to get notified if he creates new pseudo accounts. He recently added a comment to a very busy discussion. Since then I get this discussion in my stream but I'm not interested in. I would like stop this discussion to appear in my stream.

**What you expected:**
A context menu entry that gives me the possibility to mute/unwatch a discussion.

**Comment by scd** [comment] 2017-07-20 08:21
Watching/unwatching dicussions and forums is quite important. There are some structural changes required.

I am confused that you can watch Brendan create pseudo accounts. I presume you are watching him change history entries for routes.

**Comment by lordyavin** [comment] 2017-07-20 10:12
@scd you are right just watching him change history entries for routes.

**Comment by scd** [comment] 2017-07-20 11:50
Also is it the discussions in the streams or the discussions on the top of
the dashboard

**Comment by lordyavin** [comment] 2017-07-20 12:18
I would say both.

**Comment by brendanheywood** [comment] 2017-07-20 12:43
I'm going to close this as a duplicate of this, and I'll add an extra vote to it:

https://github.com/theCrag/website/issues/1828

**Closed by brendanheywood** 2017-07-20 12:43 UTC
Labels: 6: New Feature, Area: Forums & Messgaging

**Comment by brendanheywood** [comment] 2017-07-20 12:46
And also partially covered by this one too: https://github.com/theCrag/website/issues/1449

**Comment by brendanheywood** [comment] 2017-07-20 12:50
Specifically on the use case here, I think in @lordyavin 's stream he should see comments that I make if he is watching me, but he shouldn't be automatically subscribed to all discussion threads that I comment in. That's a subtle distinction. If he see's my comment he can open up the forum and decide to follow it. But if he doesn't then he shouldn't see any more notifications around that thread unless I comment again.

If you guys think this is the case then this is separate enough from those other two issue to re-open this to focus on that bit?

**Comment by lordyavin** [comment] 2017-07-21 07:12
You are right. I'm interested in your activities not the comments of others on a shared discussion with you. So only your comments shall be displayed in my stream.
