### ISSUE TITLE
Topo: Can not draw Annotations

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2604] opened 2017-02-19 02:54 UTC
As an example I would like to draw 3 sub-sectors of this crag https://www.thecrag.com/climbing/united-states/homestead/area/1049626368 
The sub-sectors are just separated by Annotations but they are not available for topo drawings.

**Comment by brendanheywood** [comment] 2017-02-19 06:26
Closing as a duplicate of #1693

**Closed by brendanheywood** 2017-02-19 06:26 UTC
