### ISSUE TITLE
Empty "Insert before" field still buggy

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4162] opened 2022-12-24 10:14 UTC
![image](https://user-images.githubusercontent.com/17315806/209431374-c572129d-d160-47e7-b278-875db793baa6.png)
I've left empty the field "Insert before" for these 3 routes in the red square expecting them to be placed at the end of the wall, but instead, they were placed before "Tempio del fumo" because the 2 routes in the green square had the field "Insert before" set to "Tempio del fumo" and thus, the red routes took that value from the green ones.

![image](https://user-images.githubusercontent.com/17315806/209431421-b39f37bd-e500-4ecb-b4a5-0a3b96fe8fe0.png)
Properly placed

![image](https://user-images.githubusercontent.com/17315806/209431428-d7a7f57b-0a95-45cc-bc0a-eb0e0536428e.png)
Not properly placed

**Comment by rouletout** [comment] 2022-12-26 03:02
Duplicate of https://github.com/theCrag/website/issues/4060 - closing

**Closed as completed by rouletout** 2022-12-26 03:02 UTC
