### ISSUE TITLE
Activity feed on other user's profile page not showing anymore

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4188] opened 2023-03-22 10:18 UTC
When visiting another user's profile, the activity feed is not shown anymore.

To reproduce
1. Go to another user's profile, e.g. https://www.thecrag.com/climber/rouletout
2. Scroll down to where the feed should be

Expected:
- Activity feed is shown with the user's recent activity

Actual:
- Activity feed missing completely

![image](https://user-images.githubusercontent.com/30682796/226872286-f7f8cfcb-94fe-4133-86e6-f428a6aa2cd0.png)

Additional Information:

- I use OSX. This happens to me on both Chrome and Safari
- When I browse my own profile, then the Activity Stream loads

![image](https://user-images.githubusercontent.com/30682796/226872871-34d968aa-7162-4819-9545-566708ce8cba.png)

**Comment by rouletout** [comment] 2023-03-23 11:48
Duplicate of https://github.com/theCrag/website/issues/4183

**Closed as not planned** 2023-04-08 22:56 UTC
