### ISSUE TITLE
Browsers back button produces error on

### ISSUE THREAD

**Issue by pas-calc** [theCrag/website#3806] opened 2020-12-06 10:19 UTC
Tried to delete an image but went back using browser's back button

```
Error

Cannot continue process: Error: running system command: ssh -i /opt/CIDS/files/localstate/image-transfer.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -q root@128.199.137.109 "rm /mnt/volume-sgp1-02/cas-image/ab/c6/abc60431017de0b0d5bf04401edb528c12ed1589" Error: running system command: ssh -i /opt/CIDS/files/localstate/image-transfer.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -q root@148.251.189.157 "rm /opt/CIDS/files/cas-image/ab/c6/abc60431017de0b0d5bf04401edb528c12ed1589" Error: running system command: ssh -i /opt/CIDS/files/localstate/image-transfer.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -q root@128.199.137.109 "s3cmd del s3://thecrag-images-production/ab/c6/abc60431017de0b0d5bf04401edb528c12ed1589"

State: 8626

Error Code: 4

CodeReference: CIDS::Process::SupplyInformation::ReviewPhoto, /opt/CIDS/perllib/CIDS/Process/SupplyInformation/ReviewPhoto.pm, 1202 
```

The same seems to happen with all kind of confirmation requests on the webpage, when going back one needs to start the process again (submit button "Return to start of process")
URL = https://www.thecrag.com/CIDS/cgi-bin/cids.cgi

Edit: now this even happens without browser back , it is not possible to remove this image, same  error message is displayed

**Comment by rouletout** [comment] 2021-01-15 11:39
Can you please provide a link to the image in question?

**Comment by pas-calc** [comment] 2021-01-15 12:50
> Can you please provide a link to the image in question?

no I cannot since I deleted the image finally not using the "back function", additionally it was independent of the image in place (tried it using different images, but always as described above)
Additionally, it is critical because the system error leaks information of the programs in use

**Comment by rouletout** [comment] 2021-01-15 14:12
I can't reproduce this, whgen do you hit the Back button? When you have to confirm the remove? I do not get an error at any stage of the process when hitting back.

**Comment by pas-calc** [comment] 2021-01-15 16:09
> I can't reproduce this, whgen do you hit the Back button? When you have to confirm the remove? I do not get an error at any stage of the process when hitting back.

I am sorry that this cant be reproduced. Still it is like I described in my initial post. Since it is a time ago I cannot add more details than there are

**Comment by rouletout** [comment] 2021-01-15 16:32
OK, seems to be gone, closing

**Closed by rouletout** 2021-01-15 16:32 UTC
Labels: Area: Photos (videos)
