### ISSUE TITLE
Data Entry "New Routes" gives error

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2651] opened 2017-03-15 23:09 UTC
This error occurs frequently on entering 10 or more routes at this area: https://www.thecrag.com/climbing/united-states/jacks-canyon

This happens even without any double name entries!

![error](https://cloud.githubusercontent.com/assets/19162952/23974662/9d356712-0999-11e7-90d7-fb0a50faff48.png)

**Comment by scd** [comment] 2017-03-21 01:58
@ulf i have done a bit of investigating and have found a failure case, but I am not sure if this is the cause or not. The current code has an inconsistency between the API dup name check and the UI name check. One was case insensitive and the other was not. This could lead to the situation you have here.

I have also updated the error so that the name of the route is returned in the error message. This will make it easier for me to investigate next time, if I have not actually fixed the problem you are seeing.

If this happens again before the release could you please count the curly brackets before the name error then do a browser back and count the records down to get the name of the route that caused the error. After the release the name will be in the error message.

I don't know whether to close this or not. I will only do more work on this issue if it comes up again. Ulf can you close it if you are happy that I have done sufficient for now, but re-open or log a new issue if you see it again.

One the release has happened then I think it is important to keep logging 10 routes at a time to make sure this is not still happening.

**Comment by scd** [comment] 2017-03-27 03:57
I am closing this one. Please reopen if occurs again

**Closed by scd** 2017-03-27 03:57 UTC
