### ISSUE TITLE
Erroneous stream events show edits of grades which never happened

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3451] opened 2019-05-25 12:38 UTC
**What happened?**

I went to an area, added a single tag 'Closed' and it looks like I set or changed a whole bunch of grade which I did not:

https://www.thecrag.com/event/2511395145
![image](https://user-images.githubusercontent.com/187449/58369454-d7b1d800-7f3d-11e9-9eb8-f13b5b46d6ad.png)

I believe this is due to some internal new state being saved. Ideally I would like to run an internal batch update of all of these in the whole world so we don't get more misleading edit events.

**What you expected:**

* [ ] Stream event should only show the Closed tag an no touches to grades

**Comment by brendanheywood** [comment] 2019-06-03 23:44
https://www.thecrag.com/event/2535550176

**Comment by scd** [comment] 2019-06-04 00:13
This is an old bug when we upgraded the way grades were being stored. The first time somebody does a bulk edit the grades are updated. There are probably only a handfull of these left.

**Comment by brendanheywood** [comment] 2019-06-04 00:54
I see it a lot. It feels to me like every grade was like this and so every grade that gets touched has this happen the first time. Can we get a proper metric around this? I'm assuming that it doesn't affect any new routes created since that internal change

**Comment by brendanheywood** [comment] 2019-06-04 00:57
I can create this bug on demand, basically an edit to any old area:

https://www.thecrag.com/event/2535852948

**Comment by Mdemaillard** [comment] 2020-03-04 10:27
ah now i understand, seen this behaviour all around south africa as well.

**Comment by Mdemaillard** [comment] 2020-03-11 12:52
Duplicate of #2137

**Comment by Mdemaillard** [comment] 2020-03-15 09:21
+1 for internal batch run to close that issue. this is confusing to new users.

**Comment by killakalle** [comment] 2020-06-23 06:51
+1

See related event:  
https://www.thecrag.com/event/3422750445

**Comment by scd** [comment] 2021-01-11 04:09
Known issue from a badly managed grade enhancements some years ago. This is only ever a once off for an area so I don't propose to fix this. Closing

**Closed by scd** 2021-01-11 04:09 UTC
Labels: 2: Bug fix, Area: Streams / feeds, Content editing, Feature: Grades
